guardian/service-catalogue

package-lock.json, package.json, packages/cdk/bin/cdk.ts, packages/cdk/package.json, packages/cdk/tsconfig.json, packages/common/aws/s3.ts, packages/common/config.test.ts, packages/common/config.ts, packages/common/github/github.ts, packages/common/sleep.ts, packages/repo-fetcher/src/handler.ts
This branch fixes linting and moves to use the root tsconfig.json for the cdk package.
=> Fix linting, move tsconfig.json to root

jest.config.js, package-lock.json, package.json, packages/common/aws/kms.test.ts, packages/common/aws/kms.ts
This PR makes calling the `decrypt` function in `kms.ts` slightly safer and adds some tests.
Tests run & pass!
Depends on: https://github.com/guardian/github-lens/pull/7
=> Add KMS tests

package-lock.json, packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/package.json, packages/repo-fetcher/src/handler.ts
Use the latest version of GuCDK, good practise to stay up to date, stop dependabot complaining too.
=> Bump GuCDK to version 47.3.3

README.md, scripts/setup.sh
This change adds a `setup_node_env` script which tries to use `fnm` or `nvm` to configure your node environment and run `npm install`, in order to more comprehensively set up the project in a first time run.
Run the script!
Does this feel like an easier developer experience?
=> Update ./script/setup.sh to setup node environment

package.json, packages/common/aws/s3.ts, packages/common/config.ts, packages/common/github/github.ts, packages/repo-fetcher/src/handler.ts
This is slightly neater as the GitHub client dependency is handed in making it mockable and reducing the number of instances of client needed.
Tests pass!
=> Hand github client dependency to github functions

packages/common/aws/kms.ts, packages/common/aws/s3.ts, packages/common/github/github.ts, packages/common/log/log.ts, packages/github-lens-api/src/handler.ts, packages/repo-fetcher/src/handler.ts
Adds support for log levels via a `LOG_LEVEL` env var. Largely based off: https://github.com/guardian/tracker/blob/cb2695a12ee0c446df6e4ffcc9969d5650b59dc1/packages/common/src/logger.ts.
Try out different levels locally using e.g. 
LOG_LEVEL=trace npm -w packages/repo-fetcher run dev
(Note you may want to add some trace log lines first.)
=> Improve logging

.gitignore, README.md, package-lock.json, package.json, packages/common/github/github.ts, packages/github-lens-api/src/app.ts, packages/repo-fetcher/src/handler.ts, test/README
We're looking at using a DEV S3 bucket for this, removing the need for the internal logic.
=> Revert "Jb/facilitate development"

packages/common/config.ts, packages/repo-fetcher/src/handler.ts
Co-locating all configuration makes it easier to see what configuration is needed.
=> refactor: Add log level to `Config`

packages/repo-fetcher/src/handler.ts, packages/repo-fetcher/src/transformations.test.ts, packages/repo-fetcher/src/transformations.ts
Tweaks some namings and replaces RepoAndOwner class with an interface. The main aim is to make the handler more readable - some of this is subjective for sure but overall I think this is an improvement.
=> Small refactor to improve readability

packages/github-lens-api/src/app.ts, packages/github-lens-api/src/expressRoutes.ts
list valid endpoints for invalid api calls
Call with invalid endpoint
=> list valid endpoints for invalid api calls

package-lock.json, package.json, packages/github-lens-api/package.json, packages/services-api/package.json
Presumably this was used pre-esbuild. But it is no longer required.
=> Remove rollup

packages/cloudformation-lens/account/account.go
Includes the build tool if found. See also:
* https://github.com/guardian/riff-raff/pull/937
* https://github.com/guardian/actions-riff-raff/pull/23
To understand usage of `guardian/actions-riff-raff` and other build tools.
=> Report build tool

README.md
Readme instructions are no longer incorrect
=> use correct script name

.github/workflows/ci.yml, packages/cdk/bin/cdk.ts, packages/cdk/lib/repocop.ts, packages/repocop/src/main/scala/main.scala
Start to use cdk, implements scheduled lambda that uses starter application
Repocop did not yet use cdk
=> Adds CDK described infra for repocop

package-lock.json, package.json, packages/common/package.json, packages/github-data-fetcher/package.json, packages/github-lens-api/package.json, packages/services-api/package.json
Batches Dependabot PRs.
Closes:
https://github.com/guardian/service-catalogue/pull/107
https://github.com/guardian/service-catalogue/pull/106
https://github.com/guardian/service-catalogue/pull/105
https://github.com/guardian/service-catalogue/pull/104
https://github.com/guardian/service-catalogue/pull/103
=> Batch Dependabot PRs

packages/repocop/src/main/scala/GHLensAPI.scala
=> chore: Remove invalid `;`

packages/common/src/aws/s3.ts, packages/github-lens-api/src/controller/describe.ts, packages/github-lens-api/src/controller/members.ts, packages/github-lens-api/src/controller/repos.ts, packages/github-lens-api/src/controller/teams.ts
Make the github lens api endpoints more consistent
To make user experience less confusing
=> Consistent api endpoint output for github lens api

.github/pull_request_template.md
Adds a test section to the PR template
It's not always clear from the code, and is extra helpful in multilingual repos where not everybody is familiar with all the test frameworks
=> Ask developers to explain how changes were tested

ADR/repocop-and-vulnerability-api-arch.md
Moves the ADR from somewhere in the filesystem to sit alongside the actual code
Findability, better visibility of changes
=> Add repocop/vulnerability api adr

package-lock.json, packages/github-lens-api/package.json, packages/github-lens-api/src/app.ts
Log details of each request that reaches the server to improve ability to debug issues.
We're using ExpressJS's [morgan module](https://github.com/expressjs/morgan), and [morgan-json](https://www.npmjs.com/package/morgan-json) to create JSON log lines that can be processed by Fluentbit, Logstash, and Elasticsearch.
- [Deployed](https://riffraff.gutools.co.uk/deployment/view/50407075-0a62-462d-b104-9f315b3665b7)
- Witnessed logs appear in Central ELK (see below)
=> feat(github-lens-api): Add request logging

packages/cloudquery/prod-config/cloudquery.sh
Issue an RDS auth token before each `cloudquery sync`.
In #159 we moved to using IAM authentication to connect to the database. This works by issuing a token that's [valid for 15 minutes](https://repost.aws/knowledge-center/rds-postgresql-connect-using-iam). Attempts to reconnect with this token after 15 minutes fail.
Each `cloudquery sync` establishes a new connection. This means if the first `cloudquery sync` takes over 15 minutes to complete, the second sync will fail to connect to RDS as the generated token would have expired.
By issuing a token before each sync, we can be sure the connection to RDS will be successful.
=> fix(cloudquery): Ensure each `sync` can authenticate with RDS

packages/cloudquery/.env.example, packages/cloudquery/dev-config/cloudquery.yaml, packages/cloudquery/docker-compose.yaml, packages/cloudquery/script/setup
This PR builds on #199.
Adds the [Snyk source](https://www.cloudquery.io/docs/plugins/sources/snyk/overview) to CloudQuery in DEV.
This will help us answer some of this quarter's key questions, at least locally:
- (Vulnerability monitoring) Does a service have vulnerability monitoring?
- (Vulnerability monitoring)  Does a service have outstanding high or critical vulnerabilities?
Follow the instructions to run CloudQuery locally, and observe data in Grafana.
=> feat(cloudquery): Collect Snyk data in DEV

package-lock.json, packages/cdk/package.json
Updates the version of GuCDK being used.
=> chore(deps): Bump version of GuCDK

.env, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/config.test.ts
Updates the version of the CloudQuery CLI and plugins.
Just staying up to date.
Tested locally.
=> chore(deps): Update CloudQuery CLI and plugins

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/config.test.ts
Update cloudquery to the latest versions
All github jobs have been failing
We can use our code environment to run one job
=> bump versions in .env file

.github/workflows/ci.yml, package-lock.json, package.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts, packages/cdk/package.json, packages/repocop/.gitignore, packages/repocop/README.md, packages/repocop/index.ts, packages/repocop/package.json, packages/repocop/prisma/schema.prisma, packages/repocop/run-locally.ts, packages/repocop/tsconfig.json, scripts/ci.sh, sql/dbuser.sql
Add prisma and generate schema in schema.prisma, make a query in table… repository with the prisma client
We had to create the db user repocop manually (dbuser.sql)
First step to use prisma with cloudquery
Deploy to code and run lambda
[riffraff deploy](https://riffraff.gutools.co.uk/deployment/view/1c43e970-6119-4187-a940-a6c253324dac)
=> Add prisma

packages/repocop/prisma/migrations/0_init/migration.sql
Add directory prisma/migration and a file with the initial data layout
The migration process is manual for now.
We want to be able to use prisma migrations to make changes to the database and need to set is up according to the
[prisma doc](https://www.prisma.io/docs/concepts/components/prisma-migrate/db-push#choosing-db-push-or-prisma-migrate)
We applied the migration first locally and to code and it worked
```
npx prisma migrate resolve --applied 0_init
```
=> Configure intial db migration

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/run-locally.ts
It is sometimes helpful to understand the underlying SQL being executed. Read the `QUERY_LOGGING` environment variable to log the SQL queries being executed.
Following https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging, we can have Prisma log SQL to stdout, interleaved with other `console.log`s.
By default, it's enabled in DEV and disabled otherwise.
<details>
<summary>Example</summary>
```console
➜ npm -w repocop start
> repocop@1.0.0 start
> ts-node src/run-locally.ts
prisma:query SELECT "public"."github_repositories"."org", "public"."github_repositories"."id", "public"."github_repositories"."_cq_sync_time", "public"."github_repositories"."_cq_source_name", "public"."github_repositories"."_cq_id", …
```
=> feat(repocop): Add configuration to log SQL queries

README.md
Updates the root README to include information about Repocop.
=> Update main README to include repocop

package-lock.json, packages/branch-protector/README.md, packages/branch-protector/package.json, packages/branch-protector/src/config.ts, packages/branch-protector/src/index.ts, packages/branch-protector/src/model.ts, packages/branch-protector/src/run-locally.ts, packages/branch-protector/tsconfig.json
Initial proof of concept for a branch protection tool.
A local project that, given a repo:
- Checks its branch protections
- If none are detected, applies basic protections
- Notifies DevX of the change
This is a skeleton project in order to keep PRs small. Subsequent PRs will
- Move the project to AWS Lambda, and authenticate via GitHub app
- Use an updated version of Anghammarad that allows us to send messages based on github teams.
In order to keep PRs a more manageable size, we'll be applying PRs step-by-step rather than one big one at the end
To help us resolve violations of departmental standards, specifically, REPOSITORY_O2 of [this document](https://github.com/guardian/recommendations/blob/main/best-practices.md)
Running the code `ts-node src/run-locally.ts` produces expected …
=> Set up local branch protection tool

packages/branch-protector/src/index.ts
Prevents non-prod environments from making changes to repos.
1. We don't want a lambda intended for testing to send real messages to teams or make real changes to repos
2. The github app for CODE shouldn't have permission to make changes to repos, but having this control adds an extra layer of safety
3. If the code github app doesn't have permission to make changes to repos, it's pretty likely `updateBranchProtection` will throw an error, so we should try to avoid calling it entirely.
TODO: add a message to the queue and invoke the lambda on CODE or DEV
=> make branch protector stage aware

packages/cdk/lib/service-catalogue.ts
Adds some potential use cases for the data being collected, to help us identify if a table needs to be collected separately and also at what cadence.
=> docs: Describe possible use cases for our data

jest.config.js, package-lock.json, packages/branch-protector/src/aws-requests.ts, packages/common/package.json, packages/common/src/functions.test.ts, packages/common/src/functions.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts
Creates and tests functions for duplicated anghammarad logic
Adherence to the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle, and more reliable code with better test coverage
Tests pass
=> create common functions for duplicated repocop logic

scripts/ci.sh
Not all CI steps are dependent on the previous one. Run them concurrently to save time/increase resource efficiency
Speed things up a bit
A successful CI run on GH now takes about two minutes rather than four
=> CI concurrency

packages/interactive-monitor/src/config.ts, packages/interactive-monitor/src/index.ts
Applies topic to repo if required.
Catches interatcives automatically
1. Submitted an unlabelled interactive to SNS
2. Check logs look good
3. Verify label has been applied on GitHub
4. Repeat on CODE to make sure topics are not applied for non-prod environments
=> apply interactive topic if necessary

packages/interactive-monitor/src/index.ts
Reduce the amount we log.
Logs have so much detail they are often unhelpful. This makes them easier to sift through without losing much meaning
=> simplify logging

packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/github-requests.ts, packages/branch-protector/src/index.ts
Remove redundant log lines, simplify the language used, and combine some logs into one message
Clarity & brevity
=> simplify logs

packages/repocop/src/remediations/repository-06-topic-monitor-production.test.ts, packages/repocop/src/remediations/repository-06-topic-monitor-production.ts, packages/repocop/src/rules/repository.test.ts
Adds some tests for the topic monitor for production topics.
=> Add tests for topic monitor (production tags)

packages/common/src/database.ts
Making `password` required in the `DatabaseConfig` interface allows us to remove an "if undefined" check.
Simpler logic.
N/A.
=> refactor: Use the type system to simplify the code

packages/interactive-monitor/src/index.ts, packages/repocop/src/remediations/repository-06-topic-monitor-production.ts
Reduce the logs produced by the production monitor.
We are no longer testing this feature, so logs don't need to be as verbose
=> chore(repocop): less logging

.github/workflows/ci.yml, packages/cli/src/database.ts, packages/common/prisma/schema.prisma, scripts/ci.sh
Check, in CI, that the `schema.prisma` file lines up with the database schema as defined by the migrations.
The `schema.prisma` file is used to generate the prisma client, which is then used in our TypeScript applications to interact with the database. If the `schema.prisma` file does not line up with the database schema, then the queries might could be invalid, and will only be known at runtime.
TBD.
=> ci: Check Prisma schema file matches migrations

package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/ecs/config.ts, packages/cdk/lib/data-audit.ts, packages/common/prisma/schema.prisma, packages/common/src/aws.ts, packages/data-audit/README.md, packages/data-audit/package.json, packages/data-audit/src/audit/aws-lambda.ts, packages/data-audit/src/index.ts
Add an audit for AWS Lambda functions. This is the first multi-region audit 🎉.
[See the original ADR](https://github.com/guardian/service-catalogue/blob/main/ADR/03-data-accuracy.md).
Ran locally, and on CODE.
=> feat(data-audit): Audit AWS Lambda functions

scripts/setup.sh
Removes reference to the Snyk token in the log line as this is now added automatically.
=> chore: update log line in setup script to make clearer

package-lock.json, packages/repocop/package.json
Removes an unused dependency
We are no longer using it
CI passes
=> remove sqs dependency

package-lock.json, packages/repocop/package.json, packages/repocop/src/remediations/snyk-integrator/snyk-integrator.test.ts, packages/repocop/src/remediations/snyk-integrator/snyk-integrator.ts
Autogenerate a markdown-formatted Snyk integration PR. The wording of the PR body has been approved by the Security team.
Provide consistent messaging to teams about why we are raising this PR, with some customisable elements.
New unit tests have been added to validate the expected behaviour
=> Generate Snyk PR title and body in markdown

packages/snyk-integrator/README.md, packages/snyk-integrator/src/snyk-integrator/snyk-integrator.ts
Documents what the purpose of snyk-integrator is, and how to use it.
Documentation is good!
Markdown is correctly formatted, all the links work.
You can see a nicely rendered version [here](https://github.com/guardian/service-catalogue/blob/eb523a5d3ad2049a96cf3a475fec430ba532642d/packages/snyk-integrator/README.md)
=> Create snyk-integrator README

packages/dev-environment/docker-compose.yaml
Update to match the version of Grafana we're running in PROD.
=> chore(deps-dev): Update Grafana version

packages/snyk-integrator/src/snyk-integrator.ts
yml->yaml
This is the officially supported extension
CI passes
=> Use official YAML extension

packages/common/prisma/migrations/20240409101800_function_aws_resource/migration.sql
Missed some things in https://github.com/guardian/service-catalogue/pull/917
=> Fix bugs in aws_resource function

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Delete an unused function
Removing bloat
CI passes
=> remove unused function getTopVulns

README.md
This adds a link to the service catalogue runbook to the README. It contains very useful information like how to run tasks manually.
=> Mention runbook

packages/repocop/src/index.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.ts
Sends a configurable number of repos to the dependency graph integrator
So we can control the pace of integration.
=> send a configurable number of repos to the dependency graph integrator

packages/repocop/src/index.ts, packages/repocop/src/remediation/branch-protector/branch-protection.ts, packages/repocop/src/remediation/snyk-integrator/send-to-sns.ts
Cleans up the index by evaluating flags inside the relevant functions
Too many nested ifs are a bit of a nightmare to read.
=> Simplify Flags

packages/dependency-graph-integrator/src/file-generator.ts, packages/dependency-graph-integrator/src/pull-requests.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.test.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.ts
Makes a few small health tweaks.
This addresses a comment made in PR #1334, and a couple of other issues that have been identified.
=> Refactor: make a couple of tweaks to repocop dep graph integrator'

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Updates https://github.com/guardian/cq-source-ns1 to the latest version.
=> chore(deps): Update cq-source-ns1 from 0.1.2 to 0.1.3

packages/cdk/bin/cdk.ts, packages/cdk/lib/service-catalogue.test.ts, packages/cdk/lib/service-catalogue.ts
Adding the `database` prefix to props that impact the database is more intention revealing. See also https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md#flat.
This is a no-op, confirmed by the snapshots being left untouched.
=> refactor: Namespace database props

docs/database-migrations.md, packages/dev-environment/README.md
During the work to develop https://github.com/guardian/service-catalogue/pull/1525, @akash1810 and I found a few snags we though would be useful to document.
To help future generations contribute to the service catalogue.
=> Updates the docs with useful migration findings
