package-lock.json, package.json, packages/common/github/github.ts, packages/repo-fetcher/package.json, packages/repo-fetcher/src/handler.ts, packages/repo-fetcher/src/mockRepo.ts, packages/repo-fetcher/src/transformations.test.ts, packages/repo-fetcher/src/transformations.ts
Apart from linting, this change introduces a a way to include repository team owners as part of the Repo object 
`npm run test -w packages/repo-fetcher`
Verify that all tests pass
We have skirted round any potential API limits but requesting owners per team, rather than by repo. There are ~100 teams and ~3000 repos at time of writing, so even paginated, this is a 30x reduction in pages requested.
=> Add teams that own repos to Repo object

jest.config.js
This change adds `common` to the list of packages that need to be tested by jest (currently some tests in that folder are being missed).
Ensure tests in `common` package are being run by GHA: [They do!](https://github.com/guardian/github-lens/actions/runs/3097544067/jobs/5014340517#step:5:61)
=> Setup jest in order that tests in common package run

jest.config.js, package-lock.json, packages/teams-fetcher/package.json
It looks like this project has evolved into [repo-fetcher](https://github.com/guardian/github-lens/tree/main/packages/repo-fetcher). Remove it to avoid confusion.
N/A
=> chore: Remove empty teams-fetcher project

packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/lib/github-lens.ts, packages/common/aws/s3.ts, packages/common/config.ts, packages/repo-fetcher/src/handler.ts
This change is intended to improve the DX of this repository by allowing the lambda running locally to use the INFRA stack S3 bucket with the "DEV" prefix. It makes specifying a bucket name mandatory and expects this to be made available in a local `.env` file as follows:
```
DATA_BUCKET_NAME=github-lens-data-INFRA
```
There is only an INFRA stack for this application and the value of `DATA_BUCKET_NAME` should be that in the currently created stack.
Note: When this is deployed and a stack is created next we'll need to update the .env file in S3 to reference the S3 bucket created in the INFRA stack.
=> Use configured bucket from environment locally

README.md
Tiny docs update to reflect that team fetcher doesn't exist.
=> Remove reference to Team Fetcher as it doesn't exist!

packages/common/config.ts, packages/common/github/github.ts, packages/repo-fetcher/src/config.ts, packages/repo-fetcher/src/handler.ts
The config in the common package currently is specific to `repo-fetcher`, as we will want to configure the `github-lens` workspace separately move the not-common config out of `common`.
Tests pass, repo-fetcher continues to work as expected.
=> Config in common package is specific to repo-fetcher

scripts/recrypt.sh, scripts/setup.sh
This change adds a script to update an SSM parameter that has been encrypted with a KMS key to an updated value encrypted with a different key. 
You may want to do this if your KMS key has been re-created by a CloudFormation stack update.
Though it is very rare we'll perform this task it is highly error prone and non-obvious how strings should be encoded to be accepted, this script hopefully prevents the need to reproduce the effort again.
=> Add script to re-encrypt SSM param if required

packages/common/src/aws/s3.test.ts, packages/common/src/aws/s3.ts
Removes the need to deal with byte arrays using [sdkStreamMixin](https://github.com/aws/aws-sdk-js-v3/issues/1877#issuecomment-1287275227).
This makes our code a bit simpler and easier to understand. It also [fixes an error in `main`](https://github.com/guardian/github-lens/actions/runs/3360557582/jobs/5569904031#step:5:39).
=> Simplify reading from S3 by using transformToString

packages/common/src/config.ts, packages/common/src/github/github.ts, packages/repo-fetcher/src/config.ts, packages/repo-fetcher/src/handler.ts
This project heavily relies on the GitHub API. This API is rate limited.
In an attempt to improve the local DX, in this change we add a new configuration property `GITHUB_TEAM`. When set, we reduce the amount of API calls made to hopefully yield a faster feedback loop when developing locally.
- Checkout branch
- Set `GITHUB_TEAM` env var
- Run repo-fetcher
=> feat: Allow collection of data for one GH team

jest.config.js, package-lock.json, package.json, packages/common/src/aws/s3.ts, packages/common/src/github/github.ts, packages/github-lens-api/package.json, packages/github-lens-api/src/app.test.ts, packages/github-lens-api/src/app.ts, packages/github-lens-api/src/config.ts, packages/github-lens-api/src/handler.ts, packages/repo-fetcher/src/handler.ts, packages/repo-fetcher/src/transformations.test.ts, packages/repo-fetcher/src/transformations.ts
This change returns the contents of the `repos.json` stored by repo-fetcher on the `/repos` endpoint in the `github-lens-api` endpoint. This allows the repo data to be read from the API!
Tests pass, after infra deployed the `/repos` endpoint will return data.
=> Output contents of repos.json on /repos

packages/common/src/aws/s3.test.ts, packages/common/src/aws/s3.ts, packages/github-lens-api/src/app.test.ts, packages/github-lens-api/src/app.ts, packages/github-lens-api/src/handler.ts
This change adds a `lastModified` field to the object returned from S3 using the `RetrievedObject` interface.
The last modified date is determined from the S3 metadata for a retrieved object.
The intention is to improve the usefulness of the data returned from the API i.e.f if the data in S3 hasn't been refreshed it's useful to know that!
The API response looks like this:
**Note:** In a future PR we may want to introduce a separate response type and parse the `RetrievedObject` into that type. 
`npm run test`
=> Add last-modified date to the data retrieved from S3

packages/github-lens-api/src/app.ts, packages/github-lens-api/src/expressRoutes.ts
This change adds a special request handler that can parse the Express routing stack and report a list of endpoints with their methods.
Requesting `/` will return the following:
```json
[
{
"path": "/",
"methods": [
"get"
]
},
{
"path": "/healthcheck",
"methods": [
"get"
]
},
{
"path": "/repos",
"methods": [
"get"
]
}
]
```
This is intended to make it easier for developers or folk working with the API to discover and browse endpoints in this service.
=> Add router describing request handler

packages/github-lens-api/src/expressRoutes.ts
Add full url to be able to click on the link in the api description (e. g. http://localhost:3232/healthcheck)
=> full url to be able to click on link in api description

package-lock.json, packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/lib/github-lens.ts, packages/github-lens-api/package.json, packages/github-lens-api/src/handler.ts
**Update: test with https://github-lens.gutools.co.uk/healthcheck !**
Security Groups (network restrictions) are used to limit API access to within the VPC and peered Guardian networks - specifically the VPN.
API Gateway can be used to achieve this too but it is difficult to use a custom domain when doing so. See e.g.
https://georgemao.medium.com/enabling-private-apis-with-custom-domain-names-aws-api-gateway-df1b62b0ba7c
which requires an ALB for this.
If, as it seems, an ALB is required anyway, then using API Gateway seems to only add complexity here.
The shift to EC2 is not strictly speaking required but provides the following:
* consistency with Cloudformation Lens (nee cdk-metadata)
* ability to use our CDK GuEc2App pattern (without this, the CDK is even more custom/verbose)
* a …
=> Make API private by moving to ALB/EC2

packages/common/src/expressRoutes.ts, packages/github-lens-api/src/app.ts
`getDescribeRouterHandler` is used to list available routes when a user provides a path that is not found. This change returns the correct status code for not found routes (404).
=> Return 404 when path not found

.github/workflows/snyk.yml, package-lock.json, package.json, packages/github-lens-api/package.json, packages/repo-fetcher/package.json, packages/services-api/package.json
Currently scanning for node vulnerabilities is disabled, this project contains TS so it should be enabled (plus it's breaking the Snyk integration in main now).
To make Snyk run without getting upset I also needed to add `esbuild` as a dev dependency of the root project (and bump the version to 15).
=> We should NOT skip node in the Snyk workflow

package-lock.json, package.json, packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/lib/__snapshots__/services-api.test.ts.snap, packages/github-lens-api/package.json, packages/repo-fetcher/package.json, packages/services-api/package.json, scripts/ci.sh
Pushes the following dependencies to the root package.json:
- `@guardian/eslint-config-typescript`
- `@guardian/prettier`
- `typescript`
- `jest`
- `ts-jest`
- `@types/jest`
- `esbuild`
These dependencies are used in all (/the majority of workspaces). By installing them once, we achieve a simpler dependency updating story as bumping happens in one place.
These dependencies are also updated to the latest available version.
Also:
- Removes `tslib` as unused
- Removes `ts-node-dev` in favour of `ts-node`
- Makes the CI script less verbose
To tell a simpler dependency story.
=> chore(deps): Simplify some dependencies by moving them to the root

package-lock.json, packages/github-lens-api/package.json
Removes an unused dependency.
The dependency `aws-sdk@2.932.0` is unused and can be removed.
The github-lens-api project doesn't used aws-sdk directly, it uses it via common, and [common uses aws-sdk@v3](https://github.com/guardian/github-lens/blob/e5358953a7c05b018b19de1cb5ef0bb6036c6b19/packages/common/package.json#L8-L9).
=> chore(deps): Remove unused aws-sdk@v2 dependency

packages/common/src/github/github.ts, packages/common/src/model/repository.ts, packages/github-lens-api/src/app.test.ts, packages/github-lens-api/src/app.ts, packages/github-lens-api/src/handler.ts, packages/repo-fetcher/src/handler.ts, packages/repo-fetcher/src/transformations.ts
This change stores a list of teams in S3 along with the repositories they own so this data can be made available in the github-lens API.  It also adds `/teams` and `/teams/:name` endpoints.
More complete view on GitHub, and this data can then be used by `services.gutools` to identify which P&E teams own which repositories.
=> Add teams data

.github/workflows/ci.yml, packages/cdk/lib/__snapshots__/cloudformation-lens.test.ts.snap, packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/lib/__snapshots__/services-api.test.ts.snap
Changes the app name to "service catalogue" so that riff-raff will call the project by its new name when deploying services. 
This should have no impact on the deployed services.
To reduce confusion when the project has a different name than that deployed under.
=> Updates the app name to "service catalogue"

.github/workflows/ci.yml
This change https://github.com/guardian/service-catalogue/pull/64 doesn't really update the name riff-raff uses, we need to 
To _really_ reduce confusion when the project has a different name than that deployed under.
=> Updates the project name to "service catalogue"

packages/github-lens-api/src/app.ts
Add an optional search after endpoint repos
search by name with ?name=searchString
Thanks to Kenny for pointing out that this actually did not make it into main at all.
=> Search for repo by names reinstated

.github/workflows/snyk.yml, package-lock.json
Snyk monitoring [has broken](https://github.com/guardian/service-catalogue/actions/runs/3547547273/jobs/5957785700#step:13:16), we need to update `package-lock.json`.
This change also excludes only the npm workspaces already covered by monitoring the root `package.json`. This allows us to cover`cloudformation-lens` which is written in go!
So we can continue to monitor and remediate vulnerabilities.
=> Fix snyk monitoring, don't exclude packages

packages/common/src/github/github.ts, packages/common/src/model/github.ts, packages/github-data-fetcher/src/handler.ts, packages/github-data-fetcher/src/transformations.ts, packages/github-lens-api/src/app.test.ts, packages/github-lens-api/src/app.ts, packages/github-lens-api/src/data.ts, packages/github-lens-api/src/handler.ts
This change retrieves organisation members from the GitHub API and makes that data available via the github-lens API.
Organisation membership data is useful when associating staff members with their GitHub accounts and team membership in the services API (and potentially for auditing purposes / reproducing some of the functionality of gu-who).
=> Add organisation members to github-lens API

packages/github-lens-api/src/app.ts
A previous PR updated to use the term "slug" (being more accurate than "name"), but broke the `teams/:slug` endpoint by failing to rename which request parameter it read from.
Fix the `teams/:slug` endpoint.
=> Fix for broken renaming of name -> slug

packages/github-lens-api/src/app.ts, packages/github-lens-api/src/controller/DescribeApiController.ts, packages/github-lens-api/src/controller/HealthCheckController.ts, packages/github-lens-api/src/controller/MembersController.ts, packages/github-lens-api/src/controller/ReposController.ts, packages/github-lens-api/src/controller/TeamsController.ts
Refactor to separate logic out of app.ts into controllers
Keeping the routes separate for the implementation and the implementation in logical groups makes the code easier to understand und is good practice
Maybe the calls to get the data could be moved too, but I ran into problems there and feel this refactor already adds worthwhile clarity.
=> Refactor to make routes in app.ts easier to grasp

package-lock.json, package.json, packages/common/src/expressRoutes.ts, packages/common/src/github/github.ts, packages/github-data-fetcher/src/handler.ts, packages/github-data-fetcher/src/transformations.ts, packages/github-lens-api/src/app.test.ts, packages/github-lens-api/src/app.ts, packages/github-lens-api/src/controller/DescribeApiController.ts, packages/github-lens-api/src/controller/HealthCheckController.ts, packages/github-lens-api/src/controller/MembersController.ts, packages/github-lens-api/src/controller/ReposController.ts, packages/github-lens-api/src/controller/TeamsController.ts, packages/github-lens-api/src/data.ts, packages/github-lens-api/src/handler.ts, packages/services-api/src/app.ts
Since @guardian/eslint-config v2.0.0 we have to run Prettier ourselves.
In this change, we configure ESlint to run Prettier.
See:
- https://github.com/guardian/csnx/releases/tag/%40guardian%2Feslint-config%402.0.0
- https://github.com/prettier/eslint-plugin-prettier
Prettier is an opinionated formatter... so we don't have to be! It produces a consistent code style.
It takes care of decisions on quite mark style (`"` or `'`), tabs vs spaces, trailing commas on objects, etc.
=> chore(prettier): Configure Prettier

.idea/jsLinters/eslint.xml, .idea/prettier.xml, .vscode/extensions.json, .vscode/settings.json
Follows https://github.com/guardian/service-catalogue/pull/83.
We run ESLint in CI. In an effort to reduce the chance of a build failing for violating ESLint rules, add some IDE configuration files to format files on save.
Config added for VS Code and IntelliJ.
An attempt to reduce friction and improve local DX.
- Checkout the branch
- Open the repository in IntelliJ
- Add `const message = "hello"` to a file
- Save and witness it being rewritten to `const message = 'hello';` (single quotes, trailing semicolon)
- Repeat for VS Code
=> chore: Add IDE configuration to format files on save

packages/common/src/github/github.ts, packages/common/src/model/github.ts, packages/github-data-fetcher/src/handler.ts, packages/github-data-fetcher/src/transformations.test.ts, packages/github-data-fetcher/src/transformations.ts
The `language` property of a repository is a single item - the primary language used. In this change, we store the entire set of languages used (ordered by frequency).
```json
[
{
"id": 13386075,
"name": "prism",
"full_name": "guardian/prism",
"private": false,
"description": "Tool for collecting live data about infrastructure so it can be easily queried by users and automated tooling",
"created_at": "2013-10-07T14:32:02.000Z",
"updated_at": "2022-06-10T10:45:05.000Z",
"pushed_at": "2022-11-28T13:04:52.000Z",
"size": 2495,
"languages": [
"Scala",
"Ruby",
"TypeScript",
"HTML",
"JavaScript",
"Shell"
],
"archived": false,
"open_issues_count": 5,
"is_template": false,
"topics": [
"production"
],
"default_branch": "main",
"owners": [
"devx-operations"
]
}
]
```
Knowing all the languages allows …
=> feat(data-fetcher): Store the languages of a repository

package-lock.json, packages/cdk/lib/__snapshots__/cloudformation-lens.test.ts.snap, packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/lib/__snapshots__/services-api.test.ts.snap, packages/cdk/package.json, packages/common/package.json, packages/github-data-fetcher/package.json, packages/github-lens-api/package.json, packages/services-api/package.json, packages/services-api/src/services.ts
Batches dependabot PRs:
Closes https://github.com/guardian/service-catalogue/pull/82
Closes https://github.com/guardian/service-catalogue/pull/81
Closes https://github.com/guardian/service-catalogue/pull/80
Closes https://github.com/guardian/service-catalogue/pull/79
Closes https://github.com/guardian/service-catalogue/pull/78
Closes https://github.com/guardian/service-catalogue/pull/75
**Note:** This change replaces `node-fetch` with `axios` as a more suitable http client that is less likely to cause type / test issues in the future.
Less fiddling with merging / rebasing PRs.
=> Batch Dependabot PRs

package-lock.json, package.json, packages/cdk/bin/cdk.ts, packages/cdk/lib/cloudformation-lens.ts, packages/cdk/lib/github-lens.ts, packages/cdk/lib/services-api.ts, packages/cdk/package.json, packages/common/src/aws/kms.test.ts, packages/common/src/aws/kms.ts, packages/common/src/aws/s3.test.ts, packages/common/src/github/github.ts, packages/github-data-fetcher/src/handler.ts, packages/github-lens-api/src/controller/repos.ts, packages/services-api/src/app.ts, packages/services-api/src/galaxies.ts, tsconfig.json
Use [@guardian/tsconfig](https://github.com/guardian/csnx/tree/main/libs/%40guardian/tsconfig) to reduce the amount of configuration.
This config has highlighted some code paths not returning expected values. These are also fixed.
- Less config
- An easier path to ESM... I think!
- Makes it easier to use packages that are now published as ESM only (e.g. [node-fetch](https://github.com/guardian/service-catalogue/pull/87#discussion_r1036853767))
=> chore: Use departmental tsconfig

packages/cdk/bin/cdk.ts, packages/cdk/lib/cloudformation-lens.ts, packages/cdk/lib/github-lens.ts, packages/cdk/lib/repocop.ts, packages/cdk/lib/services-api.ts, packages/cdk/package.json, tsconfig.json
Change tsconfig to be able to run locally without errors, revert currently unneeded js extentions
Co-authored-by: Akash <akash1810@users.noreply.github.com>
https://github.com/guardian/service-catalogue/pull/89
did introduce the problem that running locally did not work
=> Revert esm changes

packages/cdk/lib/__snapshots__/repocop.test.ts.snap, packages/cdk/lib/repocop.test.ts
Follows https://github.com/guardian/service-catalogue/pull/97, to add test coverage for Repocop CDK stack.
So we notice and test infra changes in repocop.
=> Add Repocop CDK test

.github/dependabot.yml
Target the existing `dependency-updates` branch that Scala Steward is adding updates to.
Simplify the process of merging regular dependency updates
=> Target the dependency-updates branch for Dependabot PRs

packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/lib/github-lens.ts
Before, the data fetcher and repocop both ran at 8am
Now, the data fetcher runs at 7.
Repocop is less likely to be using stale data, if datafetcher hasn't finished in time
=> Data Fetcher should run before Repocop

packages/github-lens-api/src/app.ts, packages/github-lens-api/src/controller/describe.ts, packages/github-lens-api/src/controller/repos.ts, packages/github-lens-api/src/controller/teams.ts, packages/github-lens-api/src/filters.ts
Updates the way filters work so they can be applied across multiple endpoints. This change allows filtering of repository data on the following endpoints:
- `/teams/:slug`
- `/teams`
It renames the filter parameters to refer to specifically the type of data they are filtering on the API responses, i.e.
- `name` -> `repoName`
- `isArchived` -> `repoIsArchived`
It also adds the following filter that can be applied across the existing endpoints;
- `repoIsNotArchived`: Display only repositories not archived.
- `repoNotOwned`: Display only repositories with no owners.
Generalises the use of filters in a (hopefully) sensible way, and provides utility to other services wanting to consume this data.
=> Update filters to work more generally on API endpoints

package-lock.json, package.json
Updates the `name` field to reflect the name of the repository, also regens `package-lock.json` to get Snyk to pass.
Snyk is currently failing on `main`. When manually run on this branch, it passes https://github.com/guardian/service-catalogue/actions/runs/3685617735/jobs/6236803535. Not sure why, but I don't understand Snyk well enough (yet!).
=> chore: Correct `name` in root `package.json`

packages/common/src/github/github.ts
Convert the repo language log line to `debug`, to reduce volume of logs seen in production (as we don't log at debug level in production).
Less noise makes it easier to find things.
=> chore: Quieten production logs

packages/common/src/config.ts
- `DEV` when running locally
- [`INFRA` when running in AWS](https://github.com/guardian/service-catalogue/blob/main/packages/cdk/bin/cdk.ts)
Because it's correct...
=> fix: Correct valid values of `Stage`

package-lock.json, package.json, packages/common/src/config.ts, packages/github-data-fetcher/package.json, packages/github-lens-api/package.json, packages/services-api/package.json
We achieve configuration via environment variables (env vars).
Locally, we use the [`dotenv`](https://github.com/motdotla/dotenv) package to read env vars from disk (the `.env` file). In production, we set env vars via IaC.
This change:
- Removes `dotenv` as an individual dependency from each project, favouring 1 version at the root
- [Preloads](https://github.com/motdotla/dotenv#preload) `.env` via `DOTENV_CONFIG_PATH`, to remove any imports from `dotenv` in production code
- Moves `dotenv` to `devDependencies` in the root `package.json`. This makes dependency management much easier too!
Simplifies the repository.
=> chore(deps): `dotenv` is a dev dependency

packages/github-lens-api/src/controller/describe.ts, packages/github-lens-api/src/filters.ts
Allow some of the existing parameters to take a boolean value, so we can have fewer parameters and they are used in a less surprising way. The implementation naively looks for the addition of `=false` to the param, and uses only positive language so that the original param without the addition of boolean also works.
e.g.
- `/repos?repoIsArchived=false`: returns all repos where archived is false
- `/repos?repoIsArchived=true`: returns all repos where archived is true
- `/repos?repoIsArchived`: returns all repos where archived is true
- `/repos?repoIsArchived=purplehippos`: _also_ returns all repos where archived is true
Although this is _a bit weird_ I think it is good enough for our purposes.
Slightly less surprised developers! 😮
=> Make filter params accept boolean values

scripts/pre-commit, scripts/setup.sh
extracts pre hook commit to its own file
easier to read, easier to test
deleted the hook from .git, reran the setup script, verified that the hook still works.
=> simplify hook setup

packages/common/src/github/github.ts, packages/common/src/model/github.ts, packages/github-data-fetcher/src/handler.ts, packages/github-data-fetcher/src/transformations.ts
Add last commit to repos endpoint
Adds info about last commit to repos api endpoint (if there are any)
It now works for all repos
For Repocop: Natasha: When we run snyk we send the commit hash with it to tag the project. If we can see that the hash snyk has matches the one github has at the head of the default branch (which is only mostly called main, it could be called something else), then we know that it's up to date
Paired with Nic added sha and cleaned up code
Turned out my problems were rate limit related outside of scope of this PR.
There are repos without commits.
Paired with Akash to fix issue with repos with master branch
Repository test-interactive-repo has no commits
Repository interactive-rooney-england-goals has no commits
Repository newgreekdebt2 has no commits
Repository …
=> Add last commit to repos endpoint

packages/github-lens-api/src/controller/describe.ts, packages/github-lens-api/src/filters.ts
Automatically add the available filters to the index page. This makes it easier to keep the two in-sync, at the cost of removing the `type` description. However, the type could/should be implied by the name (e.g. `isX` is a boolean).
```json
[
{
"path": "http://localhost:3232/healthcheck",
"methods": [
"get"
],
"info": "Display healthcheck"
},
{
"path": "http://localhost:3232/repos",
"methods": [
"get"
],
"info": "Show all repos, with their team owners, optionally filter repositories ?repoName=^repo-name-regex.*, ?repoIsArchived=true|false, ?repoIsOwned=true|false"
},
{
"path": "http://localhost:3232/repos/:name",
"methods": [
"get"
],
"info": "Show repo and its team owners, if it exists"
},
{
"path": "http://localhost:3232/teams",
"methods": [
"get"
],
"info": "Show all teams, with the …
```
=> refactor: Automatically add filters to route info

packages/common/src/github/github.ts, packages/github-data-fetcher/src/handler.ts, packages/github-data-fetcher/src/repoMatching.test.ts, packages/github-data-fetcher/src/repoMatching.ts
Affected GitHub requests, assuming ~3000 repos
Previously, we were making multiple requests for every repository to gather all the metadata fresh. Now, we run the initial requests to get the basic metadata, and only make further requests for information if we detect that the repo has been updated.
With a several day gap between successful runs, the calls to the language and commit endpoints have been reduced from about 3200 each to about 80 each, a reduction of about 98% 🥳🥳🥳. **n.b no changes have been made do how we interact with other endpoints. I'd guesstimate that it would be closer to 90% once all unchanged requests have been factored in**
The data fetcher has been failing for the last few days as recent changes mean we are now exceeding the rate limit. This had not been detected …
=> Reduce requests made to github

.github/workflows/ci.yml
Co-authored-by: @tjsilver 
The default timeout for a GHA is 360 minutes (6 hours). Normally this step completes in about 5 minutes, so we've lowered the timeout
6 hours seemed like too many.
I think this could be rolled out to other actions too.
Initially the timeout was set to 1 minute, which failed as there was not enough time for the process complete. It was then set to 10 minutes, and passed.
=> Sets a timeout for the CI action

packages/cdk/lib/cloudformation-lens.ts
Use the AMIgo recipe `arm64-focal-java11-deploy-infrastructure` for the cloudformation-lens service.
The [previous recipe](https://amigo.gutools.co.uk/recipes/arm64-focal-java11-deploy-infrastructure) is based on Ubuntu 18.04 which leaves [standard support](https://ubuntu.com/about/release-cycle) in April 2023.
This [new recipe](https://amigo.gutools.co.uk/recipes/arm64-bionic-java11-deploy-infrastructure) is based on Ubuntu 20.04.
1. [Deploy](https://riffraff.gutools.co.uk/deployment/view/5410401a-91be-433a-afd7-0775aba8673d) this branch (there is only one stage, INFRA)
2. The AMI used should be based on focal. Check using [SSM](https://github.com/guardian/ssm-scala):
```sh
ssm cmd -p deployTools -t cloudformation-lens,deploy,INFRA --cmd "cat /etc/lsb-release"
```
```console
➜ ssm cmd -p …
```
=> chore(cloudformation-lens): Use `arm64-focal-java11-deploy-infrastructure` based AMI

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
There are two things that need to talk to the CloudQuery database:
1. CloudQuery itself (write)
2. Grafana (read)
This change creates a Security Group that allows connection to the database, and places its ID in an SSM Parameter to allow Grafana to easily obtain it.
This follows on from the changes in #149.
=> Allow things to talk to CloudQuery database

.github/workflows/ci.yml, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/cloudquery/aws.yaml, packages/cdk/lib/cloudquery/bootstrap.py, packages/cdk/lib/cloudquery/postgresql.yaml
Cloudquery is a great way to collect AWS, and other, sources of data and push it into a destination - in this case Postgres.
This commit represents an initial spike and there will be plenty of follow up work to tidy things up and broaden its behaviour, e.g. by targeting additional accounts.
See also:
https://www.cloudquery.io/
The initial aims is to validate that we can successfully run Cloudquery
[See trello card about spike](https://trello.com/c/1bMquzu6/1813-spike-cloudquery)
Even from some initial queries it is clear that this tool can help us replace some of our custom tracking code.
=> Introduce Cloudquery

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery/aws.yaml
Add `us-east-1` to CloudQuery regions scanned
Some tables such as `aws_organizations_accounts` and `aws_waf_web_acls` the services for which are "global" will not get filled out unless you specify to query the magic original `us-east-1` region. This is necessary to get a good complete view of our infrastructure.
Tested configuration with `cloudquery` locally.
=> Add us-east-1 to CloudQuery regions scanned

config/cloudquery/cloudquery.service, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Since #156, CloudQuery's logs are available in `journald`.
In this change we [configure CloudQuery](https://www.cloudquery.io/docs/reference/cli/cloudquery) to produce logs in JSON format. We also add the `LogKinesisStreamName`, `SystemdUnit` tags to the autoscaling group.
With these three changes, we can take advantage of [devx-logs](https://github.com/guardian/devx-logs) - devx-logs will automatically[^1] produce some configuration for [fluentbit](https://fluentbit.io/) to forward our logs on to Kinesis, allowing them to be ingested into the Central ELK stack.
Having logs shipped to Central ELK increase our visibility[^2].
- Deploy it ([done](https://riffraff.gutools.co.uk/deployment/view/7149a5c5-b352-4b91-8e31-654f181e4a12))
- View [logs in Central …
=> feat(cloudquery): Ship logs to Central ELK

config/cloudquery/postgresql.yaml
In #160 we performed a plugin update, however we did not perform [the necessary migration](https://www.cloudquery.io/docs/advanced-topics/managing-versions#managing-plugin-versions). This is resulting in the following messages being witnessed in the logs:
```log
failed to sync v1 source aws: failed to write for aws (v15.7.0) -> postgresql (v3.0.0): failed to CloseAndRecv client: rpc error: code = Internal desc = Context done: context canceled and failed to wait for plugin: table aws_accessanalyzer_analyzers not found in postgres. make sure to run migrate
```
We _could_ manually perform a migration, however whilst we're still rolling out to production, let's [automatically migrate](https://www.cloudquery.io/docs/reference/destination-spec#migrate_mode) for ease.
Though undesired, a failing …
=> fix(cloudquery): Automatically apply database migration

config/cloudquery/postgresql.yaml, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Verify the full SSL certificate on the RDS connection.
To achieve this, we download and add the signing certificate authority (CA) to the OS trust store. This means the CA is trusted OS wide.
An alternative to this could be to set the [`sslrootcert`](https://www.postgresql.org/docs/11/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT) value in the postgres connection string. Opted against that because it means we have to remember a file path, which is fragile. For example, when we move to an AMIgo recipe, we'd need to ensure these two paths line up, and stay in sync.
Security!
From https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html:
> You can use Secure Socket Layer (SSL) or Transport Layer Security (TLS) from your application to encrypt a connection to a DB instance …
=> feat(cloudquery): Verify RDS SSL certificate

config/cloudquery/cloudquery.service, config/cloudquery/cloudquery.sh, config/cloudquery/postgresql.yaml, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
> **Note**
> It might be easiest to review [commit by commit](https://github.com/guardian/service-catalogue/pull/159/commits).
Switches to use [IAM authentication](https://repost.aws/knowledge-center/rds-postgresql-connect-using-iam) when connecting to the Postgres database. IAM authentication is preferred as it produces temporary credentials (valid for 15 minutes), in place of long-lived credentials.
As the credentials are temporary, we issue them each time the CloudQuery scheduled task runs. If we were to only issue them in the user data, they would have expired by the time CloudQuery would run.
Use of the root credentials is not best practice. With this change, we're using temporary credentials, for a dedicated user.
The branch has been deployed, and CloudQuery has successfully run and …
=> Implement RDS IAM auth for Cloudquery

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
We are now using IAM auth so reading the secret is redundant.
Further to #159, this is a follow up to remove the reading of the secret by the database, [as mentioned here](https://github.com/guardian/service-catalogue/pull/159#discussion_r1162482201). 
IAM auth has now been implement for the Cloudquery database, so this is no longer required.
The branch was deployed and tested on the instance. We confirmed that Cloudquery was still able to talk to the database.
=> Remove reading of secret by Cloudquery database

config/cloudquery/cloudquery.service, config/cloudquery/cloudquery.sh, config/cloudquery/postgresql.yaml, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Download files to `/opt/cloudquery` rather than `/`. Downloading files to a dedicated directory makes things easier to manage, and differentiate system files from our files.
- [Deployed the branch](https://riffraff.gutools.co.uk/deployment/view/204be484-3520-40d0-9a1a-253a8eae8ef4)
- Ran CloudQuery via `systemctl start cloudquery`
- Observed the logs showing CloudQuery continues to run successfully (`journalctl -f -u cloudquery`)
=> refactor(cloudquery): Use `/opt/cloudquery` rather than `/` as base directory

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
This PR adds encryption to the Cloudquery database.
Note: This will cause a database replacement, which will also mean re-creating the Cloudquery user on the instance.
AWS Postgres databases are not encrypted by default, but it is preferable to have encryption.
We deployed this branch and observed the encrypted database in the console. We've successfully run Cloudquery to make sure that we can still write to the database. We've also updated the data source in Grafana and observed the graphs being populated.
=> feat(cloudquery): Add encryption to database

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
This is the [latest version](https://github.com/cloudquery/cloudquery/releases?q=cli) of the CloudQuery CLI.
Keeping up to date is good!
The checksum was obtained from https://github.com/cloudquery/cloudquery/releases/download/cli-v2.5.3/checksums.txt and also confirmed via:
```sh
curl -sL https://github.com/cloudquery/cloudquery/releases/download/cli-v2.5.3/cloudquery_linux_arm64 | shasum -a 256
```
=> chore(deps): Update CloudQuery to v2.5.3

.github/workflows/ci.yml, config/cloudquery/aws.yaml, jest.config.js, package-lock.json, packages/cdk/jest.setup.js, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/package.json
Run Cloudquery in all of our AWS accounts.
So that we can inspect all of our AWS accounts to understand how we are using them.
This uses the OU support that Cloudquery provides to query all of our AWS accounts without having to manually specify them. The docs on how this works are here:
https://www.cloudquery.io/docs/plugins/sources/aws/multi-account#aws-organizations
Cloudquery discovers accounts by querying AWS for the OU members, and then assumes a role in each target accounts to query it.
Note, the process isn't entirely automatic; the cloudquery-access role must be present in target accounts, and this is only present in accounts the aws-account-setup manages. See:
https://github.com/guardian/aws-account-setup/pull/58
TODO - suggestion is that we deploy this branch for a day and see …
=> Run Cloudquery in all of our AWS accounts

packages/cloudquery/prod-config/aws.yaml
This is a major bump, with [breaking changes](https://github.com/cloudquery/cloudquery/releases?q=plugins-source-aws). Reading https://www.cloudquery.io/docs/advanced-topics/migrations and following #162, CloudQuery should automatically perform the necessary steps to migrate.
I've tested locally via #171.
=> chore(deps): Update cloudquery/aws to v16.1.0

packages/cloudquery/dev-config/cloudquery.yaml
Adding some missed changes from #169 to update the version of the cloudquery/aws plugin used.
N/A as was verified in #169. The changes were used in testing, I just forgot to stage them!
=> chore(deps): Update cloudquery/aws to v16.1.0 in DEV

packages/cloudquery/prod-config/aws.yaml
Collect data from all regions as defined by the service control policy - https://github.com/guardian/infosec-platform/blob/main/policies/DenyAccessToNonApprovedRegions.json.
I suspect we'll see the performance issues highlighted in https://github.com/guardian/service-catalogue/pull/170 a lot faster with these changes...
I've spotted a number of EC2 instances outside of eu-west-1 and us-east-1. Being able to see complete usage of all AWS services, across all regions, will be useful.
N/A
=> feat(cloudquery): Collect data across all supported regions

packages/cloudquery/dev-config/cloudquery.yaml, packages/cloudquery/prod-config/aws.yaml
This adds 23 additional tables to the list of those that are ignored (skipped) by Cloudquery.
We are seeing permissions errors on 28 tables ([see logs](https://logs.gutools.co.uk/s/devx/app/discover#/view/461d0f40-d87b-11ed-9ed7-4d35b765d6ad?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-18T05:00:00.000Z',to:'2023-04-18T07:00:00.000Z'))&_a=(columns:!(table,message,error),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'626e7830-dd3a-11ea-88b6-37713dba5739',key:app.keyword,negate:!f,params:(query:cloudquery),type:phrase),query:(match_phrase:(app.keyword:cloudquery))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'626e7830-dd3a-11ea-88b6-37713dba5739',key:level.keyword,negate:!f,params:(query:error),type:phrase),query:(match_phrase: …
=> fix(cloudquery): Skip erroring tables

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Changes the role policy to allow all `List` actions rather than 3 specific ones.
We are seeing permissions errors on the CloudQuery `aws_organizations_accounts` table such as `ListTagsForResource, https response error StatusCode: 400, RequestID: 2e5cd926-af8e-432e-b9b0-b67dd1ed1627, AccessDeniedException: You don't have permissions to access this resource`. 
It appears that the [CloudQuery documentation we followed](https://github.com/cloudquery/cloudquery/blob/main/website/pages/docs/plugins/sources/aws/multi-account.mdx) conflicts with [their template](https://github.com/cloudquery/iam-for-aws-orgs/blame/d44ffe5509ba8a6c84c31dcc1dac7f475a5099e3/template.yml#L35). 
Ran Cloudquery on the branch and the `aws_organizations_accounts` permission errors are nil:
=> fix(cloudquery): Update actions on role policy

package-lock.json, packages/cdk/lib/__snapshots__/cloudformation-lens.test.ts.snap, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/__snapshots__/github-lens.test.ts.snap, packages/cdk/lib/__snapshots__/services-api.test.ts.snap, packages/cdk/package.json
Updates the version of GuCDK being used, to the latest version.
This update includes a couple of key changes that are reflected in the snapshot diff:
- A change to the IAM Policy that enables SSM access ([v49.0.2](https://github.com/guardian/cdk/releases/tag/v49.0.2))
- Moving to launch templates over launch configurations ([v49.4.0](https://github.com/guardian/cdk/releases/tag/v49.4.0))
These are best illustrated in [the commit view](https://github.com/guardian/service-catalogue/pull/178/commits).
See CI - the snapshot tests should pass.
=> chore(deps): Update GuCDK to v50.3.3

packages/cloudquery/dev-config/cloudquery.yaml, packages/cloudquery/prod-config/aws.yaml, packages/cloudquery/prod-config/postgresql.yaml
Upgrades CloudQuery versions for:
- AWS source
- Postgres destination
There is nothing too significant in the Postgres version.
The AWS version is a new major which includes breaking changes. The [release notes](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-aws-v17.0.0) do not suggest anything concerning though.
Keeping up to date is good practice. There might potentially be some performance improvements in these versions too.
Ran locally.
=> chore(deps): Bump CloudQuery AWS source and Postgres destination

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
The `grantConnect` function was patched in [AWS CDK v2.77.0](https://github.com/aws/aws-cdk/releases/tag/v2.77.0), which we updated to in #178.
Less code for us to maintain.
N/A - this is a no-op.
=> refactor(cloudquery): Use AWS CDK method to get DB access

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cloudquery/dev-config/cloudquery.yaml, packages/cloudquery/prod-config/cloudquery.sh, packages/cloudquery/prod-config/template-summary.yaml
The plugin lives here:
https://github.com/guardian/cq-source-cloudformation-template-summary
We have published a v0.1.0 tag version for now, which will become a v1.0.0 once we are happy it is stable.
Note: the plan is to migrate this plugin into the official AWS plugin but that is not wholly within our control.
Introduces our cloudformation-template-summary plugin, to add Cloudformation template metadata as a source.
For now, we use a v0.1.0 tag, which is based off [this PR](https://github.com/guardian/cq-source-cloudformation-template-summary/pull/1).
To track GuCDK usage (see [here](https://github.com/guardian/cdk/pull/1394)).
It has been run locally with the dev config successfully. But testing on PROD is also required as the auth mechanism (assumed roles) is different. We may also …
=> Add guardian/cloudformation-template-summary plugin

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/ecs/cluster.ts, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/task.ts, packages/cdk/lib/ecs/versions.ts
This replaces #184 following the recent adoption of ECS in #189.
In this change we add the [GitHub source](https://www.cloudquery.io/docs/plugins/sources/github/overview) to CloudQuery, initially collecting data only for repositories, once a day.
We authenticate with GitHub using a [GitHub App](https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/creating-a-github-app) that we manually created earlier with read-only access to the org.
CloudQuery requires three bits of GitHub config: private key, app ID, installation ID. These live in a manually created Secrets Manager resource on path `/INFRA/deploy/cloudquery/github-credentials`. The ARN of this resource has a random GUID at the end of it. The only way I could read this secret without passing in the ARN (which is …
=> feat(cloudquery): Collect GitHub repository data 

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/versions.ts
Collecting data for Fastly services once a day, this change adds [Fastly](https://www.cloudquery.io/docs/plugins/sources/fastly/overview) to the data collected using CloudQuery.
To enable this, I've manually created a Secrets Manager resource on path `/INFRA/deploy/cloudquery/fastly-credentials` with a [read-only automation token](https://docs.fastly.com/en/guides/using-api-tokens) provided by @davidfurey. The token has been set to expire on 22-Sep-2023, so we'd need to rotate it before then, should we deem this data useful.
This might allow us to remove some of the Fastly crawling from https://github.com/guardian/aws-budgets.
This has been [deployed](https://riffraff.gutools.co.uk/deployment/view/21fe8d9a-ef9a-461f-9655-0b52353e9f40). The ECS task has been manually run, and we can now …
=> feat(cloudquery): Add Fastly data source

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/versions.ts
- CLI goes from 3.3.1 to 3.5.0
- Postgres goes from 4.1.0 to 4.2.0
- AWS goes from 17.0.0 to 17.4.0
=> chore(deps): Bump CloudQuery versions

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
As Service Catalogue uses a CloudFormation stack as a proxy for a service, its probably a good idea to collect this data more frequently than once a day.
=> feat(cloudquery): Collect CloudFormation data multiple times a day

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/policies.ts, packages/cdk/lib/ecs/versions.ts
Introduces Galaxies as a *source* for Cloudquery using an in-house plugin that lives here:
https://github.com/guardian/cq-source-galaxies
Galaxies does not (atm) support machine access to the API. Reading directly from the bucket is a 'pragmatic' solution here - it is easy to implement but vulnerable to changes in the model. The team do not expect these in the medium term though.
An initial rate of once per day is used as this data doesn't change very often.
Galaxies is the Guardian's source of truth for people, teams, and streams. We want this data to be able to link services to teams and answer questions around **ownership**.
TODO - test in INFRA and see how it goes. (The plugin has already been verified separately through local testing.)
=> Introduce Galaxies as Cloudquery source

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/versions.ts
Running once a day, this change adds [Snyk](https://www.cloudquery.io/docs/plugins/sources/snyk/overview) to the ECS cluster.
Things to note, setting `tables: '*'` in the configuration was yielding errors:
```log
failed to load spec(s) from /source.yaml, /destination.yaml. Error: failed to strip yaml comments in file /source.yaml (section 1): yaml: line 7: did not find expected alphabetic or numeric character
```
Not entirely sure why, but listing the tables explicitly solves this. This isn't massively maintainable, as we'd have to be sure to update the list when we update the version. Thankfully, there aren't (currently) too many [tables](https://www.cloudquery.io/docs/plugins/sources/snyk/tables).
This will help us answer some of this quarter's key questions:
- (Vulnerability …
=> feat(cloudquery): Collect Snyk data in INFRA

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
This PR creates a discrete task to collect data on load balancers and CloudWatch Alarms (tables `aws_elbv1_*`, `aws_elbv2_*` and `aws_cloudwatch_alarms`).
Currently, the "all AWS" task is failing (see #203), and as a result, these tables are empty/stale. Collecting the data in their own tasks should mean the data is kept more up-to-date, and therefore is more reliable. This is particularly important as these tables are used by the @guardian/devx-reliability team.
I've [deployed this](https://riffraff.gutools.co.uk/deployment/view/0141d7df-0d32-408a-8acf-9acf3c1ee163) and manually triggered the task, and can see the tables filling up.
=> feat: Collect load balancers, and CW Alarms on their own

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
The cron expression `cron(* * ? * 1 *)` evaluates to "run every minute on the first day of the week"! That's a little too much. Indeed `cdk synth` on `main` produces this warning:
```
[Warning at /CloudQuery-INFRA/CloudquerySource-GitHubTeams/ScheduledEventRule] cron: If you don't pass 'minute', by default the event runs every minute. Pass 'minute: '*'' if that's what you intend, or 'minute: 0' to run once per hour instead.
```
Use `cron(0 10 ? * 1 *)` instead, which is "run at 10AM on the first day of the week".
The GitHub API is rate limited. Let's not guarantee our violation of that rate limit!
I've used https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html to understand the cron syntax.
=> fix: Run GitHub team task once

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
This is an attempt to reduce the number of requests made to the GitHub API as we're experiencing some rate limiting. [CloudQuery's docs](https://www.cloudquery.io/docs/advanced-topics/performance-tuning#improve-performance-by-skipping-relations) describe the default behaviour of CloudQuery is to collect data of dependant tables, and one needs to add them to `skip_tables` to change this.
The [`github_repositories` table](https://www.cloudquery.io/docs/plugins/sources/github/tables/github_repositories) has a few dependants that we're not (yet) interested in, so we can skip them.
Additionally, the credentials we're using are not scoped to some of these tables, which is resulting in the following errors in the logs:
```log
GET https://api.github.com/repos/guardian/interactive-atom-paygap-calen …
```
=> fix: Skip GitHub tables that we do not (yet) need

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
The "all AWS" task is currently failing (see #203).
We'd like to look at the data from AWS Inspector, so run it as a separate task. This should only be temporary whilst the "all" task is broken.
=> fix: Collect AWS Inspector data

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
This PR creates a new task to collect data for certificate related tables, namely
- `aws_acm_certificates`
- `aws_acmpca_certificate_authorities`
This is currently not being collected and it powers one of the reliability team's grafana dashboards!
I could use some help with this! Should I manually deploy the `deploy::service-catalogue` in riff raff and manually run the task?
=> feat: Collect ACM certificate tables on their own 

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Add an ingress rule to the Postgres security group, allowing connection from the Engineering subnet.
The CloudFormation diff is quite big, however that's largely due to one change - we're now explicitly creating a security group for the database, rather than letting AWS CDK create one. This change has a cascading effect across most other resources in the stack.
As noted, a [bastion host](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.BastionHostLinux.html) might be a better option here as it means we're not reliant on the network to limit access. Thoughts on whether this is blocking welcomed. See also https://github.com/guardian/cdk/issues/1786.
This means we can connect to the database from the office network, as it is sometimes easier to run queries outside of Grafana. …
=> feat: Allow access to Postgres from the office (and VPN)

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/versions.ts, packages/cloudquery/dev-config/cloudquery.yaml
Add [custom snyk plugin](https://github.com/guardian/cq-source-snyk-full-project) as a cloudquery source. This means we are now able to pull project tags and the aggregated issues, grouped by severity.
This PR means we are more easily able to join Snyk data with other sources of information from GitHub or AWS. We are also able to see more about the state of a project at a glance, without needing to join with other tables.
Running the changes locally using docker, we found that all the new information was collected. The change has been deployed and runs successfully
=> Use custom plugin to fetch snyk projects

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/versions.ts, packages/cloudquery/.env.example
Bumps the versions of CloudQuery things being used.
The AWS and GitHub source plugins see a major version update, i.e. a breaking change. Looking at the notes for the [AWS plugin](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-aws-v18.0.0) and the [GitHub plugin](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-github-v6.0.0), the kind of breaking change would not impact us.
=> chore(deps): Bump the version of CloudQuery CLI, sources, and destination

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/ecs/cluster.ts, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/task.ts
IAM authentication for RDS has the following [behaviour](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html):
- The generated password expires after 15 minutes
- A connection established within 15 minutes is valid for as long as the connection is kept
- Attempts to establish a connection after 15 minutes are rejected
Most of the CloudQuery tasks finish well before 15 minutes[^1], however there are some that take over 2 hours (see https://github.com/guardian/service-catalogue/pull/209).
We're seeing these tasks fail, with a log line of:
```log
failed to connect to `host=REDACTED user=cloudquery database=postgres`: server error (FATAL: PAM authentication failed for user \"cloudquery\" (SQLSTATE 28000))
```
It appears that CloudQuery does not hold a …
=> fix: Allow long running tasks to complete

ADR/02-cloudquery.md, docs/cloudquery.md
Adds an ADR to the repository to document the decision to adopt CloudQuery. This is largely an adaptation of the [original proposal document](https://docs.google.com/document/d/1AJGK4HjHf6znEXRGqbbF5gYaq2PmmcrJjsX0feKXd0I/edit).
Also adds an "implementation" document, primarily as a way to have the SQL we've manually executed tracked in VCS.
This is part 1 of a series of changes to document this repository. Other documentation should cover:
- How to manually invoke an ECS task
- How to debug configuration
- How to query the database locally
- Anything else...
ADRs help provide context for our future selves.
By reading the documents, and checking it's an accurate reflection of events.
---
Closes https://github.com/guardian/service-catalogue/pull/182.
=> docs: Add docs for CloudQuery adoption

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
https://www.cloudquery.io/docs/plugins/sources/github/tables/github_issues
Used to understand PR activity, and especially bot activity (such as Dependabot and Scala Steward).
Initially run daily as PRs and Issues change frequently.
=> Add task to ingest github_issues

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
This is a rework of https://github.com/guardian/service-catalogue/pull/209.
We've setup Security Hub as a delegated service in the Security account. This means that account can see Security Hub results for all accounts in the organisation. Collecting the data from each member account is redundant, as it is duplication.
This change collects Access Analyzer and Security Hub data _once_, from the Security account.
This should also reduce the running time of the "all AWS" task (see #220).
I've [deployed](https://riffraff.gutools.co.uk/deployment/view/d4771128-9c33-4714-978b-8032f39957ca) this branch, manually run the task, and observed it run to completion in ~50 mins[^1].
[^1]: Between 21/06/2023, 8:55:56 UTC and 21/06/2023, 9:47:04 UTC
=> fix: Collect Security Hub data once

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/cluster.ts, packages/cdk/lib/ecs/task.ts
If a scheduled CloudQuery task fails, we are not notified. This change introduces an EventBridge rule, where if the container stops with an error code, we get a message telling us which, when, and why. Currently, this message is a rather nasty JSON blob, but it does contain all the information required to figure out what is going on.
Further work should be done in a subsequent PR to turn the alert message into something a bit nicer, maybe we could send the message to a lambda that reformats it and passes it along to Anghammarad. But this is a significant amount of scope creep and needs to be prioritised against our other work. For now (aka the next couple of days), it meets the minimum requirements
We need to know if our data is stale, as we rely on it for OKR purposes. We also need to …
=> Alert if a cluster task fails

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/versions.ts
A bug in the Github Cloudquery source plugin was preventing us from fetching all the data. For full details see:
https://github.com/cloudquery/cloudquery/pull/11727
The fix has now gone [live](https://github.com/cloudquery/cloudquery/pull/11582#issuecomment-1619980238) so we can use it!:
=> Bump Github source plugin version

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
We're not (yet) interested in this table, and it takes a long time to crawl.
The `GitHubRepositories` task runs once a day, and with `github_repository_dependabot_alerts` being collected, the task takes over 24 hours to run!
N/A
=> fix(github): Stop collecting `github_repository_dependabot_alerts`

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/versions.ts, packages/cloudquery/.env.example
Update the [CloudQuery CLI](https://github.com/cloudquery/cloudquery/releases?q=cli).
Just keeping up to date.
I've [deployed this](https://riffraff.gutools.co.uk/deployment/view/e5c89264-0a90-411c-9924-5f292b98f56f), manually run the GitHub tasks, and can see data coming in. For example:
```sql
SELECT COUNT(*) FROM github_repositories;
-- 3300
```
=> chore(deps): Bump CloudQuery CLI from 3.5.2 to 3.9.0

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Collects more GitHub data. The [`github_organization_members` table](https://www.cloudquery.io/docs/plugins/sources/github/tables/github_organization_members) allows us to dashboard the total number of users. The [`github_organizations` table](https://www.cloudquery.io/docs/plugins/sources/github/tables/github_organizations) provides interesting things, such as any defaults we've set.
I have previously deployed these changes to build [this dashboard](https://metrics.gutools.co.uk/d/mhkYgTQVz/github?orgId=1); the "Total users" stat is a count of rows in the `github_organization_members` table 😬.
=> feat: Collect GitHub organisation information

sql/views.sql
The main logical change here is that we are filtering on the tag key, rather than the tag value
There are at least a couple of projects that have tags that are not a commit hash or a repo (eg a team name). By filtering on key rather than value, this query becomes safer.
Running the query returns the expected results.
The current view has been created using this query
=> change query for view_snyk_project_tags

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Start collecting data for all branches, on all repositories as we're interested in this data now.
This data helps understand if a repository is reliably integrated with Snyk. We can compare the commit sha of a repository's default branch, with a Snyk project's commit tag. Where they match, we conclude a repository is reliably integrated with Snyk.
In addition to the aforementioned Snyk checks, this PR is also a simplification of #232, which itself has demonstrated that #229 is not needed.
I've [deployed](https://riffraff.gutools.co.uk/deployment/view/d6835314-0835-4e7c-885a-8e943317da2e) this branch, and manually started the task.
The task completes successfully, and there are some compelling statistics that suggest #229 (and it's related PRs) is not needed:
- The task completes in <7 …
=> Collect GitHub branch data

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/versions.ts, packages/cloudquery/.env.example
Collect all AWS Org data, as we've started to become more interested in it. In particular the `aws_organizations_account_parents` table tells us which OU an account is in.
Uses [wildcard](https://www.cloudquery.io/docs/advanced-topics/performance-tuning#use-wildcard-matching) matching as there are a lot of [tables](https://www.cloudquery.io/docs/plugins/sources/aws/tables):
As we organise OUs by department, knowing which account is in which OU helps us determine how each department is performing.
I've collected `aws_organization*` locally, and can confirm the data is expected.
=> fix: Collect all `aws_organization` tables

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/cloudquery.ts
Changes the schedule for the AWS org data. This data doesn't change that often, certainly not daily, so collect it at a slower rate of once a month.
N/A
=> fix: Collect AWS org data once a month

.env, .gitignore, README.md, jest.config.js, package-lock.json, package.json, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/versions.ts, packages/cdk/package.json, packages/cloudquery/package.json, packages/cloudquery/script/setup, packages/cloudquery/script/start, tsconfig.json
Aimed at improving the story of version upgrades, this PR refactors how we define the versions of CloudQuery being used. Currently, we track the PROD and DEV versions independently, and we're not in sync. In this change, we use the root `.env` file to track the versions for all environments. This should make it easier to verify version bumps.
Keeping two files in sync isn't very fun!
- Followed the README for running CloudQuery locally, and it still works as before
- The CDK snapshot tests passing _and_ not being updated demonstrates this is a no-op for our AWS infrastructure
=> refactor: Use the same CloudQuery versions locally and in PROD

.env, packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/config.test.ts
This PR builds on #240, as a way to demonstrate those changes in practice.
This version includes a fix for the collection of ACM certificates. See https://github.com/cloudquery/cloudquery/issues/12416 for more details.
The `aws_acm_certificates` table is used by @guardian/devx-reliability's dashboards.
I've run CloudQuery locally. Running AWS source v20.0.0 does not collect any ACM certificates. Running AWS source v22.0.1, the ACM table has entries again.
=> chore(deps): Update CloudQuery AWS plugin

package-lock.json, packages/cdk/package.json
Bump version of `@guardian/cdk`, and its peer dependencies of `aws-cdk`, `aws-cdk-libs`, and `constructs`.
Versions obtained via:
```sh
npm info @guardian/cdk@latest peerDependencies version
```
Keeping up-to-date, but also addressing a [security vulnerability in AWS CDK](https://github.com/guardian/service-catalogue/security/dependabot/20) (no impact to this stack, but still good to resolve).
CI passing is enough.
=> chore(deps): Update `@guardian/cdk` from 50.3.3 to 50.10.6

packages/cdk/lib/__snapshots__/cloudquery.test.ts.snap, packages/cdk/lib/ecs/config.test.ts, packages/cdk/lib/ecs/config.ts
This table links a P+E email ID to a Github ID, which is useful to understand ownership of services.
Note, there wasn't a pre-existing Cloudformation version here so I've released a v1.1.0 to match what we expect in `cq-source-galaxies`. I have no idea how this could have worked before without this.
@see https://github.com/guardian/cq-source-galaxies/pull/1
=> Add Galaxies profile info table

sql/views.sql
Some of our dashboards are relying on Cloudquery views. This PR adds a SQL script to create/recreate those views
Views are useful as there are some patterns/joins that we are performing repeatedly, such as connecting a stack to a Galaxies team.
We need an auditable record of our views so that if the database is destroyed, we can recreate this data. We also need to know if and when views have changed, and keeping track of them in GitHub allows us to do this.
At some point we could use something like flyway to manage this, but just having the queries available on GitHub at all is a marked improvement from where we were before
These views are currently live and are viewable in Grafana
=> Add SQL views script to repo

packages/repocop/repocop.ipynb, packages/repocop/rules.py, packages/repocop/test_rules.py, sql/views.sql
Add a `full_name` column, that contains the same values as `repo_name`. refactor repocop collector to reflect this.
To keep column names more consistent with the github source data. Eventually, the `repo_name` column will be removed
- this change can be seen in the production db.
- unit tests are happy
- writing to the repocop table succeeds
A lot of these python queries can be simplified further in a follow-up, now that the names match. This PR captures the minimum required work to migrate from one column to the other
=> introduce full_name column to view_repo_ownership

.github/workflows/snyk.yml
The repocop folder contains a python 3 project. I've modified the snyk.yml to take this into account when scanning the repo for manifests, and pointed it at the dependency manifest
So we can keep on top of our vulnerabilities
The repocop project shows up in snyk
=> Fix the Snyk action

packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/cluster.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/task.ts, packages/cdk/lib/ecs/versions.ts, packages/cdk/lib/service-catalogue.test.ts, packages/cdk/lib/service-catalogue.ts
Changed the stack name to service-catalogue from cloudquery. 
To better reflect the fact that it now includes repocop and cloudquery.
We had to rebuild the stack because the database from the old stack had been corrupted. We took the opportunity to change the stack name.
We successfully deployed with riffraff.
=> Rebuild and rename stack

packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.test.ts, packages/cdk/lib/service-catalogue.ts
- Creates separate CODE and PROD stacks. They supersede the single INFRA stack, which can then be deleted
- Set the cadence of the all ECS jobs in the code stack to be monthly, to minimise cost, while still keeping data vaguely up to date (we will add a mechanism to kick off all these jobs manually in a subsequent PR)
- Create GitHub and Snyk secrets for API keys (these will need to be populated if the secret is recreated)
The last time we attempted a database migration on INFRA, we got ourselves into a bit of a state. A CODE stack means we can test out changes like this in a cloud environment.
The stacks are running, and we can connect to the CODE database to verify the data exists
=> Create a code environment that runs less often.

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/cluster.ts, packages/cdk/lib/ecs/task.ts, packages/cdk/lib/service-catalogue.ts
To help distinguish between each task, add a `Name` tag.
Additionally, rename the "All" task to "RemainingAwsData" for clarity (this creates quite the snapshot diff!)
=> fix: Add `Name` tag to ECS task definitions

sql/views.sql
This view's definition was missing from the file. Adding it for completeness.
The definition was taken from [this comment](https://github.com/guardian/service-catalogue/pull/233#issuecomment-1662615497).
=> fix: Add `aws_accounts` view

packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
AWS defaults to no protection on RDS instances 😱. This change enables protection for the PROD database.
RDS holds state, so being protected from accidental deletion is desired, at least for PROD.
See the snapshot changes.
=> fix: Enable deletion protection for PROD RDS database

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
The [`github_workflows` table](https://www.cloudquery.io/docs/plugins/sources/github/tables/github_workflows) has a `content` column, allow the workflow file's content to be queried.
With adoption of GitHub Actions for CI is growing, it'll be interesting to see how we're using GHA. Potential use-cases include:
- A vuln. has been detected in a third-party action. Which repositories are impacted?
- How is a repository integrated with Snyk? Via the departmental action? Or other means?
Ran locally.
=> feat: Collect GitHub Workflow data

.github/dependabot.yml
We previously used the "dependency-updates" branch to batch multiple dependency updates into one PR to reduce the amount of PRs to review (1 mega PR, vs multiple small ones).
We've since removed this process[^1], so we need to raise PRs to `main`.
[^1]: I can't remember why and can't find when...
=> chore: Configure Dependabot to target the default branch

packages/cloudquery/src/index.ts
Currently, the `list-tasks` command returns a list of all tasks, their ARN, and tags.
This is quite a lot of information, and more than we typically want. Typically, we only want to know the task names.
This change adds a `debug` flag to the `list-tasks` command. When `true`, all the detail is printed.
When `false`, only the names are printed. This is the default.
Offers a simpler DX.
By running it locally:
```console
➜ npm run cli --workspace cloudquery list-tasks -- --stack deploy --stage CODE --app service-catalogue
> cloudquery@0.0.0 cli
> ts-node src/index.ts "list-tasks" "--stack" "deploy" "--stage" "CODE" "--app" "service-catalogue"
[
"DelegatedToSecurityAccount",
"DeployToolsListOrgs",
"FastlyServices",
"Galaxies",
"GitHubIssues",
"GitHubRepositories",
"GitHubTeams", …
```
=> feat(cli): Simplify the `list-tasks` command output

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
This adds a new rule to the individualAwsSources list to process the aws_autoscaling_groups table.
This removes the table from the very bloated remaining AWSSources list allowing the autoscaling groups to be quickly made available to the SLO debug dashboard.
This is one of the tables on the critical path for the Reliability Team's SLO dashboards. Moving it to its own rule allows us to debug any issues with this table more quickly.
Verified by deploying to code and testing that table populates and that the SLO dashboards populate correctly for a range of accounts and services
=> Create a seperate task to process the aws_autoscaling_groups table

package-lock.json, package.json
Update `@guardian/eslint-config-typescript` to the latest available version, and update `typescript` to match the `peerDependencies` of `@guardian/eslint-config-typescript`.
Versions discovered via:
```sh
npm info @guardian/eslint-config-typescript@latest peerDependencies version
```
Observe CI - a passing build is sufficient here.
=> chore(deps): Update `@guardian/eslint-config-typescript` to 7.0.0

.github/workflows/ci.yml, package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts, packages/repocop/.gitignore, packages/repocop/index.js, packages/repocop/index.ts, packages/repocop/package.json, scripts/ci.sh
Add a scheduled typescript lambda, scheduled one a week
It is preparatory work to add repocop as a cloudquery based lambda
Deploy to code 
[riffraff deployment](https://riffraff.gutools.co.uk/deployment/view/66e529c2-e4be-4ec4-99dd-e287fe7c7349)
[elk logs](https://logs.gutools.co.uk/s/devx/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'626e7830-dd3a-11ea-88b6-37713dba5739',key:app.keyword,negate:!f,params:(query:repocop),type:phrase),query:(match_phrase:(app.keyword:repocop))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'626e7830-dd3a-11ea-88b6-37713dba5739',key:lambdaEvent,negate:!t,type:exists,value:exists),query:(exists:(field:lambd …
=> Add scheduled typescript lambda

README.md, packages/cloudquery/README.md, packages/cloudquery/script/setup
This change improves the developer experience. Following the instructions now means that this works first time. I've also added some more information that will be useful for first time contributors.
I've also made the output from the script more readable, simplifying the paths displayed in the output, and showing error messages in a different colour
Having pulled the repo fresh and trying to follow the setup instructions, I'd often have to go back and repeat steps. The steps are now in the correct order.
Often, when setting up the project, users did not understand that the setup script was failing. Showing the error message in a different colour will hopefully make that clearer
Tested locally. Now a bad output looks like this. Much more error-y
=> Streamline docs

.github/workflows/ci.yml
Since #267 we no longer have Python in the repository, so can remove it from the CI environment.
=> ci: Remove `actions/setup-python`

jest.config.js, packages/repocop/package.json, packages/repocop/src/index.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts, sql/dbuser.sql
Heavily inspired by #260, this change provides an initial implementation applying RepoCop logic:
1. Get one repo
2. Get all branches
3. Evaluate [rules repository_01 (default branch should be main), and repository_02 (branch protection on default branch)](https://github.com/guardian/recommendations/blob/main/best-practices.md)
4. Write results to database
AND TESTS!
Note: We've disabled the linter on the repocop project, so there might be some formatting issues!
This change completes the end to end demonstration of using Prisma for RepoCop. The next stage would be to implement the evaluation of the remaining rules. This will be done in a separate PR.
Run the branch locally via `npm -w repocop start`, observe the logs, and observe the `repocop_github_repository_rules` table being written …
=> feat(repocop): Add logic to evaluate rules repository_01 and repository_02

package.json, packages/repocop/prisma/schema.prisma
This follows from #295.
**TL;DR - generate a smaller Prisma client to give eslint less work.**
When we first introduced Prisma in #280, we saw eslint exiting with OOM issues, and so we disabled eslint from the repocop directory.
<details>
<summary>Example of OOM caused by running eslint on all directories</summary>
This was run on `main`.
```console
➜ npm run lint
> service-catalogue@0.0.1 lint
> eslint packages/** --ext .ts --no-error-on-unmatched-pattern
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0
YOUR TYPESCRIPT VERSION: 5.1.6
Please only submit bug reports when using the officially …
```
=> chore(repocop): Enable eslint to ensure consistent code style

packages/repocop/src/config.ts, packages/repocop/src/index.ts
We were previously evaluating one repository. This change evaluates all repositories, excluding those that are archived or outside of P&E. We're performing this filtering via SQL, which though isn't unit tested, does mean we hold less in memory, that is, it should be more performant.
Ran locally. I've also [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/43f216e2-25f5-46c8-804a-7dd1e15cdb57), and successfully executed the lambda.
=> feat(repocop): Evaluate all repositories

packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
Implements rule [repository_04](https://github.com/guardian/recommendations/blob/main/best-practices.md):
> Grant at least one GitHub team Admin access - typically, the dev team that own the project.
> Repositories without one of the following topics are exempt: production, testing, documentation.
Run Repocop locally. I've also [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/c236cb9b-db4c-4e4c-9e35-c326ade5e6c0), and successfully executed the lambda.
=> feat(repocop): Implement rule repository_04

packages/repocop/src/index.ts, packages/repocop/src/query.ts
Moves all query functions into the `query.ts` file.
For better organisation - `index.ts` now simply imports from `query.ts` and passes the results into the rule evaluation function.
N/A.
=> refactor: Move all query parts into `query.ts`

packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
Implements rule [repository_06](https://github.com/guardian/recommendations/blob/main/best-practices.md):
> Repositories should have a topic to help understand what is in production.
> Repositories owned only by non-P&E teams are exempt.
I'm not sure how best to apply the exemption. We're already filtering out repositories that start [interactive-](https://github.com/guardian?q=interactive-&type=all&language=&sort=) or [oz-](https://github.com/guardian?q=oz-&type=all&language=&sort=). However this doesn't catch all non-P&E repositories, such as https://github.com/guardian/dog-breeds or https://github.com/guardian/my-project. I don't think this is a blocker; we'll be over reporting a little, but all the P&E owned repositories will be included.
Run Repocop locally. I've also [deployed to …
=> feat(repocop): Implement rule repository_06

packages/repocop/src/config.ts
Filters out repositories starting with [esd-](https://github.com/orgs/guardian/repositories?language=&q=esd-&sort=&type=all), as they are owned by ESD.
The initial audience for Repocop is the P&E department, so remove ESD owned repositories to reduce noise.
N/A.
=> fix(repocop): Do not evaluate ESD owned repositories

packages/repocop/src/config.ts
Follows on from #309.
RepoCop's initial audience is the P&E department. Add some more exclusions to reduce noise. Today, these repositories account for 1334 of the 3450 in the GitHub organisation.
| prefix | count |
| :--- | :--- |
| guardian/aus- | 15 |
| guardian/australia- | 4 |
| guardian/australian- | 55 |
| guardian/esd- | 45 |
| guardian/interactive- | 1011 |
| guardian/interactives- | 17 |
| guardian/main-media- | 18 |
| guardian/oz- | 136 |
| guardian/pluto- | 12 |
| guardian/us- | 16 |
| guardian/visuals- | 5 |
<details>
<summary>SQL query used</summary>
```sql
SELECT  'guardian/interactive-' AS "prefix"
, COUNT(full_name)
FROM    github_repositories
WHERE   full_name LIKE 'guardian/interactive-%'
UNION ALL
SELECT  'guardian/interactives-' AS "prefix"
, COUNT(full_name)
FROM …
```
=> fix(repocop): Ignore more non P&E repositories

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Increase the timeout of the Repocop lambda to the maximum (15 minutes). Repocop is making an increasing amount of SQL requests. The performance on these requests is largely related to the indexing of the database. Using the maximum duration provides enough time for the queries to complete.
This will impact costs if the lambda runs for over 30 seconds:
> Duration is calculated from the time your code begins executing until it returns or otherwise terminates, rounded up to the nearest 1 ms*. The price depends on the amount of memory you allocate to your function. In the AWS Lambda resource model, you choose the amount of memory you want for your function, and are allocated proportional CPU power and other resources. An increase in memory size triggers an equivalent increase in CPU available …
=> feat(repocop): Increase the timeout of the lambda

packages/repocop/src/index.ts, packages/repocop/src/query.ts
Previously, we were getting branches for each repo by making a DB call for each one. Now, we are grabbing all the ones we need at the beginning
Fewer requests mean fewer chances for requests to fail. Also places less strain on the DB
~~Tested a before and after on CODE. Job ran successfully. We've gone from 7.5GB seconds to 9 GB seconds. Assuming one run a day for 30 days, this equates to an additional cost of $0.00075 per month (about 1/12th of a cent). Which seemed like an acceptable increase to me.~~
After following @akash1810 's advice on filtering archived repos, we've actually **dropped** from 7.5 GB seconds to 7.1.
=> Get all unarchived branches up front

packages/repocop/README.md, packages/repocop/prisma/migrations/20230915151426_repository_05_and_07_optional/migration.sql, packages/repocop/prisma/schema.prisma, packages/repocop/src/rules/repository.ts
Make repository_05 and 07 in table repocop_github_repository_rules optional
These will not be implemented in the first iteration of repocop and having the field populated with true or false is misleading
Applied database migration to code with
```
npx prisma migrate deploy
```
Deployed to code and started lamda and verified that the fields repository_05 and repository_07 are now populated with null
Before merging the database migration should be applied to prod
=> repository_05 and 07 optional

packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
We saw some repos with valid owners failing the repo_04 check, because of the way we were checking the topics. Some repos have topics that are not recognised by devX, so using `repo.topics.length === 0` as the first check for "might be in production" doesn't work, as a repo with topics such as `avocado` or `misc` would have counted as having a valid topic, then short circuited and never moved on to the second check.
The topic check has also been refactored slightly for improved readability, and we will update the recommendations repo to reflect this.
Having multiple topics recognised by devx can cause confusion about what a repo is used for. It also potentially causes confusion for REPOSITORY_04, as something with both a `hackday` and `production` topic is not valid, and we don't have …
=> Modify some repo rules

.gitignore, packages/cloudquery/dev-config/cloudquery.yaml, packages/repocop/README.md
- Moves GitHub first in the sequence of sources for local development, so you don't have to wait for all the AWS tables when Cloudquery runs.
- Updates Repocop README for clarity and with more info about running locally.
- Adds Intellij's module file to `.gitignore`.
To make it easier for a new user to get up and running with Repocop.
Tested locally.
=> Improve running locally

packages/repocop/prisma/migrations/20230920113337_snyk_tables/migration.sql, packages/repocop/prisma/schema.prisma
Snyk tables included in the prisma client
We can start tracking whether or not repos are integrated with snyk.
Migration has been applied to schema locally, and snyk tables are accessible via the prisma client
=> Add snyk tables to prisma

docs/getting-started.md, packages/cloudquery/README.md, packages/cloudquery/dev-config/cloudquery.yaml, packages/cloudquery/script/start, scripts/setup.sh
Previously, we were using developerPlayground and deployTools resources to test Cloudquery. This required us to fetch two sets of credentials. We are now using only deployTools resources for local testing.
To improve the developer experience, and make setup faster
The correct error messages show up at the expected points, and we are able to gather AWS data locally for the relevant account
=> Use deployTools as dev account

.env, package-lock.json, packages/cloudquery/README.md, packages/cloudquery/docker-compose.yaml, packages/cloudquery/script/start, packages/repocop/README.md, packages/repocop/package.json, packages/repocop/script/migrate.sh, packages/repocop/script/migrate_dev, packages/repocop/src/run-locally.ts, scripts/setup.sh
- Puts local env vars for Postgres DB into the root `.env` file so that they can be retrieved when running CloudQuery and Repocop locally
- Creates a migrate script which will eventually migrate for DEV, CODE and PROD, but this PR is concerned with DEV only. 
- Simplifies running Repocop locally as the `DATABASE_URL` env var is set in the migrate script.
- Updates the Repocop README to reflect the changes.
- Changes the name and path for the local .env file for simplification and clarity.
This makes running locally simpler and now env vars are shared between scripts rather than being set manually. 
Running `./scripts/setup.sh` followed by `npm start -w cloudquery`, `npm migrate:dev -w repocop` and `npm start -w repocop` all works.
=> Refactor: create local migrate script

packages/repocop/prisma/migrations/20230928080512_guardian_production_status/migration.sql, packages/repocop/prisma/migrations/20230928080813_guardian_non_p_and_e_github_teams/migration.sql, packages/repocop/prisma/schema.prisma, sql/views.sql
Adds a couple of manually created enumeration tables as Prisma migrations, to reduce the amount of manually invoked SQL.
This is related to some work to bring our views into Prisma. Part of this involves [introspecting the views](https://www.prisma.io/docs/concepts/components/prisma-schema/views#use-introspection). I'm pulling this change out separately to keep the diff as small.
=> fix(prisma): Bring some manually created tables into Prisma

packages/repocop/prisma/migrations/20230928084104_view_repo_ownership/migration.sql, packages/repocop/prisma/schema.prisma, packages/repocop/src/index.ts, packages/repocop/src/query.ts, sql/views.sql
Following https://github.com/guardian/service-catalogue/pull/338, this change brings the SQL view `view_repo_ownership` into Prisma[^1] so that it can be used within RepoCop.
In order for RepoCop to know who to notify about a repository, we need to know who owns it, this information is within the `view_repo_ownership` view.
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/6a5f63dc-32ea-46b7-8984-03867cc0b209), run the lambda, and observed [the logs](https://logs.gutools.co.uk/s/devx/app/discover#/doc/626e7830-dd3a-11ea-88b6-37713dba5739/logstash-dev-tools-2023.09.28?id=B38O24oB1GrvOkJ_ak7i) matching the view.
[^1]: SQL view support in Prisma is currently in "ver early Preview" - https://www.prisma.io/docs/concepts/components/prisma-schema/views
=> feat(repocop): Query the `view_repo_ownership` view

package-lock.json, packages/branch-protector/package.json, packages/branch-protector/src/index.ts
- Uses repo owner to send notifications to the department
- Add a call to action so teams can check their branch protections themselves
We don't want all these notifications to come to devx.
This is possible now that https://github.com/guardian/anghammarad-config/pull/18 has been merged. https://github.com/guardian/anghammarad-config/pull/19 will allow more departmental teams to be notified
Ran locally, messages routed via github team are delivered.
=> Use new github team mapping to send notifications

scripts/setup.sh
Makes setup process easier to follow. Use an incrementing number for `STEP_COUNT` so functions can be run in any order
Make it clearer what is happening when
Output now looks like this
Previously it looked more like this
=> make setup process clearer

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Seperate S3 CloudQuery tables into a seperate Task.
Part of debugging why we're missing some buckets in our Cloudquery results.
=> Seperate S3 CloudQuery tables into a seperate Task.

.github/workflows/ci.yml, package-lock.json, packages/branch-protector/package.json, packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/config.ts, packages/branch-protector/src/github-requests.ts, packages/branch-protector/src/index.ts, packages/branch-protector/src/model.ts, packages/branch-protector/src/run-locally.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts, scripts/ci.sh, scripts/setup.sh
- Branch protector now reads off an SQS topic.
- The schedule of this lambda has initially been set to weekly, while we are still testing  but this will change as we find the optimum cadence.
- Functions have been pulled out to separate files based on what APIs they are calling.
This looks like a much larger PR than it is, due to bits of code being moved about, and a large snapshot. The main functional change is the introduction of the `getEvents` method, to read items in the queue
We are also pulling the anghammarad ARN as part of the setup script
Local execution does still work, but the developer experience has been degraded slightly as some environment variables need to be manually retrieved and set. This will be addressed in a subsequent PR
TODO: 
- Set QUEUE_URL as part of local …
=> Set up branch protection app as a lambda

packages/repocop/README.md, packages/repocop/package.json, packages/repocop/script/migrate.sh
- Provides NPM scripts for Prisma migration to code and prod environments.
- The code and prod migration scripts require confirmation in order to continue, just to be extra safe.
- Provides an NPM script for local setup of Prisma.
- The scripts create the `DATABASE_URL` environment variable that Prisma requires. In the case of code and prod, these are created from secret retrieved from Secrets Manager.
- Updates the dev script for running locally, separating out the reset function from the adding a new migration function.
- Updates the README to reflect the changes.
- Prisma migration requires the setting of the `DATABASE_URL` environment variable. This previously relied on users putting the correct values into their environment, which is far from ideal and risks committing secrets.
- …
=> Prisma migrate scripts

package-lock.json, packages/repocop/package.json
Removes a duplicated line from `package.json`, resolving this warning displayed during `npm i`:
```
Warning: G] Duplicate key "@types/aws-lambda" in object literal [duplicate-object-key]
package.json:6:4:
6 │     "@types/aws-lambda": "^8.10.119",
╵     ~~~~~~~~~~~~~~~~~~~
The original key "@types/aws-lambda" is here:
package.json:5:4:
5 │     "@types/aws-lambda": "^8.10.122",
╵     ~~~~~~~~~~~~~~~~~~~
1 warning
```
=> chore(deps): Correct `package.json`

package-lock.json, packages/cdk/bin/cdk.ts, packages/cdk/package.json
Update `@guardian/cdk` to the latest version, [51.0.0](https://github.com/guardian/cdk/releases/tag/v51.0.0).
The AWS CDK dependencies have also been updated, to match the peer dependencies of GuCDK:
```console
➜ npm info @guardian/cdk@latest peerDependencies version                     
peerDependencies = {
'aws-cdk': '2.100.0',
'aws-cdk-lib': '2.100.0',
constructs: '10.3.0'
}
version = '51.0.0'
```
CI continuing to pass, with no changes to the snapshot, provides confidence in this change.
=> chore(deps): Update GuCDK from 50.10.14 to 51.0.0

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/task.ts
https://github.com/guardian/devx-logs/pull/32 should be merged first, to ensure log lines have the correct markers in Central ELK.
Replaces the logging container with the one from [devx-logs](https://github.com/guardian/devx-logs/tree/main/ecs).
The devx-logs solution is more "official", and with this change we can archive https://github.com/guardian/hackday-firelens.
https://github.com/guardian/service-catalogue/pull/369 tests https://github.com/guardian/devx-logs/pull/32. Once deployed to CODE, the logs in Central ELK look like this:
=> chore(deps): Use logging solution from devx-logs

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/config.test.ts
Bumps the Cloudquery AWS plugin to 22.15.0
We fixed the bug in this version of CQ AWS which was causing some old buckets to not appear in our S3 buckets table.
https://github.com/cloudquery/cloudquery/pull/14476
=> Update Cloudquery AWS plugin to 22.15.0

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/config.test.ts
Bump the Cloudquery Github plugin to V7.4.0
v7.4.0 introduces several new tables which contain information about Github action workflow runs. This'll allow us to know various bits of information such as "how long a workflow takes on average", "what runners are most actively used and how much does it cost us", and "how often does a workflow need to be retried"
Back when I was in WebX we had some workflows that would fail all the time. A dashboard that could quantify how much time is being spent on re-running workflows would have been quite useful for planning time to make improvements to GHA.
https://github.com/cloudquery/cloudquery/pull/14529
https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-github-v7.4.0
<del>DNM - Need to check if our current Github token has access …
=> Bump CQ Github plugin to v7.4.0

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/service-catalogue.ts
In https://github.com/guardian/service-catalogue/pull/372 we bumped the GitHub source plugin, noting that it provides more data.
This change creates a `RemainingGitHubData` task, which will collect those tables that are not part of a discrete job. This is similar to the `RemainingAwsData` task.
See https://github.com/guardian/service-catalogue/pull/372 for some possible questions this can help answer.
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/1867ab04-f2dc-44f8-8374-655382451b38), ran the task, and can see the [data in Grafana](https://metrics.code.dev-gutools.co.uk/goto/2s2ThinIz?orgId=1).
=> feat(cloudquery): Collect remaining GitHub tables

packages/repocop/README.md
- Edits the repocop README to make information about the `DATABASE_URL` (hopefully!) clearer.
- It was a little confusing mentioning the format of the url (implying that the user will have to set it) when it is set automatically by a script now.
Is it easier to understand?
=> docs: update repocop README

packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/index.ts
Previously, we were reading the messages off of SQS, and then letting them sit there. This meant that we were reading the same messages over and over again. Now we delete messages after branch protection has been successfully applied.
This prevents a backlog accumulating, as we can now read new messages off of the queue.
Tested on DEV. NB that even for local invocations, we are interacting with real AWS resources, namely reading/deleting messages from the CODE queue.
=> burn after reading

packages/branch-protector/src/config.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
- Updates the schedule for the `branch-protector` lambda to run every morning at 9am Tue-Fri only. 
- Makes a small change to the way the `GITHUB_APP_SECRET` env var is retrieved.
- We don't want people being notified about their branch protection being enabled on a non-working day. Starting the lambda on a Tuesday allows for pre-messaging to go out on the Monday also.
=> Refactor: Change branch protector schedule

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/config.ts
Add `aws_stepfunctions_executions` to list of skipped AWS tables
Like `aws_stepfunctions_map_executions` this table is extremely verbose as it tracks every invocation of a `Step Function`. [AWS holds step function execution history for up to 90 days](https://docs.aws.amazon.com/step-functions/latest/dg/limits-overview.html), and atleast one of our accounts has a Step Function that is executed every couple of minutes.
I don't think this data is particularly useful to us, and maybe we can consider trying to make this table incremental if we ever do need this data. The API is also "eventually consistent" which causes a lot of errors in our syncs.
=> Add `aws_stepfunctions_executions` to list of skipped AWS tables

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/config.test.ts
Theres been a couple of fixes to some of the tables that we're querying.
- Don't error on ECR repositories when they're missing Lifecycle policies (aws_ecr_repository_lifecycle_policies) ([#14730](https://github.com/cloudquery/cloudquery/issues/14730)) ([352d46d](https://github.com/cloudquery/cloudquery/commit/352d46d784326ecb5aecab7a18c9df3a463f8e63))
- Don't error on S3 buckets with Object Lock disabled (aws_s3_bucket_object_lock_configurations ) ([#14726](https://github.com/cloudquery/cloudquery/issues/14726)) ([3328007](https://github.com/cloudquery/cloudquery/commit/33280074c71e4db21049842710fb268b2ca5ba0b))
=> Bump Cloudquery AWS plugin to 22.15.2

.env, packages/repocop/src/run-locally.ts
Removes some env var aliasing when running RepoCop locally, in favour of reading values directly from the `.env` file.
It's simpler.
N/A.
=> refactor(repocop): Read straight from `.env` file to reduce duplication

packages/repocop/src/run-locally.ts
Obtain the home directory from the `os` package. This allows us to remove an `eslint` disablement.
=> refactor: Obtain home directory via `os`

packages/repocop/README.md
Updates the Repocop README with (hopefully) clearer instructions for running locally.
The original instructions were unclear that you need to wait for Cloudquery to populate the database before running Repocop.
I successfully followed the instructions locally.
=> docs: update Repocop README to make running locally clearer

packages/repocop/src/remediations/repository-02.test.ts, packages/repocop/src/remediations/repository-02.ts
Limits Repocop to only messaging DevX teams about branch-protector remediations.
This is a temporary change to allow us to fully test and improve messaging from Anghammarad without bothering other teams.
Tested on CODE. Ran the Repocop lambda twice and it added a total of 3 DevX-owned repos to the branch-protector queue, and none owned by other teams.
=> refactor: temporarily restrict branch protector messaging to DevX teams

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Corrects the schedule for the `branch-protector` lambda to run Tuesday-Friday. It was running Monday-Thursday which was an error.
We want the branch protector to run on working days only, so that the messages are seen by teams when branch protection has been applied.  We don't run on a Monday to allow for all warning messages to be seen by teams that were sent from Saturday to Monday inclusive.
Cannot test on CODE, will merge and check the schedule. If it's wrong, will revert.
=> fix: correct schedule for branch protector lambda

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Sets the task to collect all other AWS data to run once a week, and documents the reasoning.
We're seeing this task take a long time to complete (over 15 hours, and counting). We don't need this data to be super fresh as we're not using it.
N/A.
=> fix: Collect remaining AWS data once a week

packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/index.ts
Currently, the branch protector lambda takes one message off the queue each time it runs (once per day Tue-Fri).  Currently Repocop adds up to two messages to the queue every day. This change means that branch protector will now take all the messages from the queue when it runs. N.B. Repocop has just been temporarily configured to add only DevX-owned repos to the queue, so we will be the only team affected going forward although there are other teams' repos on the existing queue which will hopefully be cleared down.
We want the branch protector to clear down the queue every day it runs so that protections are applied in a timely manner. 
It will be verified on PROD, which is why we're restricting it to DevX repos while testing.
=> refactor: remove rate limit on branch protector reading from the queue

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/task.ts
Use v1 of devx-logs
I will be making some breaking changes in https://github.com/guardian/devx-logs/pull/34 which will cause `main` to break logging for service-catalogue . Also good practice to not always use the latest version of a docker image.
=> Use a v1 of the devx-logs Image instead of latest

packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/index.ts
Testing PROD has revealed that removing the number of messages param from the `readFromQueue` function in `branch-protector` has not removed rate limiting, it has just defaulted to 1. The allowed maximum is 10, so this PR reverts the previous removal and sets the max to 10.
- Reverts guardian/service-catalogue#411
- Increases number of messages taken from queue from 1 to 10 (the max)
This is for the meantime, ahead of a further planned refactor of `branch-protector` to make it batch work more effectively.
=> Revert "refactor: remove rate limit on branch protector reading from the queue"

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Reverts guardian/service-catalogue#410 as by 10:14AM on Monday 30th October 2023, we had ~187 instances of this task running. This is ~186 more than intended!
=> Revert "fix: Collect remaining AWS data once a week"

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Follows #416, and #410 to set the `RemainingAwsData` task to run at 10AM on Monday's. It was previously every minute, of every hour on Monday!
---
Co-authored-by: @tjsilver
=> fix(cdk): Run the RemainingAwsData task each Monday at 10AM 

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/cluster.ts, packages/cdk/lib/ecs/config.ts, packages/cdk/lib/ecs/task.ts, packages/cdk/lib/ecs/versions.ts, packages/cdk/lib/service-catalogue.ts, packages/cli/src/aws.ts, packages/cloudquery/docker-compose.yaml
Source riff-raff data such as deployment history into Cloudquery by using the riff-raff. This is done using the [Postgresql source plugin](https://www.cloudquery.io/docs/plugins/sources/postgresql/overview) to pull data from some [custom views](https://github.com/guardian/riff-raff/pull/1273) created in the riff-raff DB.
New tables:
- `riffraff_deploys` - List of all deploys
- `riffraff_deploy_logs` - History of each deployment
- `riffraff_authorized_history` - Users with access to riff-raff
Requires https://github.com/guardian/riff-raff/pull/1273 & https://github.com/guardian/deploy-tools-platform/pull/731 to be merged first.
This lets us answer questions such as "Whats the latest version of an application running in production?" or "Is an application being deployed everyday?" or "What …
=> Source deployment data from RiffRaff

package-lock.json, packages/branch-protector/package.json, packages/branch-protector/src/aws-requests.ts, packages/repocop/package.json, packages/repocop/src/remediations/repository-02.ts
This change adopts the recently added message threading in Anghammarad (see https://github.com/guardian/anghammarad/pull/138) to group messages together.
Messages from RepoCop and Branch Protector will appear on the _same_ thread, for all time.
❓ Should there be a different thread per day?
The intention here is to reduce noise in Chat. Grouping messages together also helps to keep a running narrative of events.
I've run RepoCop and observed the messages in Chat appearing on a single thread:
=> feat(messaging): Send messages to a thread, rather than individually 

packages/cloudquery/dev-config/cloudquery.yaml
Use `CQ_POSTGRES_DESTINATION` instead of `CQ_POSTGRES`
I renamed this variable in https://github.com/guardian/service-catalogue/pull/424 and its breaking our local cloudquery environment.
=> Fix Cloudquery dev-config using the old CQ_POSTGRES variable

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
This PR allows us to collect DynamoDB data once per day. 
Currently this data is [collected once per week](https://github.com/guardian/service-catalogue/blob/6ead55e82f342f37011195dba1e95400a9f13456/packages/cdk/lib/service-catalogue.ts#L302-L308), but DevX Reliability are tracking one of their KRs based on this data, so it'd be nice to have more regular updates.
As we are copying an existing pattern, I think the snapshot testing is sufficient here, but please let me know if you'd normally test anything else before merging a PR like this.
=> Add dedicated CloudQuery source for DynamoDB tables

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
The [aws_ec2_instances](https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_instances) and [aws_ec2_security_groups](https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_security_groups) tables are currently being collected in the `RemainingAwsData` task, once a week.
This change collects the data every 5 minutes. This cadence is rather arbitrary TBH. It could very easily be once a day, similar to most other tasks. It would be interesting to see if we can make this real-time however, as it will allow us to replace https://github.com/guardian/prism. We might want to change the cadence of this, based on how long it takes to run.
In addition to the above, we report on the "30 day old" SLO in the weekly 5/15 report every Friday. Having the data be "fresh" for that …
=> feat(CloudQuery): Collect EC2 instance, and security groups every 5 minutes

packages/repocop/prisma/migrations/20231027112910_github_repository_rules_friendly_names/migration.sql, packages/repocop/prisma/schema.prisma, packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-02-branch_protection.test.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
- Renames the Repocop best practice rules in the `repocop_github_repository_rules` from their IDs to their Names.
- Renames the rule evaluation functions to indicate what they do using the friendly names, and updates the function comments to be more accurate.
It will be easier for users to visit the [Repocop Compliance](https://metrics.gutools.co.uk/d/EOPnljWIz/repocop-compliance?orgId=1) dashboard and understand which rules their team's repos are breaking, reducing the number of times they will have to access the [rule definitions](https://github.com/guardian/service-catalogue/blob/main/packages/best-practices/best-practices.md). This is supported by the results of the recent UX research.
The migration has been applied on CODE and the renamed columns can be seen on this [CODE …
=> refactor: friendly names for repocop rules

packages/repocop/src/query.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts
The team repos logs are quite noisy. Made them debug statements so we can filter them out if needed.
Log which repos have been added to the queue
Make debugging easier
Deployed to code and verified the new message still shows up.
The debug statements also still show up, so no behaviour has changed there
=> Tweak logging

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
1. Changes schedule of remaining AWS tasks from 10am on Monday to 4pm on Saturday
2. Lower timeout of repocop
1. The job running during the week means a lot of DB connections are used up when things like repocop are running, resulting in timeouts. Moving it to the weekend makes this issue less prelevant.
2. Repocop typically takes between 10 and 70 seconds to complete. A hanging DB request here means that the lambda will wait for 15 minutes before failing, accumulating cost, and wasting resources. Lowering the timeout to 5 minutes reduces that waste, while also giving us plenty of headroom.
=> Change scheduling

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/task.ts, packages/cdk/lib/service-catalogue.ts
The current certificate authority (CA) (rds-ca-2019) is due to expire in August 2024. Update to the newer rds-ca-rsa2048-g1. This CA supports automatic rotation too! See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.RegionCertificateAuthorities.
According to the [CloudFormation spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-cacertificateidentifier), this change should not replace the current database, however it will require a database reboot. This might cause running CloudQuery tasks to error, however we can simply rerun them.
=> fix: Update RDS certificate authority

packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/github-requests.ts
Adds some error messaging to branch protector functions.
Branch protector was only deleting one message off the queue rather than one after each application of branch protection (10 per day). Although this is now fixed, and probably due to an edge case, this will help to understand when we do have errors.
Branch protector only applies branch protection on PROD so it is not possible to test all of this in CODE.
=> feat: add some error messaging for branch protector functions

packages/repocop/src/remediations/repository-02-branch_protection.test.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts
Allows branch protector to be applied to all teams in the department, reverting the temporary restriction to DevX repos.
The app is now in a place where we can roll it out more widely again and get teams' branches protected.
Ran tests locally.
=> refactor: revert restriction on branch protector

packages/branch-protector/package.json, packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/config.ts, packages/branch-protector/src/index.ts, packages/repocop/package.json, packages/repocop/src/config.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts
We have two systems sending messages to teams via Anghammarad.
This change tweaks the sent message to allow one to better identify the origin of the message:
- The message's `sourceSystem` is unique, and is comprised of the app name and stage
- The message's `subject` includes the GitHub team slug
We currently message every administering GitHub team of a repository. These GitHub teams may belong to the same P&E team, and therefore land in a single Chat thread.
For example:
These changes help to understand why the same message is appearing multiple times as the subjects will read:
- Repocop branch protection (for GitHub team A)
- Repocop branch protection (for GitHub team B)
- Repocop branch protection (for GitHub team C)
Rather than simply "Repocop branch protection" x3.
N/A.
=> refactor: Tweak the message metadata

package-lock.json, packages/best-practices/tsconfig.json, packages/branch-protector/src/index.ts, packages/branch-protector/src/model.ts, packages/branch-protector/tsconfig.json, packages/cdk/tsconfig.json, packages/cli/tsconfig.json, packages/common/package.json, packages/common/src/types.ts, packages/common/tsconfig.json, packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-02-branch_protection.test.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts, packages/repocop/tsconfig.json, tsconfig.json
Introduces a `common` package where shared code can live.
Having a place to share code:
- Allows for DRYness. For example the interactions with Anghammarad.
- Allows for better decoupling. For example, we can move database migrations out of RepoCop.
In this change, the `UpdateBranchProtectionEvent` interface is moved to this `common` package addressing the comment:
> The two interfaces should be kept in sync until we can share the interface.
The change can be verified via the compiler. If the compiler (a.k.a the build) is green, then we're good.
=> refactor: Share `UpdateBranchProtectionEvent` interface

packages/branch-protector/src/index.ts
Throws an error in `branch-protector` if the a repo doesn't have any branches. Also adds some console errors if branch protection fails, and slightly refactors the protect branch function to by DRYer.
We recently had problems when `branch-protector` came across a repo that was empty and thus didn't have any branches to protect  (`guardian/braze-diff-publisher`).
Tested on CODE with `braze-diff-publisher`. There were 5 other messages on the queue, and `branch-protector` ran successfully, didn't apply branch protections to the other repos (as it's CODE, expected), threw an error for `braze-diff-publisher`, and deleted all the messages off the queue including the failing one.
=> fix: throw error if a repo doesn't have any branches

packages/branch-protector/src/config.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts, packages/repocop/src/config.ts, scripts/setup.sh
Changes the name of the `QUEUE_URL` env var that is used by `branch-protector` to be specific to that app.
This makes it clear that this is a branch protector and allows for another queue url to be added for other apps in future.
Tested locally by running ./scripts/setup and then cloudquery and then repocop.
=> refactor: give branch protector queue url env var unique name

packages/branch-protector/src/index.ts, packages/repocop/src/index.ts
Bumping from 2 to 3 messages a day allows us to move through the backlog a little faster.
Repocop will add two messages to the backlog a day, but branch protector only runs four days a week. This means messages accumulate for three days over the weekend, and all get sent out at once. Let's work through the backlog at a more even pace
| Day of week | Messages Added | Messages read | Total in queue |
|-------------|----------------|---------------|----------------|
| Saturday  | 3 | 0 | 3 |
| Sunday    | 3 | 0 | 6 |
| Monday    | 3 | 0 | 9 |
| Tuesday   | 3 | 6 | 6 |
| Wednesday | 3 | 6 | 3 |
| Thursday  | 3 | 6 | 0 |
| Friday    | 3 | 3 | 0 |
=> don't bombard people with messages on a tuesday

ADR/03-data-accuracy.md
Adds an ADR for how we can verify our data accuracy. The proposal is to directly use the SDKs, rather than using AWS Resource Explorer, or AWS Config.
See https://github.com/guardian/recommendations/blob/main/architecture-decision-records.md.
I've looked at [implementing Resource Explorer](https://github.com/guardian/aws-account-setup/pull/133). That is, the opinion to not use it for this purpose is well informed.
=> docs: Add ADR for checking our data accuracy

packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-02-branch_protection.test.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts
- Moves functions specific to branch protector into its remediations file
- Renames some functions to make them clearer
This is in anticipation of some functions currently in branch protector being shared with the topics remediation.
=> refactor: move all branch protection functions into remediation file

packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.test.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.ts
Creates a list of unlabelled repos that could be interactives.
There are a few clues indicating that a repository might be an interactive
1. The repository was created from a list of template repositories the interactives team uses
2. We can detect artifacts from that repo in a particular bucket
Going through potentially hundreds of candidates and checking them all here would take too much time, so we're generating a list of repos to be submitted elsewhere for checks.
Unit tests have been added.
=> Generate list of potential interactives

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/config.test.ts
- bumps versions
- deletes most snapshot tests
- they need bumping
- inline snapshots are not automatically updated when using this version of jest. We've removed some of them for now as two is enough to verify that the functionality works, while being less annoying to developers
TODO: test on code
=> bump versions

packages/branch-protector/src/aws-requests.ts, packages/branch-protector/src/github-requests.ts, packages/branch-protector/src/index.ts
- Changes the 'delete message' log lines from `error` to `warn`
- Deletes a log line that is more or less duplicated later
- Changes the messaging of the branch protector function to be more appropriate.
Hopefully this will make understanding the logs a bit easier and make them less repetitive.
=> refactor: improve branch protector log messaging

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/policies.ts, packages/cdk/lib/service-catalogue.ts
We have been doubling up the IAM Policies we provide the ECS tasks.
In this repo, we have been saying:
- You can assume the role `arn:aws:iam::*:role/cloudquery-access`
- You can't do `dynamodb:GetItem`, `dynamodb:BatchGetItem`, etc.
However, these deny policies are already attached to the [`arn:aws:iam::*:role/cloudquery-access` role](https://github.com/guardian/aws-account-setup/blob/main/packages/cdk/lib/constructs/cloudquery-role.ts)!
Keeping IAM as simple as possible makes it easier to follow least privilege, IMO.
It confused me why the policy changes in https://github.com/guardian/service-catalogue/pull/364 wasn't enough, and why https://github.com/guardian/aws-account-setup/pull/118 was needed 😅.
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/ebcae6a9-6e51-45 …
=> refactor(cdk): Simplify IAM Policies

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
After https://github.com/guardian/service-catalogue/pull/456 this task is taking longer than 5 minutes to run, and therefore seeing overlapping runs. Run every 30 minutes instead in an attempt to avoid overlaps.
This is a regression. Once we enable singleton tasks, we can run at a more frequent schedule.
=> Run `OrgWideEc2` task every 30 minutes

.github/workflows/ci.yml, package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/interactive-monitor.ts, packages/cdk/lib/service-catalogue.ts, packages/interactive-monitor/README.md, packages/interactive-monitor/package.json, packages/interactive-monitor/src/index.ts, packages/interactive-monitor/tsconfig.json, scripts/ci.sh
Creates infrastructure for a lambda that will:
1. Listen to repocop for repositories that might be interactives
2. Run checks to verify whether or not a repository is an interactive
3. Apply the relevant label to the repository if required
For now though, it just says hello.
We aim to have as many repos as possible labelled with a valid production status, so we can prioritise it appropriately. New interactives pop up all the time, so we need an ongoing way to detect them.
Deployed to code.
=> Create interactive monitor infrastructure

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Skip `snyk_organization_provisions`
The API this table depends on does not allow service users from accessing it https://snyk.docs.apiary.io/#reference/organizations/manage-organization/list-pending-user-provisions . This causes a lot of errors in our logs that can throw off our alerts.
=> Skip `snyk_organization_provisions`

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/interactive-monitor.ts
SNS topics must have a unique name, so add the stage to differentiate CODE from PROD.
=> fix: Make SNS topic stage aware

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts, packages/repocop/src/config.ts, packages/repocop/src/query.ts
Allows more DB connections
Bumps the DB timeout
Provide additional memory to the repocop lambda
The lambda has gotten busier, and more queries are being made. We should bump the number of connections to avoid timeouts
Tested on PROD, repocop succeeds. Billed about the same number of GB seconds as before
=> Prevent lambda from timing out

packages/branch-protector/src/index.ts, packages/common/src/functions.ts, packages/common/src/types.ts, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-02-branch_protection.test.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts, packages/repocop/src/remediations/shared-utilities.test.ts, packages/repocop/src/remediations/shared-utilities.ts, packages/repocop/src/remediations/shared_functions.ts
- Moves various functions that are currently used by `branch-protector` into a shared file.
- Adds some types and objects to allow the right app and messaging to be passed into the shared messaging functions.
- Adds some scaffolding code so that the new topic monitor for 'production' tags is set up to message correctly.
- The shared utitilies can be used by the forthcoming `topic-monitoring-production` lambda that will automate the application of the `production` topic to repos, as it will follow a very similar messaging pattern to `branch-protector`.
Tested by running repocop locally using CODE database. Repocop ran successfully and added branch protection repos to the queue as before.
=> Refactor: Move shareable functions into shared file

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/ecs/task.ts
This should allow a task to identify itself using the [ECS task metadata endpoint](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v3.html#task-metadata-endpoint-v3-response).
This will be useful in implementing a singleton pattern for our tasks.
The updated snapshot should suffice.
=> feat: Add docker labels to each task

packages/common/src/functions.ts, packages/repocop/src/config.ts, packages/repocop/src/remediations/shared-utilities.ts
Changes the name of the scaffolding variables that refer to the upcoming implementation of the 'production' topic monitoring remediation in repocop.
Feedback on PR #466  indicated that it was not clear, due to the confusion over the multiple meanings of the word 'production' in this context.
Is it clearer?
=> refactor: rename production topic things for clarity

packages/cdk/lib/branch-protector.ts, packages/cdk/lib/service-catalogue.ts
Pulls out branch protector infrastructure into its own class
Declutter the main stack file
More of these classes will be created over the coming days
No difference in snapshots
=> create class for branch protector components

packages/cdk/lib/repocop.ts, packages/cdk/lib/service-catalogue.ts
Similar to #477 , this PR puts all repocop infrastructure into its own class
Better readability. This makes the separation between different parts of the service catalogue, and their interfaces (mostly SNS topics/SQS queues) clearer
Snapshots are identical
=> make repocop infrastructure its own class

packages/repocop/src/config.ts
The [shared `getEnvOrThrow` function](https://github.com/guardian/service-catalogue/blob/235ad1bdab2a61e15f02503afb86ab6aafacab24/packages/common/src/functions.ts#L22-L28) has the same implementation, so no need to redefine it.
N/A.
=> refactor(repocop): Use shared `getEnvOrThrow`

packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts, packages/repocop/src/rules/repository.ts
Currently, the function `getUnarchivedRepositories` is called twice, in the main repocop function and the remediation for branch protection. Soon, it would have been called 3 times with the addition of the production topic remediation.
With this PR, the function is called once and then passed into the functions that need it. 
This will hopefully save memory and time (and therefore money), and make things DRYer and more future-proof.
Tested locally using the CODE database with messaging on, and all worked as expected.
=> refactor: call getUnarchivedRepositories only once 

packages/interactive-monitor/src/config.ts, packages/interactive-monitor/src/index.ts, packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.test.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.ts
We are submitting the full repo name to github. We shouldn't be doing this
Also make repocop logging more useful
Passing in the full name into the name field means we are searching for the wrong repo and return a 404. ie `guardian/guardian%2Fcapi` rather than `guardian/capi`
Deployed to code, octokit is able to find the correct repo
=> make logs more useful, fix octokit request

.github/workflows/ci.yml, package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/data-audit.ts, packages/cdk/lib/service-catalogue.ts, packages/data-audit/package.json, packages/data-audit/src/config.ts, packages/data-audit/src/index.ts, packages/data-audit/src/run-locally.ts, packages/data-audit/tsconfig.json
Add the infrastructure for the data-audit lambda. The lambda currently prints the time, and will be later updated to track the accuracy of our data.
In this initial step, we're testing:
- Can we build the lambda?
- Can we deploy the lambda?
- Can we see the lambda's logs in Central ELK?
See https://github.com/guardian/service-catalogue/blob/main/ADR/03-data-accuracy.md.
- The lambda built and [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/a3789524-fe0d-4256-9b85-d18f9073eb65) successfully
- The logs appear in [Central ELK](https://logs.gutools.co.uk/s/devx/goto/98a08e80-8795-11ee-a34c-11e7b53d0c58)
=> feat(data-audit): Initialise data-audit lambda

packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
- Exclude non production/documentation repos from requiring branch protection.
- Repos with no branches do not need protection
- Test the above changes
It's unreasonable to expect every hackday project, for example, to have branch protection, and previously our code did not line up with our [exemptions](https://github.com/guardian/service-catalogue/blob/main/packages/best-practices/best-practices.md)
Tests pass.
Branch protection increases from 14% to 98%
=> fix branch protection rule

.github/workflows/ci.yml
Upgrade to [v3 of guardian/actions-riff-raff](https://github.com/guardian/actions-riff-raff/releases/tag/v3.0.0) to get PR commenting 🎉.
Its easier and faster to deploy to CODE.
There should be a comment on this PR...
=> chore(deps): Update `guardian/actions-riff-raff` to v3

package-lock.json, packages/branch-protector/src/index.ts, packages/branch-protector/src/run-locally.ts, packages/cli/package.json, packages/cli/src/aws.ts, packages/common/package.json, packages/common/src/aws.ts, packages/common/src/functions.ts, packages/repocop/package.json, packages/repocop/src/config.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.ts
Unifies how we initialise AWS clients for simplification, and to stay DRY. In this change we use a profile when running locally, and fallback to the default chain otherwise.
Simpler code!
- Ran each lambda locally
- [Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/e68731a9-5c44-4737-b4bc-00639afa4910) and executed each lambda successfully.
=> refactor: Initialise AWS clients in a consistent way

.github/workflows/ci.yml
Grants permission for CI to run as part of a merge queue
Without this, PRs will hang forever
The only way to test this PR is to merge it
=> Allow CI to run on merge queue

package-lock.json, packages/branch-protector/src/aws-requests.ts, packages/common/src/functions.ts, packages/repocop/package.json, packages/repocop/src/index.ts, packages/repocop/src/remediations/repository-02-branch_protection.ts
Makes the CTA for branch protector messages clearer.
Only send one message per repo per team
Feedback gathered from recipients was that the messages from branch protector are too noisy, and that people don't understand what is happening to their repos, or that the CTAs were clickable
CI passing should be sufficient
=> Simplify branch protector notifications

package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/data-audit.ts, packages/data-audit/package.json, packages/data-audit/src/index.ts
Requires #504.
Check that the number of accounts in the database is the same as the number of accounts in the AWS Organisation. At the moment we're just logging the result. We'll alarm/alert in the near future.
We want Service Catalogue to collect information for all our AWS accounts.
- Ran locally
- [Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/c6b3495a-2b40-45e8-8c16-413de5d13115), manually invoked the lambda, and observed the [logs](https://logs.gutools.co.uk/s/devx/goto/d1e852f0-8965-11ee-9308-f99e8aa2f574)
=> feat(data-audit): Check the number of accounts we have data for

package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/data-audit.ts, packages/cdk/lib/service-catalogue.ts, packages/common/package.json, packages/common/src/database.ts, packages/data-audit/package.json, packages/data-audit/src/config.ts, packages/data-audit/src/index.ts, packages/repocop/package.json, packages/repocop/src/config.ts, scripts/ci.sh, sql/dbuser.sql
Updates the data-audit lambda to perform a basic query against the database. There's a bit of wiring involved:
- Moving the database connection string logic into the `common` package
- Placing the lambda in the VPC, and adjust it's security groups to allow database connection
- Creation of a database user[^1]
- Include prisma in the lambda artifact
As such, it'll be easier to review this change [commit by commit](https://github.com/guardian/service-catalogue/pull/504/commits).
The data-audit lambda will compare what is in the database to what AWS thinks, e.g. number of S3 buckets. This change begins that process.
- Ran data-audit locally and observed the log line "There are X AWS accounts in the database"
- [Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/e4be404c-fa2d-496 …
=> feat(data-audit): Query the database

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Downgrades snyk from 3.1.11 to 3.1.10
All versions of the Snyk plugin > 3.1.10 are a cloudquery premium feature. While we work out what to do about this, let's stick to a free version
Able to gather snyk data locally again
=> downgrade snyk version

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
We are collecting the date for aws reservation purposes.
The tables were there already but empty, so this is a trial to get data into them
To use for the aws reservation dashboard
=> Collect data for aws reservition as seperate job into tables aws_cost_explorer_*

packages/common/src/database.ts, packages/data-audit/src/config.ts, packages/data-audit/src/index.ts, packages/repocop/src/config.ts, packages/repocop/src/index.ts
Reduce code repetition by instantiating a prisma client in a shared way. This is a no-op change.
=> refactor: Share function to create a prisma client

packages/repocop/script/migrate.sh
Prisma code has been moved to common, this PR updates the migration script to reflect this.
I haven't moved it to the common folder as repocop populates basically all the non cloudquery tables created by the migration, so I think it makes sense to keep it here for the time being
The script was failing due to the prisma package having been moved
DEV migrations succeed.
TODO: test CODE migration
=> Fix migration script

packages/common/prisma/migrations/20231124095700_cq_last_synced/migration.sql
Replace our cq_last_synced view with a cq_last_synced() function. This function does much the same thing but figures out which tables it needs to query at runtime, instead of it being hardcoded at creation.
Because the old `cq_last_synced` view had hardcoded references to all Cloudquery tables in its DDL it caused Cloudquery to not be able to update table schemas due to Cascade issues. Since this new function doesn't directly reference any Cloudquery tables it hopefully shouldn't impact anything.
Deployed this function and ran `SELECT * FROM cq_last_synced()`
Also verified that we're now able to drop Cloudquery tables again without having cascade issues
=> Use a function instead of a view for collecting last sync times

.github/workflows/ci.yml
Configure GHA to have exactly one build per branch at a time. If a new one appears, all others are cancelled.
Now that we're using merge queues, we want to be sure the build from the last item in the queue is also the last one to be deployed via CD.
This PR triggered two builds in quick succession:
1. The change
2. The change, plus a rebase against `main`
The build from the [first](https://github.com/guardian/service-catalogue/actions/runs/6980653518) was cancelled:
=> ci: Avoid race condition across builds

packages/common/prisma/migrations/20231124095700_cq_last_synced/migration.sql
Fix the amibious column names error when doing a Prisma migrate.
I was a little bit too quick on the previous PR and missed some crucial changes!
=> Fix cq_last_synced() function having ambigious names

package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/interactive-monitor.ts, packages/interactive-monitor/package.json, packages/interactive-monitor/src/config.ts, packages/interactive-monitor/src/index.ts, packages/interactive-monitor/src/run-locally.ts
All interactives are deployed to an S3 bucket. Some of them have a config.json file with a `path` field. Those paths correspond to s3 prefixes. By searching the s3 bucket for those prefixes, we can tell if a repository corresponds to a deployed interactive, and label it accordingly
To reduce the number of unlabelled repositories across the department
Local testing against known interactives and non-interactives
Runs on CODE and produces the expected output
=> Match repos to deployed interactives in S3

package.json, packages/best-practices/src/definitions.ts, packages/best-practices/src/index.ts, packages/cdk/package.json, packages/common/package.json, packages/repocop/src/index.ts
RepoCop isn't compiling due to a duplicate import. This wasn't caught in CI as we were only running `tsc` in a workspace if they defined a `typecheck` script (`npm run typecheck --workspaces --if-present`).
When you try to run RepoCop locally on `main` we get:
```console
➜ npm -w repocop start
> repocop@1.0.0 start
> APP=repocop ts-node src/run-locally.ts
/Users/akash_askoolum/code/service-catalogue/node_modules/ts-node/src/index.ts:859
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:3:2 - error TS2300: Duplicate identifier 'PrismaClient'.
3  PrismaClient,
~~~~~~~~~~~~
src/index.ts:4:2 - error TS2300: Duplicate identifier 'PrismaClient'.
4  PrismaClient,
~~~~~~~~~~~~
at createTSError …
```
=> fix: Resolve compilation errors

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Every AWS task that runs in multiple accounts needs to be able to list the accounts. This permission is provided via the IAM Policy `organizations:List*`.
Add this permission to the `RemainingAwsData` task.
This fixes a regression from #447. In #447 this task lost the [ReadOnlyAccess managed policy](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/ReadOnlyAccess.html) which was providing `organizations:List*` permissions.
[Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/fb19d1e1-ff83-4e87-a173-efb5f5787c85), manually ran the `RemainingAwsData` task[^1], and observed data coming in ([logs](https://logs.gutools.co.uk/s/devx/goto/51393c50-8d11-11ee-9ace-b9608309e74f))!
[^1]: `npm -w cli start run-task -- --stage CODE --name RemainingAwsData`
=> fix(cloudquery): Allow `RemainingAwsData` task to list orgs

scripts/setup.sh
Removes reference to branch protector queue
Branch protector does not exist any more
=> remove reference to nonexistent queue

packages/repocop/src/remediations/repository-06-topic-monitor-interactive.ts
Only send one message if we are not running on prod
We don't need to run the lambda 10 times to verify it works. Also, if we want to test the interactive monitor, the easiest thing to do would be to submit the name of the repo directly to SNS.
We're also getting rate limited by AWS on prod so let's lower the number of repos we send for now
=> send fewer messages on non-prod stages

packages/interactive-monitor/src/index.ts, packages/repocop/src/config.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.ts
interactives with a `config.json` deploy into a different prefix than those with a `cfg/s3.json`. We know what these prefixes are so can search only in the correct parts of the bucket for artifacts.
Halving the number of requests we are making to S3 means we can look at more of them at one time
Local execution still works
=> interactive-monitor: Make fewer requests to S3 per repo

packages/interactive-monitor/package.json, packages/interactive-monitor/src/index.ts, packages/interactive-monitor/src/run-locally.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.test.ts, packages/repocop/src/remediations/repository-06-topic-monitor-interactive.ts
Previously, we were sending 10 individual messages to SNS at once. Now, we are creating a JSON list of x repositories, and submitting it in one invocation.
Fewer lambda invocations means better performance overall. Theoretically we could send more in one go, but leaving it at 10 for now to keep us under AWS API's abuse limits, which seem to be triggered after about 10 repos have been checked. We can make the interactive monitor a bit smarter about which checks it runs in a later PR.
Deployed to CODE and verified the messages are processed correctly
=> Bunch potential interactives into one lambda invocation

packages/common/src/functions.ts, packages/common/src/types.ts, packages/interactive-monitor/src/index.ts, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/remediations/repository-06-topic-monitor-production.test.ts, packages/repocop/src/remediations/repository-06-topic-monitor-production.ts
Adds the functionality to apply the `production` topic to unarchived repos that
- have a `PROD` or `INFRA` stack in AWS (excluding Developer Playground)
- don't have a `production` or `interactive` topic
- have a 'contactable owner' - ie whether we can message the teams who the repos belong to. 
Once the topic has been applied, the repo owners will be notified via Anghammarad.
This will help us to ensure that we know about all repos in production for security reasons.
Tested the functions locally where posible, but will need to test in PROD to see if the topics are successfully applied and messaging is sent out.
=> Apply production topic and message teams

package-lock.json, package.json, packages/best-practices/package.json, packages/cdk/cdk.json, packages/cdk/lib/cloudquery/ecs/versions.ts, packages/cdk/package.json, packages/data-audit/package.json, packages/interactive-monitor/package.json, packages/interactive-monitor/src/run-locally.ts, packages/repocop/package.json, packages/repocop/src/run-locally.ts, tsconfig.json
As commented in #532, `ts-node`, ESM and Node 20 is [tricky](https://github.com/TypeStrong/ts-node/issues/1997). This change swaps `ts-node` for `tsx` across the entire repository.
A lot of NPM packages are being moved to ESM only, so being able to continue to use these libraries makes it easier to keep up to date.
Everything still runs locally, and CI is happy.
=> chore(deps): Swap `ts-node` for `tsx`

packages/repocop/src/config.ts
Increases the number of repos sent to interactive monitor
We are making fewer s3 requests per repo, so can check more repos
=> Catch more interactives

packages/cdk/lib/service-catalogue.ts, packages/cli/src/aws.ts, packages/common/src/logs.test.ts, packages/common/src/logs.ts
Updates the alarm description for the RepoCop lambda, adding a link to the logs within Central ELK. This is aimed at making it easier to triage alarms.
Here is an example of the current alarm received over email:
Kibana links are tricky to craft. This change refactors #532, moving the link building into a function. I've confirmed that the link is still valid by starting an ECS task via our CLI tool.
cc @guardian/devx-reliability as maybe [GuCDK's `defaultDescription`](https://github.com/search?q=repo%3Aguardian%2Fcdk%20defaultDescription&type=code) should include a link to Central ELK?
=> feat(cdk): Add link to logs within RepoCop alarms

packages/repocop/src/remediations/repository-06-topic-monitor-production.ts
- Improves the spacing between sentences in the Anghammarad message for the production topic monitor.
- Slight rewording to hopefully make it clearer.
What I thought might be separate lines were actually just concatenated together without spacing.
It will only affect future repos found to be in production, so their team(s) will see the improved messaging.
=> refactor: improve the messaging for production topic monitor

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Restrict repocop runs to weekdays only.
Currently, repocop could potentially be sending messages out to teams every day. Messages sent on the weekend are more likely to be missed, and don't contribute to a healthy work-life balance. Let's avoid this!
=> chore(repocop): only run repocop on weekdays

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Increase Snyk task memory from 512MB to 1GB
Job is getting terminated due to OOM in PROD
Deployed to CODE and ran
=> Increase Snyk job memory to 1GB to deal with OOM issues

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
This task is being killed by AWS with the reason:
```
OurOFMemoryError: Container killed due to memory usage
```
Increase the resources, to resolve. From 500MB RAM, to 16GB. From 0.25 vCPU, to 8 vCPU.
Note, the new values were selected somewhat arbitrarily!
We deployed to PROD, and ran the task successfully.
=> Increase resources for `GithubTeams` task 

packages/interactive-monitor/src/js-parser.test.ts
Add some annotations to help the linter understand we know what we're doing, and therefore reduce noise in the build.
Observe CI - the annotations appearing on `main` have been removed on this branch.
<details><summary>Annotations on main</summary>
<p>
</p>
</details>
<details><summary>Annotations on this branch</summary>
<p>
</p>
</details>
=> chore: Reduce build time noise from linter

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/ecs/task.ts
Enable GOMEMLIMIT, adding a soft limit of how much memory a task can use before Go aggressively garbage collects.
Currently configured to be 80% of the allocated memory for a task to provide:
- Memory headroom for tasks running in sidecars
- Time for Go to GC before AWS terminates the task due to OOM.
Inspired by https://weaviate.io/blog/gomemlimit-a-game-changer-for-high-memory-applications
This might help prevent future OOM issues. The downside to this is that a task will run slower when it exceeds 80% memory usage due to the GC having to be ran aggressively.
Ran in code
=> Enable GOMEMLIMIT, adding a soft limit of how much memory a task can use

packages/repocop/src/remediations/repository-06-topic-monitor-interactive.ts, packages/repocop/src/remediations/repository-06-topic-monitor-production.test.ts, packages/repocop/src/remediations/repository-06-topic-monitor-production.ts, packages/repocop/src/remediations/shared-utilities.test.ts, packages/repocop/src/remediations/shared-utilities.ts
- Renames `removeGuardian` function to `removeRepoOwner` to make it more generic, reflecting how the owner is referred to in the rest of the codebase. The owner is currently always 'guardian'.
- Moves the function to shared utilities file from the production topic monitor.
- Reuses the function in the interactive topic monitor.
To make the codebase DRYer.
Local tests ran successfully.
=> refactor: Share function to remove owner from repo name

packages/repocop/src/index.ts, packages/repocop/src/remediations/topics/topic-monitor-interactive.test.ts, packages/repocop/src/remediations/topics/topic-monitor-interactive.ts, packages/repocop/src/remediations/topics/topic-monitor-production.test.ts, packages/repocop/src/remediations/topics/topic-monitor-production.ts
- Renames the topic monitor files to remove 'repository-06' from them.
- Moves the files into their own 'topics' folder.
To make the filenames shorter and thus easier to read and to keep related files together.
Ran local tests successfully.
=> refactor: rename topic monitor files and move to own folder

packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/remediations/branch-protector/branch-protection.ts, packages/repocop/src/remediations/topics/topic-monitor-production.test.ts, packages/repocop/src/remediations/topics/topic-monitor-production.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts, packages/repocop/src/types.ts
Creates a new type, `Repository`, which is a subset of `github_repositories`, and stops fields being nullable if they are never actually null in reality
- Doing the conversion from `T | undefined => T` at the query stage means much less null checking later on
- Using a type that's smaller than the original makes it clear which fields we actually care about, and reduces memory usage in the lambda.
Deployed to CODE, running the lambda produces the expected results, consistent with previous outputs
=> shrink the repo type, and make always-there fields required

packages/repocop/src/remediations/topics/topic-monitor-production.ts
- Pulls the creation of the Anghammarad message for `topic-monitor'-production` into a separate function.
- Console logs out the contents of the message.
- Moves the logic to perform the topic addition and messaging according to the stage closer to their calls, to allow for easier logging.
This will allow us to preview the messaging on CODE so we can see if it is formatted correctly. 
Tested on CODE.
=> feat: log out Anghammarad  message if not in PROD

packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
Creates a method that
1. Checks if vulnerability tracking is required for a repo
2. Retrieves the languages used by that repo
3. Looks for the repo on Snyk
3a. Checks that all languages used by the repo are supported by Snyk
4. If not on Snyk, checks that all languages used by the repo are supported by dependabot.
We expect all production repositories to have dependency tracking enabled, either via Snyk or Dependabot. This feature allows us to track if teams are complying with this requirement. Teams that are not using more niche languages such as Scala, do not 
All new and old tests pass. Deployed to CODE, logs look happy.
=> Demonstrate we are able to detect if a repo has sufficient vulnerability tracking.

packages/repocop/src/index.ts, packages/repocop/src/rules/repository.ts
There's a lot going on in the main file. This PR moves a lot of it out to the `repository` file, and creates a function for evaluating experimental repocop features
Readability. The main method is less cluttered, and its easy to tell which features are and aren't experimental
=> Move functions out of index. Create a parent function for experimental features

packages/cdk/lib/cloudquery/ecs/cluster.ts, packages/common/prisma/migrations/20231205105200_monitoring/migration.sql, packages/common/prisma/schema.prisma
Drops the old (well, older) cq_sync_time() function and replace it with a new function which is aware of exactly which tables to check and what their frequencies should be.
The list of tables and their frequencies is current spread out across a few different dashboards and alerts in Grafana and its a bit of a pain in the arse to make sure they're all using the same query.
Part of this PR creates a new `monitoring.cloudquery_table_frequency` table, it has hardcoded values at the moment, but I'm hoping that at some point we'll be able to populate this table at runtime when a task starts. Maybe by running a little script at the start of a task which takes the `tables` config and appends it to this table.
Ran on CODE
=> Add a new schema which holds tables and functions dedicated to monitoring cloudquery status

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Previously, repocop was running at 3pm, change this to 10:30
- Early enough that CloudQuery is still reasonably in sync
- Early enough that if something goes wrong, we'll have found out by standup.
- Late enough that most people should have started working by then, and will see the notifications
=> Run repocop at 10:30

packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/remediations/branch-protector/branch-protection.ts
Temporarily stop branch protector from running until we have a solution that allows us to publish libraries
It's interfering with library releases.
=> Ditch branch protector temporarily

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
This allows us to collect data about the RDS and Backup services once per day, instead of once per week.
Similar to https://github.com/guardian/service-catalogue/pull/428.
Next quarter we have an OKR related to RDS backups and it would be nice to see daily updates for this data.
I'm also hoping that the Backup tables will be useful for ensuring that https://github.com/guardian/aws-backup [continues working as expected](https://trello.com/c/Z3Ds2ENF/2337-spike-how-can-we-ensure-that-devx-backup-continues-working). 
As we are copying an existing pattern, I think the snapshot testing is sufficient here, but please let me know if you'd like me to check anything else.
=> Add decidated CloudQuery sources for RDS and Backup

README.md, docs/updating-cloudquery.md
An attempt to make the README more terse by:
- Cross-linking to other docs
- Not enumerating each app within the repository
=> docs: Update the README

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Bump `GitHubIssuesTask`, `OrgWideCloudFormation`, and `OrgWideInspectorTask`
It looks like these 3 tasks are running out of memory
(Ignore the EC2, I'm not sure why thats failing just yet)
=> Bump memory usage of various failing tasks to 1024MB

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
We're seeing some deployments failing in Riff-Raff with the ASG reporting:
> Instance stayed in Pending state too long.
Contact AWS Support has led us to believe this is an issue in AWS's data centres.
It would be helpful to understand how many applications are experiencing this symptom. If it's the majority, maybe we need to escalate.
The ASG activity has this information. Sadly, CloudQuery doesn't have this table. I've started to build https://github.com/guardian/aws-asg-monitor to collect the information outside of Service Catalogue, however [CloudTrail](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html) should also have it, which CloudQuery can collect!
This change collects all CloudQuery tables. There is going to be a lot of data here, so run the …
=> feat(cloudquery): Collect AWS CloudTrail data

packages/common/prisma/migrations/20231220170100_drop_old_tables/migration.sql
We previously populated this table when we integrated riffraff into CloudQuery, but we've since stopped using it as it was quite large and resource intensive.
Its not referenced in our prisma schema so I guess I could have just dropped it without a migration? But I suppose a PR preserves history.
=> Drop unused `riffraff_deploy_logs` table.

.github/dependabot.yml
Use [grouping](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) to bump AWS SDK libraries together, and Prisma libraries together. This should result in fewer PRs.
For example, these five open PRs would become two:
=> chore(deps): Configure Dependabot groups

packages/cdk/lib/repocop.ts
Increases the number of repos we check for interactives from 20 to 40
Testing a larger subsection of repos means that we find new interactives faster.
Manually increased the interactive count to 40 on PROD, and ran the lambda to verify that the memory/timeouts/API could handle it.
n.b. the lambda now takes 8 seconds to run, rather than 5.
=> Double interactive monitor capacity

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/cluster.ts, packages/cdk/lib/cloudquery/task.ts
Sets the `CLOUDQUERY_API_KEY` environment variable to [authenticate with CloudQuery](https://docs.cloudquery.io/docs/deployment/generate-api-key). By authenticating, we provide CloudQuery with more telemetry data, which they can use to understand our usage rates.
Being authenticated also enables us to use premium plugins, such as the latest Snyk version.
By itself, this should be a no-op change. Paired with #623, we're able to update the Snyk plugin.
=> feat(cloudquery): Authenticate with CloudQuery

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Updates the Snyk CloudQuery source plugin to the latest version. This version is listed as a premium plugin, and requires login, which is done in #622.
AFAICT there aren't any new tables in [this version](https://hub.cloudquery.io/plugins/source/cloudquery/snyk/v4.0.2/versions?search=snyk).
See:
- https://github.com/guardian/service-catalogue/pull/510
- https://github.com/cloudquery/cloudquery/pull/15191
Deployed to CODE, ran the Snyk task, and observed the logs showing data is being collected.
=> chore: Update CloudQuery Snyk plugin version

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/cluster.ts, packages/cdk/lib/cloudquery/task.ts
Remove ECS task monitoring via SNS (added in #224) as it doesn't appear to be working (no emails have been received), and we have implemented alternative mechanisms via Grafana.
=> Remove ECS task monitoring via SNS

packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/cloudquery/task.ts
This is an attempt to make `task.ts` a bit smaller/easier to reason about.
N/A. This is a no-op, as demonstrated by the CDK snapshots not changing.
=> refactor(cdk): Move image references to own file

packages/cdk/lib/cloudquery/cluster.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/cloudquery/task.ts
Following from #625, some (rather pedantic) refactors for correctness/consistency/simplicity:
- Reuse the Fire Lens log driver
- Update some doc strings to reference CloudQuery not Service Catalogue
- Rename `extraSecurityGroups` to `additionalSecurityGroups` to match the naming of `additionalCommands`
- Remove some [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming))
N/A. This is a no-op, as demonstrated by the CDK snapshots not changing.
=> refactor(cdk): Updates for consistency/simplicity

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/cloudquery/versions.ts
Collect languages for production repos
Provides more granular information about dependabot/snyk coverage
Runs on CODE.
The state of this plugin's authentication is VERY temporary, running with a short lived token with very tightly scoped credentials tied to a user. We plan to migrate this to use a GitHub app, and eventually remove the need to use a GH token at all when running locally
=> Set up cloudquery source to pull languages for github repositories

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts
Bumps AWS Source plugin to 23.3.1
This fixes a bug with `aws_backup_vault_recovery_points` throwing errors which causes are alerts to go off.
https://github.com/cloudquery/cloudquery/pull/15781
Ran `OrgWideEc2` task on CODE to verify cloudquery can still fetch the plugin as it was moved to the Cloudquery registry instead of Github.
=> Bump AWS Source plugin to 23.3.1

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts
Source the Galaxies plugin from the `github` registry.
Cloudquery started defaulting to their private registry in CQ CLI 4.0 https://github.com/cloudquery/cloudquery/releases/tag/cli-v4.0.0 which we updated to in https://github.com/guardian/service-catalogue/commit/60d08178a9073b9d0ea240ef13749c21c6b84776
=> Fetch Galaxies and Snyk-Full-Project plugin from Github

.github/dependabot.yml, package-lock.json, package.json
Being explicit is better than being implicit! Previously, eslint was being brought in via a peerDependency of `@guardian/eslint-config-typescript`.
Also configures Dependabot to update eslint and prettier tooling together, for fewer PRs.
=> chore(deps): Add explicit dependency on eslint

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Gives OrgWideEc2 1GB of memory (up from 512MB)
This task was ocassionally running out of memory in PROD
=> Give OrgWideEc2 task 1GB of memory

packages/cloudquery/dev-config/cloudquery.yaml, packages/cloudquery/docker-compose.yaml, scripts/setup.sh
CloudQuery's github plugin now uses the CODE auth
This is part of the work to simplify project setup. Eventually, all GitHub plugins on CODE will use GitHub app auth so the user does not have to mess around setting up PATs with the right permisisons. Next steps are:
- Move github-languages plugin to GitHub app only auth
- Use snyk equivalent instead of requiring users to get their own tokens
The snyk work will significantly reduce the chance of accidents, as snyk API tokens are always scoped to the permissions of the user, which in the case of DevX engineers, is quite broad.
Tested locally and verified that we are able to collect data
**NB:** users will need to delete their `.env.local` and rerun the setup script in order to run CloudQuery locally. Make sure to retain a copy your GitHub …
=> Authenticate CQ github plugin with GitHub app locally

packages/common/prisma/migrations/20240102121400_aws_ec2_images_timestamp/migration.sql, packages/common/prisma/schema.prisma
Alter "creation_date" and "deprecation_time" columns to TIMESTAMPS instead of TEXT and re-creates dependant views and functions.
These columns were changed to TIMESTAMP in https://github.com/cloudquery/cloudquery/pull/15378 . Our CloudQuery EC2 task is currently failing as it can't update the underlying table for these views and functions.
Ran on CODE.
=> Alter "creation_date" and "deprecation_time" columns to TIMESTAMPS instead of TEXT and re-creates dependant views and functions

packages/common/prisma/migrations/20240103120510_add_vulnerability_tracking_column/migration.sql, packages/common/prisma/schema.prisma, packages/repocop/src/remediations/branch-protector/branch-protection.test.ts, packages/repocop/src/remediations/topics/topic-monitor-interactive.test.ts, packages/repocop/src/rules/repository.ts
Co-authored by @tjsilver @NovemberTang @akash1810 @chrislomaxjones.
This PR primarily makes two schema changes:
1. Add the `github_languages` model to the Prisma schema file. This was done by running `npm -w cli start migrate -- --stage DEV`, which in turn runs [`prisma db pull`](https://www.prisma.io/docs/orm/reference/prisma-cli-reference#db-pull). Generating a new Prisma client then allows us to be begin consuming this model from within the application itself.
2. Add a boolean `vulnerability_tracking` column to the `repocop_github_repository_rules` table/Prisma model, and generate an associated migration (note this migration also contains a `CREATE TABLE github_languages ...` statement for the previous step). Since this field is non-nullable we currently hardcode any required usages as …
=> feat: Adjust Prisma schema for Github languages

packages/cloudquery/dev-config/cloudquery.yaml, packages/cloudquery/docker-compose.yaml, scripts/setup.sh
As part of the setup script, retrieve a `CLOUDQUERY_API_KEY` from AWS Secrets Manager, and append it to the `.env.local` file.`docker-compose.yml` is changed to make it available within the CloudQuery container itself.
As a small drive-by change, I've also added `registry: github`  to plugins that produced the following errors:
```
ERR exiting with error error="failed to download plugin source guardian/galaxies@v1.1.0: plugin version not found. If you're trying to use a private plugin you'll need to run `cloudquery login` first. Hint: make sure to use the latest plugin version from hub.cloudquery.io or to keep using an outdated version add `registry: github` to your configuration" module=cli
```
Some of the CloudQuery plugins used for local development require a `CLOUDQUERY_API_KEY` to …
=> Retrieve CloudQuery API key for local development

scripts/setup.sh
This is a follow up from #642
Pulls the CODE snyk credentials from secrets manager during repo setup
The user no longer needs to set up their own snyk token.
The token provided has the correctly scoped permissions. Snyk user tokens are given the same level of permissions as the respective users, and this cannot be changed. Using the service account token closes this security loophole
Verified that local setup succeeds
=> Do not require snyk token for setup

packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
Make dependency tracking validation a feature of repocop, and remove it from the experiments section.
As of #639 , we are able to pull repo languages directly from cloudquery, meaning we don't have to make a request to octokit for every one. As a result, we are able to quickly evaluate whether or not a repository's languages are supported by our respective vulnerability trackers. This means we can count the number of repos that are not correctly integrated with a tracker, and fix this issue.
~TODO: Deploy to CODE and check via grafana.~
This PR has been deployed to CODE and the vulnerability tracking field is now being correctly set in the repocop table.
=> Use Github Languages table to determine dependency tracking 

packages/repocop/src/rules/repository.ts
Make logs more useful by telling the user which platform the repo has been evaluated against, and which languages are missing.
Easier to tell **why** a repo has failed the vulnerbaility tracking check
All tests still passed, deployed to CODE and observed expected result
`<REPO> contains the following languages not supported by <PLATFORM>:  [ '<LANGUAGE>' ]`
=> Make vulnerability tracker logging more useful

package-lock.json, packages/repocop/package.json, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/remediations/snyk-integrator/create-pull-request.ts, packages/repocop/src/remediations/snyk-integrator/snyk-integrator.test.ts, packages/repocop/src/remediations/snyk-integrator/snyk-integrator.ts, packages/repocop/src/rules/repository.ts
Add the ability to create pull requests against repositories within the Guardian organisation:
- This change is currently introduced as an experimental feature, and is hardcoded to create a pull request against [test-repocop-prs](https://github.com/guardian/test-repocop-prs/pulls) with a hardcoded set of languages.
- It uses logic introduced in #656 to generate the PR title/body.
- It uses the [`octokit-create-pull-request`](https://www.npmjs.com/package/octokit-plugin-create-pull-request) package (thanks for pointer @NovemberTang) to handle the creation of the pull request itself. I've wrapped this in a small wrapper, so we could drop this dependency in the future with minimal refactoring of the caller. This package can be used as an Octokit plugin, although this seemed more fiddly than …
=> Create test PRs for Snyk remediation

packages/repocop/src/remediations/snyk-integrator/snyk-integrator.test.ts, packages/repocop/src/remediations/snyk-integrator/snyk-integrator.ts, packages/repocop/src/rules/repository.ts
Add options `PIP_REQUIREMENTS_FILES` and `PIPFILES` to the Snyk inputs. 
We also modify the workflow so that it is run when commits are pushed to the generated branch containing the snyk.yml file.
These options are required to properly run the Snyk workflow when a repository contains Python dependencies.
See the updated tests.
=> Fix Snyk Python options

jest.config.js, package-lock.json, package.json
Use `esbuild` (via [`esbuild-jest`](https://github.com/aelbore/esbuild-jest)) to transform our Jest tests.
Should speed up our testing (especially when combined with #666).
On my laptop, here's the output of running `time npm run test` on `main` at the time of this PR:
```
npm run test  37.39s user 4.24s system 161% cpu 25.810 total
```
And here it is on this branch
```
npm run test  4.69s user 0.89s system 101% cpu 5.481 total
```
=> Use esbuild to transpile Jest tests

package-lock.json, packages/dev-environment/package.json, scripts/ci.sh
When using NPM workspaces, there is not a built in way of running the same command across multiple workspaces in parallel, so we've created a way to do this in bash.
Make CI faster
Cuts CI time by about 15 seconds
=> Run tests in parallel

packages/repocop/src/query.test.ts, packages/repocop/src/query.ts
Checks that tables are populated before executing repocop
Having an empty table means that our data is innacurate, which means potentially unwanted actions could occur. For example, if it looks like no snyk projects exist, we could start raising PRs against lots of repos that are already correctly integrated. The lambda should halt and fail if data is missing.
Tests have been added to verify the expected behaviour.
Deployed and tested, logs have enough information to deduce which table failed.
```
{"errorType":"Error","errorMessage":"Expected a non-empty array. Source table may be empty.",
"stack":["Error: Expected a non-empty array for object","    at toNonEmptyArray
(/var/task/index.js:844551:11)","    at getSnykProjects (/var/task/index.js:844617:10)",
"    at async Runtime.main [as …
```
=> Fail repocop if a required table is empty

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/cluster.ts, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/cloudquery/task.ts, packages/cdk/lib/cloudquery/versions.ts
The NS1 source plugin (https://github.com/guardian/cq-source-ns1) is written in TypeScript, and [distributed as a Docker image](https://docs.cloudquery.io/docs/developers/creating-new-plugin/javascript-source#releasing-and-deploying-your-plugin).
Previous attempts (see https://github.com/guardian/service-catalogue/pull/337) to use this plugin failed, because ECS containers cannot interact with Docker (see https://github.com/aws/containers-roadmap/issues/1356).
In this change, we run the NS1 source plugin directly, in its own container, resulting in a GRPC server on `localhost:7777`. We then configure the CloudQuery sync container to connect to this endpoint.
Collecting this data provides more information about our running services. For example, we can identify which services use Fastly, …
=> feat: Collect DNS records from NS1

packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
While we can't check snyk project tags directly, we can use the presence of a snyk workflow file as an indicator that a repo is integrated with snyk.
Adds a helper function to the tests. Rather than having to declare all empty arrays up front, we use a function that defaults them to empty unless otherwise specified. This means if we add or remove a field from `evaluateOneRepo`, there's far fewer changes we need to make to keep the tests happy.
Removes the non-empty check from snyk_projects while we have the snyk workflow check in place, as the latter is a workaround for the former being empty.
To allow us to continue to measure and make progress on our OKR while work to bring back the table continues, albeit with slightly lowered precision
Added new unit test to verify new behaviour. …
=> Check for existence of snyk workflow file

packages/snyk-integrator/src/remediations/snyk-integrator/snyk-integrator.test.ts, packages/snyk-integrator/src/remediations/snyk-integrator/snyk-integrator.ts
Adds more detailed instructions to the PR body. Removes gh cli step.
The yaml generated includes a field that will run on every push to the feature branch. This is because a user cannot run an action manually if it has not been kicked off by github at least once. Now we are running on every push, we don't need to instruct users to run the action via the CLI.
Python is not used in every repo, so make clear that this part is optional. In future, maybe we could only display that checklist item if we detect python in the repo?
Unit tests verify expected behaviour
=> update PR body

package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/repocop.ts, packages/common/package.json, packages/common/src/functions.test.ts, packages/common/src/functions.ts, packages/interactive-monitor/src/index.ts, packages/snyk-integrator/src/index.ts, packages/snyk-integrator/src/run-locally.ts
`snyk-integrator` is triggered in response SNS events. It tries to unwrap those events and generate PRs based on their contents.
`repocop` does not currently send notifications to snyk integrator via this queue. This will be set up via a separate PR to keep this one manageable.
So repocop can (eventually) tell snyk integrator which repos require PRs to be raised.
Tested on CODE
=> Allow snyk integrator lambda to take input

package-lock.json, package.json
Update `@guardian/eslint-config-typescript` from 9.0.1 to 9.0.2 to get some performance improvements. See https://github.com/guardian/csnx/pull/1083.
This shaves a few seconds off the build time. The latest build of `main` took [1m47s](https://github.com/guardian/service-catalogue/actions/runs/7542308573). The build of this branch took [1m33s](https://github.com/guardian/service-catalogue/actions/runs/7542377709). See also https://github.com/guardian/service-catalogue/pull/685#issuecomment-1893433003.
=> chore(deps): Update `@guardian/eslint-config-typescript` from 9.0.1 to 9.0.2

packages/dev-environment/dev-config/grafana-datasource.yaml, packages/dev-environment/docker-compose.yaml, packages/dev-environment/steampipe/Dockerfile
Runs [Steampipe](https://steampipe.io/) locally with the GitHub plugin. The data is also queryable in the local Grafana instance; we can run queries like this:
```sql
select name
from github_my_repository
limit 10;
```
Note: The GitHub plugin only supports GitHub Personal Access Tokens. We're using the token from the `~/.gu/service-catalogue/.env.local` file created during setup.
<details><summary>Example of querying Steampipe with Grafana</summary>
<p>
</p>
</details> 
Exploring real-time data querying.
=> Add Steampipe container and use it in Grafana

.github/workflows/ecs-publish.yml
We want to use the image that we build locally for our dev-environment in ECS as it configures the required plugins and volumes for running Steampipe.
=> Add new workflow to publish our custom Steampipe container to GHCR

package-lock.json, packages/common/src/functions.ts, packages/snyk-integrator/package.json, packages/snyk-integrator/src/index.ts, packages/snyk-integrator/src/projects-graphql.test.ts, packages/snyk-integrator/src/projects-graphql.ts, packages/snyk-integrator/src/types.ts
In PROD, once a PR has been raised, we should add it to the [project board](https://github.com/orgs/guardian/projects/110/views/1)
Allows us to keep track of the PRs we've raised, so we know who we might need to follow up with
Deployed to PROD and verified that the PRs are raised and added to the project board
=> Add PRs to project board

packages/repocop/src/remediations/snyk-integrator/send-to-sns.ts
Previously, repocop would try to pass an undefined value to SNS, which would cause a failure. Now, we are checking to make sure the value exists first.
Prevent repocop failures
=> Only trigger snyk integrator if a repo exists

package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/cloudquery/schedule.test.ts, packages/cdk/lib/cloudquery/schedule.ts, packages/cdk/lib/cloudquery/task.ts, packages/cdk/package.json, packages/common/prisma/migrations/20240109110500_add_pk_cloudquery_table_frequency/migration.sql, packages/common/prisma/schema.prisma
Adds a sidecar container to our CloudQuery tasks which handles running an INSERT query on our DB to record the frequency of the CloudQuery task being executed. This frequency is derived from our Schedule specified in CDK.
We currently have to manually keep the `cloudquery_table_frequency` up to date which can lead to some tables being missed. By automating this process we can make this table more reliable.
Truncated `cloudquery_table_frequency` in CODE and ran the Galaxies task, observed the creation of new records in `cloudquery_table_frequency`
=> Automatically record table frequency

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts, packages/common/prisma/migrations/20240119145931_remove_emr_types/migration.sql, packages/common/prisma/schema.prisma
This table has ~5 million rows, and isn't especially useful.
It lists the instance types we could use, and their specification. It is fairly repetitive across all regions and AWS accounts.
As we don't use AWS EMR, skip the table.
See https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-supported-instance-types.html.
Note: We'll need to [apply the migration](https://github.com/guardian/service-catalogue/blob/main/docs/database-migrations.md) manually.
<details><summary>Exactly how many rows?</summary>
<p>
```sql
SELECT relname, reltuples AS estimate 
FROM pg_class 
WHERE relname IN (
SELECT TABLE_NAME
FROM information_schema.tables
WHERE TABLE_NAME not like 'pg_%' AND table_schema in ('public')
) 
ORDER BY estimate DESC
limit 5;
```
| relname | estimate |
|--------|--------|
| …
=> fix(cloudquery): Skip the `aws_emr_supported_instance_types` table

packages/snyk-integrator/src/index.ts, packages/snyk-integrator/src/snyk-integrator/snyk-integrator.ts
Thanks to @michaelwmcnamara for his invaluable feedback on the PR body
While testing this feature on some repos belonging to other DevX streams, we received feedback that the instructions were not as clear as they could be. This PR aims to rectify that, by using more specific language, and clarifying terms where required.
We now also log the PR title and body on CODE and DEV
To make it easier for teams to follow the instructions
- PR body still formats as expected
- Verified that the Python checklist item shows up when Python is listed as a language, and vice versa.
=> Improve PR instructions

packages/common/src/string.test.ts, packages/common/src/string.ts, packages/repocop/src/remediations/topics/topic-monitor-production.test.ts, packages/repocop/src/remediations/topics/topic-monitor-production.ts
Create a function that utilises [tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) to replicate Scala's `stripMargin`.
Easier to read, and create long strings?
See added tests.
=> refactor: Make it easier to create multi-line strings 

packages/repocop/package.json, packages/repocop/src/index.ts, packages/repocop/src/rules/repository.ts, packages/repocop/src/types.ts
Creates a function that, given a repo, will return the first page of dependabot alerts for that repo.
So we know if a repository has dependabot vulnerabilities that need addressing.
Run locally using known vulnerable repos, returns expected output. Run on CODE, verified output, and that error handling works as expected
Sometimes the request fails because dependabot scanning is not enabled for the repo. We should look into whether or not this is opt-in or opt-out, and whether it's appropriate/possible to switch it on at the org level for production repos, similar to branch protection rulesets.
=> Get critical dependabot vulnerabilities for some production repos

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/task.ts
Mark Postgres container as non-essential
Last week I merged https://github.com/guardian/service-catalogue/pull/653 which added a new Postgres container to tasks, it turns out that when this container completes ECS kills all the containers as this one container is marked as "essential"
Annoyingly at the same time I purged the `cloudquery_table_frequency` table as the new postgres container was meant to populate it automatically, meaning that we stopped getting alerted to data sync issues.
=> Fixes Postgres container making every other container exit

packages/common/src/functions.test.ts, packages/common/src/functions.ts, packages/snyk-integrator/src/projects-graphql.ts
- Removes the custom graphQL auth function, as it's just duplicating regular octokit logic (less code means less untested code!)
- Add unit tests to untested parts of the common package
This package in particular is used by several parts of the service catalogue, and it's important that its behaviour is well-understood, -documented and -tested
`npm run test -w common -- --coverage`
nb: I think that using jest rather than ts-jest has has confused the coverage tool, as some of the details about which lines are covered/uncovered don't add up (any advice on how to make this more accurate is welcome) - but the general idea is that coverage (especially of non-async code) has increased significantly.
File          | % Stmts | % Branch | % Funcs | % Lines | …
=> Increase test coverage in common package

packages/snyk-integrator/src/index.ts, packages/snyk-integrator/src/snyk-integrator/pull-requests.ts, packages/snyk-integrator/src/snyk-integrator/snyk-integrator.test.ts, packages/snyk-integrator/src/snyk-integrator/snyk-integrator.ts
This PR contains two main changes:
1. Check if a PR already exists for Snyk integration on a given repo, before creating the integration PR. We check for PR existence by searching the PRs for a given branch name.
2. The branch name is now derived from the set of languages passed to the snyk-integrator lambda. We take the languages into account here so that if we raise a Snyk integration PR and at a later date a new language is added to the repo (that requires integration), we'll go ahead and raise another PR.
Prevent the same Snyk integration PR being raised multiple times between the `snyk.yml` file actually being merged. For example: https://github.com/guardian/devx-backup-monitoring/pull/14 https://github.com/guardian/devx-backup-monitoring/pull/16.
I tested this locally against …
=> Prevent Snyk integrator raising duplicate pull requests

packages/repocop/src/languages.ts
Ignore a couple more languages
They variants of languages that we already handle
CI passes
Before: 55 untracked repos
After: 49 untracked repos
=> ignore a couple more languages

packages/repocop/src/index.ts, packages/repocop/src/remediations/snyk-integrator/send-to-sns.ts
Removes the DevX filter that was only sending internal repos to the Snyk Integrator
We are ready to release to the wider department
CI passes
=> Remove DevX filter from snyk integrator

packages/snyk-integrator/src/snyk-integrator/pull-requests.ts
Check that the type of parameters we use to retrieve pull requests conforms to the set of allowed parameters.
Combining listing pull requests with pagination seems to lose us some type safety. Adding in this type should avoid allowing us to pass in parameters that do not exist.
=> refactor: Properly type parameters for fetching PRs

packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/service-catalogue.test.ts, packages/cdk/lib/service-catalogue.ts, packages/cdk/lib/steampipe/service.ts
We can now call Steampipe using Grafana
Add Steampipe as a AWS ECS Service. This service runs 24/7.
We're currently using the smallest possible ECS instance type (0.25 vCPU, 0.5GB) which costs about 2.7$, the most expensive part is probably the NLB costing ~16$
We want to explore realtime alternatives to CloudQuery
It has been running in CODE for a number of days
=> Add Steampipe as a AWS ECS Service running 24/7

packages/repocop/src/index.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts, packages/repocop/src/types.ts, packages/repocop/src/utils.test.ts, packages/repocop/src/utils.ts
- Pull all the first page of critical alerts from dependabot (oldest first)
- If a repo has old, unresolved critical or high vulnerabilities, log it.
95% of dependabot alerts are not relevant as they pertain to old, decomissioned, or otherwise non-production repos. This feature will allow us to highlight to developers which repositories with vulnerabilities need addressing, focusing the noisy output from GitHub
Deployed to CODE and saw expected behaviour in the logs
Currently we do not collect dependabot data via CloudQuery as the job takes over 48 hours to complete (potentially much longer). We could probably collect it in a more timely way if we were able to provide the job with a list of repos we cared about. I've spoken to @guardian/devx-operations about this, and we have added this …
=> Log if a repo contains a vulnerability older than it should

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
This'll enable us to identify who is a Fastly admins, making it easier to, for example, identify who to ask to create an automation token.
=> feat(fastly): Collect Fastly user information

packages/cdk/bin/cdk.ts, packages/cdk/package.json
It is sometimes useful to see the delta between the current branch and the CODE CloudFormation stack.
This change allows us to run:
```bash
npm -w cdk run diff:code
```
to yield something like this:
```console
Stack ServiceCatalogue-CODE (deploy-CODE-service-catalogue)
Creating a change set, this may take a while...
IAM Policy Changes
┌───┬─────────────────────────────────────┬────────────────────────────────────────┐
│   │ Resource                            │ Managed Policy ARN                     │
├───┼─────────────────────────────────────┼────────────────────────────────────────┤
│ - │ ${steampipeTaskDefinition/TaskRole} │ arn:aws:iam::aws:policy/ReadOnlyAccess │
└───┴─────────────────────────────────────┴────────────────────────────────────────┘
(NOTE: There may be security-related …
```
=> feat(cdk): Enable local CFN stack diffing

package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/repocop.ts, packages/cdk/lib/service-catalogue.ts, packages/repocop/package.json, packages/repocop/src/config.ts, packages/repocop/src/index.ts
Allows repocop to read the contents of the snyk secret so it can retrieve the data that used to populate the `snyk_projects` table. Logs the group ID to the console to demonstrate it was retrieved successfully.
So we can retrieve Snyk Projects data using repocop
Local execution works.
Verified group ID is logged on CODE
=> Allow repocop to access the snyk secret

scripts/setup.sh
Whilst the SSM Parameter `/INFRA/deploy/services-api/galaxies-bucket-name` exists, it's value is incorrect! Use the [same SSM Parameter used in CODE/PROD](https://github.com/guardian/service-catalogue/blob/b26cd77d01cc2caaf6d824929e8986ed824f2471/packages/cdk/lib/cloudquery/index.ts#L393-L401) to locate the Galaxies S3 bucket.
- Collect Galaxies data locally on `main`
- Observe the database tables being empty
- Collect Galaxies data on this branch
- Observe the database tables having data
=> fix: Use correct SSM parameter for Galaxies bucket

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/steampipe/service.ts
Runs Steampipe on ARM
Steampipe publishes an ARM image (and so do we). ARM is 20% cheaper and better for the environment!
Will run on CODE.
=> Run Steampie on ARM

packages/repocop/src/languages.ts
Adds the Swift language to those supported by the Snyk [dependency submission action](https://github.com/guardian/.github/blob/main/.github/workflows/sbt-node-snyk.yml). The action works with both Cocoapods and Swift Package Manager files without any modifications required to the action itself.
We can check more repos, now that [Snyk supports Swift](https://docs.snyk.io/scan-using-snyk/supported-languages-and-frameworks/swift-and-objective-c).
I tested against the [test-repocop-prs](https://github.com/guardian/test-repocop-prs/actions) repo and a [fork of ios-app](https://github.com/guardian/test-repocop-prs/actions).
=> feat: add Swift to the Snyk dependency submission action

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/steampipe/service.ts, packages/dev-environment/steampipe/Dockerfile
We added the steampipe aws plugin and gave a policy read-only
We want to query aws tables
=> Add aws plugin and get credentials via policy arn

packages/repocop/src/languages.ts
Adds the Kotlin language to those supported by the Snyk [dependency submission action](https://github.com/guardian/.github/blob/main/.github/workflows/sbt-node-snyk.yml). The action works with both Maven (pom.xml) and Gradle (build.gradle.kts)  files without any modifications required to the action itself.
We can check more repos, now that [Snyk supports Kotlin](https://docs.snyk.io/scan-using-snyk/supported-languages-and-frameworks/java-and-kotlin#open-source-and-licensing).
I tested against a Maven `pom.xml` manifest in [test-repocop-prs](https://github.com/guardian/test-repocop-prs/actions/runs/7628229105/job/20778767374) and the action is already being used for Gradle files by [android-news-app](https://github.com/guardian/android-news-app/blob/main/.github/workflows/snyk.yml), [Snyk …
=> feat: add Kotlin to the Snyk action

.github/workflows/ci.yml, packages/common/prisma/views/public/aws_accounts.sql, packages/common/prisma/views/public/view_old_ec2_instances.sql, packages/common/prisma/views/public/view_repo_ownership.sql, packages/common/prisma/views/public/view_running_instances.sql, packages/common/prisma/views/public/view_snyk_project_tags.sql
Ensure the [directory created by Prisma for views](https://www.prisma.io/docs/orm/prisma-schema/data-model/views#the-views-directory) is tracked in VCS.
This directory gets re-created whenever we perform a [migration](https://github.com/guardian/service-catalogue/blob/main/docs/database-migrations.md), so add it for ease[^1], and check in CI that it's up-to-date.
The content has cross-over with the [`migrations` directory](https://github.com/search?q=repo%3Aguardian%2Fservice-catalogue+path%3Apackages%2Fcommon%2Fprisma%2Fmigrations%2F*view*%2Fmigration.sql&type=code), so it might turn out that we can `.gitignore` it...
With untracked files, CI fails with this output:
[^1]: Ease, as in I can `git add .` on a feature branch again without fear of adding unrelated files 😄
=> ci(prisma): Ensure views directory is added

packages/repocop/src/languages.ts
Declares some more languages as supported
Confirmed Mako with @philmcmahon 
They are just extensions of already existing languages
=> Declare Svelte, Mako as supported

packages/repocop/src/languages.ts
Adds the Ruby language to those supported by the Snyk [dependency submission action](https://github.com/guardian/.github/blob/main/.github/workflows/sbt-node-snyk.yml). 
We can check more repos, as [Snyk supports Ruby](https://docs.snyk.io/scan-using-snyk/supported-languages-and-frameworks/ruby).
I tested against [the fork of the ios-app](https://github.com/guardian/snyk-test-ios-live/actions/runs/7641883008/job/20820203079) and the Gemfile was scanned successfully [Snyk results](https://app.snyk.io/org/guardian-test/project/91dcb40c-e94e-4147-94cc-1c0a245f0fd0/history/adf48955-625b-4c4d-8847-21f00c32543f).
=> feat: add Ruby to Snyk integrator

packages/repocop/src/languages.ts
Classifies coffeescript as a dependabot supported language
It uses NPM dependencies.
This will allow us to classify some repos more accurately
CI passes
=> classify coffeescript as a dependabot supported language

packages/repocop/src/remediations/snyk-integrator/send-to-sns.test.ts, packages/repocop/src/remediations/snyk-integrator/send-to-sns.ts
Filter out all of the _ignored languages_ before we send an event to the Snyk integrator lambda. If a Snyk integrator event is left with zero languages, it will now also be filtered out.
To prevent additional languages being sent to the Snyk integrator which it cannot action. This currently causes confusion on [some PRs](https://github.com/guardian/etag-caching/pull/38) *.
(*) This might not be super important in the future if we refactor the way we name branches.
I've added two test cases, and existing tests pass.
=> Don't send ignored languages to the Snyk integrator

packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts, packages/repocop/src/types.ts
Calculates whether or not a repository has Snyk vulnerabilities older than the cut-off date
So teams can be better informed about their vulnerability obligations
Unit tests verify expected behaviour. Deploying to CODE, we can see that it is logging when it finds repos with out of date vulnerabilities.
Example:
```
INFO	Dependabot - <REDACTED>: has 19 alerts that need addressing
INFO	Snyk - <REDACTED>: has 5 issues that need addressing
```
Combine alerts from both formats using a common format
=> Count up number of alerts from Snyk

packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts
We are able to pull the tags for each project from the Snyk API, meaning we have a more reliable way of telling whether or not a repo is on snyk or not. This means we don't have to use the proxy signal of whether or not it has a workflow file with a particular name.
Better accuracy
CI passes
There's about a 10% difference in the number of untracked repos, which is about what I was expecting to see
=> Assess vulnerability tracker integration using results from snyk API

packages/repocop/src/languages.ts
Moves Ruby and Rust into common supported languages, as they are [now supported by Dependabot](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph) as well as Snyk.
To be more accurate!
There is a dependency graph on the [self-assessment tool](https://github.com/guardian/self-assessment/network/dependencies) which lists Rust dependencies, and I enabled dependency graph on [the fork of the ios app](https://github.com/guardian/snyk-test-ios-live/network/dependencies) and this lists the Ruby dependencies.
=> refactor: move Ruby and Rust into common supported languages

.env, .github/workflows/ecs-publish.yml, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/images.ts, packages/dev-environment/docker-compose.yaml, packages/dev-environment/steampipe/Dockerfile
Move the Steampipe plugin versions to the `.env` file, for consistency, but also to later make them available as env vars in other contexts.
Ran the workflow to build and push the image to GitHub Packages - https://github.com/guardian/service-catalogue/actions/runs/7742341313.
=> refactor(steampipe): Move plugin versions to `.env` file

packages/snyk-integrator/src/index.ts, packages/snyk-integrator/src/pull-requests.test.ts, packages/snyk-integrator/src/pull-requests.ts, packages/snyk-integrator/src/snyk-integrator.test.ts, packages/snyk-integrator/src/snyk-integrator.ts
Simplify how we check for the existence of a Snyk integration PR, by assuming that the **gu-snyk-integrator Github app will only have a single open PR on any repository**.
Making this assumption allows us to revert to the old branch naming scheme (removed in #715), independent of the languages. Choosing a random branch name prevents naming collisions, and we lookup the existence of a PR by its author instead.
Simplify the logic for looking up Snyk integration PRs.
Also provides a foundation for longer-term work we may wish to do, such as updating the existing PR.
Tested locally (using the `PROD` stage) by running twice against [test-repocop-prs](https://github.com/guardian/test-repocop-prs). Note the first time the PR is created, and the second time it's skipped as it already exists: …
=> One Snyk pull request per repo

.github/workflows/ecs-publish.yml, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/service-catalogue.ts, packages/cdk/lib/steampipe/service.ts, packages/dev-environment/docker-compose.yaml, packages/dev-environment/steampipe/Dockerfile, packages/dev-environment/steampipe/generate-aws-plugin-config
> [!Note]
> Easiest to review [commit by commit](https://github.com/guardian/service-catalogue/pull/759/commits).
Configure Steampipe to [access all the accounts](https://hub.steampipe.io/plugins/turbot/aws#multi-account-connections) in the AWS organisation by generating a config file with an entry per AWS account returned by:
```bash
aws organizations list-accounts
```
> [!Important]
> This branch requires static (permanent) IAM credentials to run locally.
It's worth noting that to run this locally, AWS credentials vended by Janus DEV is not enough, as it does not allow `sts:AssumeRole`. Therefore, one currently has to create some static credentials for an IAM User. This user should have an inline policy as below, and set to the profile `service-catalogue-DEV`:
```json
{
"Version": …
```
=> feat(steampipe): Configure for multi-AWS account

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/steampipe/service.ts
Add the `Name` tag to Steampipe containers. See also https://github.com/guardian/service-catalogue/pull/253.
=> fix(steampipe): Add `Name` tag to containers

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts
Updates the versions of CloudQuery CLI, source, and destination plugins to the latest available. Also updates the comments to point to the CloudQuery hub page, rather than GitHub releases.
We've seen a couple of errors collecting the `aws_backup_vault_recovery_points` table. Updating as a first attempt to resolve this - I've not read the release notes...
=> chore(cloudquery): Update CloudQuery versions to latest available

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/repocop.ts, packages/repocop/src/query.ts
By default, CDK's log level is set to `INFO`. Despite this, we were still getting `DEBUG` level logs showing up in Cloudwatch etc. Log filtering only works if your logs are JSON formatted (thanks @jacobwinch for the tip), so this PR does that, and adjusts the level of a few less interesting log lines.
Deployed to `CODE` and verified only `INFO` and higher logs are getting through
=> Get log filtering in repocop working

packages/repocop/src/index.ts, packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts, packages/repocop/src/types.ts
1. Adds an `isPatched` field to tell us if a vulnerability can be resolved through a direct or indirect version bump
2. Deduplicate vulnerabilities based on CVE, keeping whichever alert had the highest severity
3. Return a list of vulnerabilities along with the evaluation results for each repo.
4. Only return runtime dependencies from Dependabot
1. To give teams an idea of how much work is involved in mitigating a vulnerability, allowing them to prioritise their remediations
2. Make the vulnerability count more accurate, so we aren't double-counting vulnerabilities across two platforms
3. So we can keep track of vulnerabilities on a departmental level
4. Picking only runtime dependencies brings us in line with our existing Snyk policy. It also makes the number of vulnerabilities less …
=> Gather more information about vulnerabilities, and deduplicate

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/config.ts
Since [v5 of the CLI](https://github.com/cloudquery/cloudquery/releases/tag/cli-v5.0.0), `concurrency` defined at the top level unrecognised. Move it to the plugin's `spec` configuration.
=> fix(cloudquery): Correct `concurrency` configuration

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/task.ts, packages/cli/src/aws.ts
Adds `propogateTags` to our ECS Task definition
This tells EventBridge to add the tags from the task definition to the task instance when it schedules one. This allows us to track costs better.
=> Add tags prop and proprogateTags prop to ECS task definition

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/task.ts
The [`cloudquery-access` role](https://github.com/guardian/aws-account-setup/blob/cfa18ed8b94b56223498f9227b0f32a1a7ea70d2/packages/cdk/lib/constructs/cloudquery-role.ts) is currently assumable by any role in the DeployTools account.
By having a deterministic IAM Role name, we can restrict the principal on the `cloudquery-access` role to tighten access.
This will be done as it's own PR, in the aws-account-setup repository - https://github.com/guardian/aws-account-setup/pull/166.
We can also set the [external id](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html) to further tighten access. Will do this in a follow-up PR.
The `cloudquery-access` role deliberately breaks least responsibility; access should be tightly controlled.
[Deployed to …
=> fix(iam): Create an explicit role w/deterministic name

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts
The commented issue has been resolved in https://github.com/guardian/deploy-tools-platform/pull/733 [^1].
[^1]: Riff-Raff's RDS is using the [same CA certificate as Service Catalogue](https://github.com/guardian/service-catalogue/blob/59cc777a6daa8927c5b7a83566c2a1904771fd10/packages/cdk/lib/service-catalogue.ts#L111-L127).
=> fix: Connect to Riff-Raff's Postgres with full ssl verification

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Updates the `minute` field to be `0` instead of `*`. This caused:
1. At 10AM the `DeployToolsListOrgs` task would be launched every minute until 11AM
2. Our stale data alerting incorrectly flagged the table as `DAILY` (despite it actually being `MONTHLY`) as the time between 1 invocation and the next was 1 minute.
=> Don't run DeployToolsListOrgs every minute at the start of a month

.github/workflows/ci.yml
Co-authored-by: @AshCorr
Upgrade [guardian/actions-riff-raff](https://github.com/guardian/actions-riff-raff) to [v4](https://github.com/guardian/actions-riff-raff/releases/tag/v4).
This allows us to remove the [aws-configure-credentials](https://github.com/aws-actions/configure-aws-credentials) step from the earlier part of the workflow.
Builds of the service-catalogue are still picked up by Riff-Raff.
=> Update actions-riff-raff to version 4

packages/repocop/src/rules/repository.test.ts, packages/repocop/src/rules/repository.ts, packages/repocop/src/vulnerability-digest.test.ts, packages/repocop/src/vulnerability-digest.ts
Send messages to teams twice a month letting them know about historic vulnerabilities in their estate.
Give teams an indication of how long a vulnerability has existed in their codebase.
Since enabling dependency graphs on our repos, Dependabot has flagged new vulnerabilities against our repos. Teams don't have a clear way of viewing and prioritising this information, so we have created a way for them to see the most urgent vulnerabilities that need addressing.
Unit tests have been added to make sure that the date logic works, and the anghammarad messages have been tested extensively in CODE. The first messages are due to go out next week, but it may be worth deploying a version without a date condition to test the first run.
It's worth noting that this is _not_ intended as a way for …
=> Send vulnerability messages to teams

packages/repocop/src/rules/repository.ts, packages/repocop/src/vulnerability-digest.ts
Sending out 15 messages only results a couple of teams with vulnerable production repos. let's widen our test group a little, especially as we don't know for sure that all those teams have anghammarad mappings. Let's double this number
Snyk API responses sometimes wrongly indicate that a vulnerability is not patchable. This is something we should address with Snyk directly, but for now, let's make the negative case more ambiguous.
Deployed to CODE, confirmed we are now sending twice as many messages as before
=> send notifications more teams, modify wording

packages/repocop/src/index.ts, packages/repocop/src/rules/repository.ts
Co-authored-by @NovemberTang 
Temporarily removes Dependabot alerts from Repocop vulnerability monitoring.
Currently we are creating vulnerability digests alerting on critical vulnerabilities from dev dependencies. This will create a lot of unnecessary work for teams that receive the digests. It seems like some vulnerabilities have been mis-classified by Dependabot as 'runtime' when they are not, and transitive (as well as possibly direct) dev dependencies are not being ignored as they should be. 
Once we have resolved these issues then this work can be reverted.
Tested on CODE and the vulnerability digests were created with only Snyk vulnerabilities.
=> Refactor: temporarily remove Dependabot alerts from vulnerability monitoring 

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/data-audit.ts
The data-audit lambda assumes the `cloudquery-access` role. This role's principal has been narrowed to a pattern. Update the IAM Role used by the lambda to match this pattern, so that it can assume the role.
See https://github.com/guardian/aws-account-setup/pull/166.
=> refactor(data-audit): Explicitly name the IAM Role

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
This job was set to run on the 1st of January every year, Instead of the 1st of every month. This was causing our our table out of sync alarm to trigger.
Before
After
=> Run DeployToolsListOrgs once a month, instead of once a year

packages/repocop/src/index.ts, packages/repocop/src/rules/repository.ts, packages/repocop/src/vulnerability-digest.test.ts, packages/repocop/src/vulnerability-digest.ts
Send all teams with vulnerable repos notifications.
No negative feedback received about current message system, so roll out to department, and move it out of the test feature function
=> Notify all teams about old vulnerabilities

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/index.ts
Bumps the Github plugin to v8.0.0
The newest version of the Github plugin [supports syncing SBOM tables](https://github.com/cloudquery/cloudquery/pull/16796) from Github!
Ran locally
=> Bump Clouquery Github plugin to v8

packages/repocop/src/evaluation/repository.ts, packages/repocop/src/index.ts
Bring back dependabot alerts
We stopped collecting dependabot alerts while we were deciding what to do about yarn dependencies, as github does not differentiate between development and runtime deps. We decided to take no action, and encourage people to move away from yarn, in line with departmental recommendations.
CI passes.
deploy to CODE and sense check the number of vulnerabilities
=> bring back dependabot vulnerabilities

packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Always log digests
So we can see what messages have been sent to teams on the day digests are sent
CI passes
=> log digests no matter what

docs/database-migrations.md, packages/common/prisma/migrations/20240229142634_add_team_slug_to_view_repo_ownership/migration.sql, packages/common/prisma/schema.prisma, packages/common/prisma/views/public/view_repo_ownership.sql, packages/repocop/src/remediation/branch-protector/branch-protection.test.ts, packages/repocop/src/remediation/shared-utilities.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
This PR adds a new Prisma migration that drops and recreates the `view_repo_ownership` view.
The migration contains some breaking schema changes:
- Add column `github_team_slug`.
- Add column `short_repo_name`.
- Drop column `repo_name`.
- Renamed the `full_name` column to `full_repo_name`.
As some of these changes are breaking, this required changes in the Recocop application code, which are included as part of this PR.
> [!NOTE]
> Applying the migration without deploying the new Repocop application will break Repocop (as field names have changed). This shouldn't be a problem in reality, as Repocop runs on a schedule such that we should be able to migrate the database and deploy the new application between invocations.
Making the team slug available in this view should ease sending …
=> Add Github team slug to `view_repo_ownership`

scripts/setup.sh
Co-authored-by: @NovemberTang 
Adds a step to fetch the Snyk API key ARN and add this as an environment variable in the setup script.
This is required to successfuly run  Repocop locally, since the environment variable was added to Repocop in #733.
Ran the setup script after this change and observed repocop running without error.
A future piece of work is required to use only one SNYK env var.
=> fix: add Snyk API key ARN to setup script

.github/workflows/ci.yml, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/repocop.ts, scripts/ci.sh
This change adds additional CDK to create some new resources:
- A lambda that will run the dependency-graph-integrator script.
- A SNS topic from which Repocop can publish messages, and a lambda subscription so the dependency graph integrator lambda is triggered with these messages.
- In `PROD`/`TEST`, a secret for Github app credentials.
It also modifies our CI script and Riff Raff content directories to add a new lambda artifact, which we're already producing.
So that we can begin running the `dependency-graph-integrator` in CODE and PROD stages, as opposed to just locally.
CI passes and the snapshot appears to match what I'd roughly expect. I've also deployed the CFN and lambda changes to CODE, which passed successfully and created the new resources in AWS.
I tested the new CODE SNS …
=> Provision infra for the Dependency Graph Integrator

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Changes `DeployToolsListOrgs` from running once a month to running daily. 
This job is currently throwing off our out of sync alerting. Due to a bug in our alert behaviour we expect every AWS table to be at minimum refreshing once a week.
This job isn't particularly expensive, it only takes ~30s to run and it syncs less than 100 rows.
=> Run DeployToolsListOrgs daily

package.json, tsconfig.json
Specify the `noEmit` TypeScript compiler option in the root tsconfig. This means we can also remove it from the `typecheck` package script.
If I mistakenly run `npm run tsc` it won't emit JS files across the entire repository.
CI passes, and running `npm run typecheck` doesn't emit JS locally.
=> Add `noEmit` option to the root TypeScript config

.github/workflows/ci.yml, packages/cdk/bin/cdk.ts, scripts/ci.sh
This PR adds a new artifact to the RiffRaff deployment, which gets directly copied into the account dist bucket. To achieve this, a change is made to the Riff Raff file (synthed in the CDK, requiring a change to `bin/cdk.ts`).
The steps are:
1. The CI script produces an additional `prisma.zip` file containing the contents of the Prisma directory.
2. This is added as a content directory to Riff-Raff, so it gets synced to the Riff Raff artifacts bucket.
3. When a deploy is triggered, this `prisma.zip` file is copied from the RiffRaff artifacts bucket to account dist bucket.
Subsequent work will then focus on running a migration within a task, triggered by a `prisma.zip` being PUT into the bucket.
This is the first PR for a series of steps that will allow us to run automated Prisma …
=> Upload Prisma migrations to S3 bucket on deploy

package-lock.json, package.json, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/index.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Adds https://github.com/sindresorhus/eslint-plugin-unicorn to the linting rules, and configure the linter to force usage of `.flatMap` as a terser version of mapping then flattening.
`eslint-plugin-unicorn` has a number of rules, which we might want to enable in future, and/or add it to the [departmental eslint configuration](https://github.com/guardian/csnx/tree/main/libs/%40guardian/eslint-config).
Terser code.
N/A.
=> Add linting rule to prefer `.flatMap(...)` over `.map(...).flat()`

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Swaps package name and repo name
Feedback has indicated that people would find it more useful to have the repo name first, then severity, then package name
Unit tests have been updated to reflect the change
=> change ordering of information in vulnerability digests

.github/workflows/prisma-migrate-image.yml, containers/prisma-migrate/Dockerfile, containers/prisma-migrate/run-prisma-migrate.sh
This PR adds a `Dockerfile` (*) for building an image that can perform Prisma migrations. This image uses a `run-prisma-migrate.sh` script to fetch the Prisma directory from S3, which will be placed there by a successful deploy on Riff-Raff (see https://github.com/guardian/service-catalogue/pull/852), before performing the `prisma migrate deploy` command against the database specified by the environment variables set.
At the moment, each image gets pushed to GHCR tagged with the full commit sha, e.g.
```
ghcr.io/guardian/service-catalogue/prisma-migrate:sha-42771e43c3130daa7476d9e5b77455001533c557
```
This will be manually referenced within the CDK, when the task definition that uses this image is defined.
(*) Heavily inspired by the Steampipe CI step that used to be part of this repo. …
=> Build an image to perform Prisma migrations

packages/dev-environment/dev-config/cloudquery.yaml, packages/dev-environment/script/start
Copy github data directly from the cloudquery DB.
The copy function uses wildcarding, meaning we're collecting a couple more tables than we were before, but only about 5 or 6. Until we're more specific about which tables we want, we should be careful when introspecting the database.
For now, the only data we are not gathering is AWS data. These tables tend to me much larger, and theres like 600 of them. This means we need to be really careful about what data we pull, and the wildcarding approach used so far might be a bit too greedy, and will be refined in the next PR
- Save money on CQ rows
- Faster startup times
Tables show up in DEV environment
=> copy github data directly from DB

packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts, packages/repocop/src/types.ts, packages/repocop/src/utils.test.ts
Remove the need to hand-roll a `RepocopVulnerability` type. Derive one from the `repocop_vulnerabilities` interface provided by prisma
Maintainability. This is part of a larger piece of work to simplify vulnerability calculations in repocop
All unit tests still pass, local execution of repocop produces the same output as CODE
=> Stop hand-rolling RepocopVulnerability type

packages/snyk-integrator/src/snyk-integrator.test.ts, packages/snyk-integrator/src/snyk-integrator.ts
Allows PRs to be raised for repos that contain Kotlin or Ruby
Our action supports these languages
=> allow snyk integrator to support kotlin and ruby

docs/database-migrations.md, packages/cdk/lib/cloudquery/images.ts
Update the documentation on Prisma migrations to mention the new automated method of applying them via CD.
Also, add a TSDoc comment explaining how the `prisma-migrate` image is versioned.
Make usage clearer.
This is just documentation changes.
=> Update documentation on migrations

packages/dev-environment/dev-config/cloudquery.yaml, packages/dev-environment/script/start
This PR is more easily digestible in [split mode](https://github.com/guardian/service-catalogue/pull/876/files?diff=split&w=1)
- Check for the `libpq` package before attempting to install it. Less noisy output, quicker execution if `libpq` is already installed
- Split up `copy` into two methods. One for wildcarding, one for pulling single tables. Better performance.
- Perform db migration before copying data over, so views show up from the beginning. Improves QOL - there is no need to pull data twice.
- Parallelise `copy` operations. Improves setup performance
- Copy some AWS tables over via `copy`. Much faster than waiting for cloudquery, grabs data from multiple accounts, no sync fees.
This script runs in about a minute: `npm run start -w dev-environment  7.59s user 5.29s system 21% cpu …
=> Sync some AWS tables using pg_dump

packages/dev-environment/script/start
Reduces the error messages we see from the dev environment start script as we are not setting up redundant schemas. ty to @akash1810 for the tip!
This means getting rid of wildcard_copy and being explicit about exactly which tables we want, because if the wildcard causes us to dump a table we don't have a schema for, it will fail.
Also, we are now using a parallel for loop instead of calling `copy` a million times.
No more misleading errors when running `npm run start -w dev-environment`.
Repocop still runs correctly.
=> Don't pull DB schemas

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/data-audit.ts, packages/cdk/lib/github-actions-usage.ts, packages/cdk/lib/interactive-monitor.ts, packages/cdk/lib/repocop.ts, packages/cdk/lib/service-catalogue.test.ts, packages/common/prisma/schema.prisma
Change the architecture of each lambda to Arm64.
Arm based lambdas are cheaper and more performant. See https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/.
- [Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/8df7ce4d-c5bf-42af-941e-e86d88a1bfd2)
- Successfully ran each lambda
Here are some statistics after invoking the x86_64 and arm64 versions of each lambda once with the same input.
Lambda | Architecture | Duration (ms) | Init Duration (ms) | Max Memory Used (MB)
-- | -- | -- | -- | --
data-audit | arm64 | 43,625.24 | 544.92 | 226
data-audit | x86_64 | 40,958.23 | 471.65 | 217
dependency-graph-integrator | arm64 | 11.61 | 404.20 | 91
dependency-graph-integrator | …
=> Move to Arm64 lambdas 

package-lock.json, packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Run the service catalogue db as a Multi-AZ on prod
This is the standard approach for PROD and we saw we did not at the moment when doing the reservations. So we reserved a Multi-AZ db instance now.
=> Run service catalogue in Multi-AZ on prod

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Do not write trailing newline from GitHub configuration files to improve CloudQuery's parsing.
This should solve the CloudQuery error:
> Error: failed to sync v3 source github: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: failed to parse AppID 000000\n: strconv.ParseInt: parsing "000000\n": invalid syntax
[Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/b7d9637b-2190-44e1-a65c-18e81a988740), and successfully ran the `GitHubRepositories` task.
=> fix(cloudquery): Remove newline from GitHub config files

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts, packages/common/prisma/migrations/20240329083925_snyk_frequency/migration.sql
Since the version update in https://github.com/guardian/service-catalogue/pull/809, the `snyk_reporting_issues` property is not valid, as observed in the logs:
> jsonschema: '/table_options' does not validate with https://github.com/cloudquery/cloudquery/plugins/source/snyk/client/spec/spec#/$ref/properties/table_options/$ref/additionalProperties: additionalProperties 'snyk_reporting_issues' not allowed
It has been replaced with [`created_after`](https://hub.cloudquery.io/plugins/source/cloudquery/snyk/latest/docs?search=sny#overview-snyk-table-options-spec) which takes an ISO 8601 date string.
Achieving the same "only collect issues from 30 days ago" with the new configuration options is tricky, as the ISO 8601 string will be set at build time, not runtime...
Additionally, to avoid …
=> fix(cloudquery): Remove erroneous configuration

packages/repocop/src/evaluation/repository.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts
Pull dependabot alerts for production repos up front.
This brings data loading behaviour for dependabot in line with the rest of repocop. We've generally preferred loading all our data up front, and failing fast if there are any issues. This also pushes `await` statements to the edge of the lambda, making repocop more testable overall.
The function to pull dependabot alerts has been moved to `query.ts`, as to an outside observer, it's behaviour isn't really that different to if we were pulling this information from the CloudQuery database.
Repocop runs as expected. The number of vulnerabilites detected has remained constant.
=> pull all dependabot vulnerabilities up front

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/index.ts, packages/dev-environment/dev-config/cloudquery.yaml
This change adds table_options to the AWS source to ingest only the records which are ACTIVE. 
Right now aws_securityhub_findings has 51000 active records and 914000 archived records. This is extremely slow to query, taking about 19.5 seconds. This number is also unlikely to decrease over time. The 914050 archived records (representing a little under 95% of entries aren't particularly interesting, as there will be a more up to date ACTIVE record, if the resource(s) in question still exist.
This table runs once a day. Ignoring the free rows quota, using the price of $15 per million rows, and the row counts stated above, this change will save us  about $14 a day, which over the course of a month, represents a saving of over $400 a month, or 27.5 million rows ($5000 over the course of a …
=> Add Table Options to AWS Source to only ingest ACTIVE SecurityHub findings

.github/dependabot.yml
These libraries are related, so update them in unison.
https://github.com/guardian/service-catalogue/pull/895 is failing the build, for no fault of our code. Updating the octokit libraries in unison (hopefully) improves this.
This change will also result in fewer PRs. For example the changes in https://github.com/guardian/service-catalogue/pull/900, https://github.com/guardian/service-catalogue/pull/899, and https://github.com/guardian/service-catalogue/pull/895 will be made in a single PR.
=> chore: Configure octokit Dependabot group

jest.config.js
Improve the DX of a failing test using https://jestjs.io/docs/configuration#github-actions-reporter to annotate a pull request with details of a failing test.
The build log is fairly busy, and can be difficult to isolate which test is failing. Annotating the failing test(s) improves the DX.
=> ci: Add test reporter

packages/common/prisma/migrations/20240408141500_view_aws_resources/migration.sql, packages/common/prisma/schema.prisma, packages/common/prisma/views/public/view_aws_resources.sql
Add a view to service-catalogue for easier querying of resources and their tags
We want more visibility on tagged resources
Tried locally
=> New view view_aws_resources for tagging OKR baseline

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts, packages/dev-environment/dev-config/cloudquery.yaml
By limiting ourselves to only open, sufficiently severe issues, the number of rows in this table has reduced from ~50k to about 1.5k, a reduction of 98.5%.
Prior to #874 , we were ingesting about a million rows a day, so the combination of these PRs mean we are ingesting 99.85% less data
Queries against this table take a long time to execute. By limiting ourselves only to information that is relevant, the table is now about 700x smaller than it was last week, and we should see a correlating increase in performance. 
A view is a thin query wrapper around the original table. It provides no performance benefit, and is more useful as a tool of convenience rather than performance
Prisma doesn't have great support for materialized views. Also, this would require more work to be done to make …
=> Reduce the number of rows we collect form security hub

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/cloudquery/task.ts
Adds a new sidecar container to all our tasks. This sidecar runs [`aws-otel-collector`](https://github.com/aws-observability/aws-otel-collector) which collects Telemetry traces from CloudQuery and forwards them to AWS XRay[^1].
The `aws-otel-collector` sidecar also supports collecting container metrics such as CPU usage and Memory usage, but @NovemberTang found that its possible to enable `Container Insights` at a cluster level and AWS will collect roughly this information for us. So for now I've disabled the `aws-otel-collectors` ability to collect metrics.
Cloudquery is capable of [generating traces](https://docs.cloudquery.io/docs/advanced-topics/monitoring) to let developers understand whats happening under the hood. This is good for debugging and fine tuning job resources.
This also …
=> Add `aws-otel-collector` cloudquery sidecar to collect OTLP traces and forward them to XRay

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/cluster.ts
Enables Container Insights for ECS.
Container Insights tracks container metrics such as CPU Utilization & Memory Utilization in Cloudwatch allowing us to more easily identify jobs that have too many or too few resources assigned to them.
A slight concern with this PR is how expensive custom metrics are in Cloudwatch, with each custom metric costing 0.30$ per month it can be quite scary to have ~10 custom metrics per task. However, as I understand metrics are charged by the hour and only if they're actively being pushed to, this means for most tasks that are run daily the metric will only be "active" 1 hour every day, therefore costing 0.30/24 = 0.0125$ per month per metric.
We have 26 tasks, so it roughly works out at 3.25$ per month for these metrics assuming my above understanding is …
=> Enable Container Insights

packages/common/prisma/migrations/20240409101800_function_aws_resource/migration.sql, packages/common/prisma/schema.prisma
- **Drops the `view_aws_resources` view in favour of a function.**
Views can be a bit problematic for CloudQuery and Postgres. The structure of any tables a view depends on cannot be changed, this means that you have to delete the view before you can change the underlying tables.
Since our view references most AWS Cloudquery tables this means that we won't be able to update any of our tables without deleting our view. This can also cause CloudQuery to behave unpredictably as it will try to update table schemas whenever a plugin is updated.
Functions on the other hand don't have this limitation. Due to how much custom code a function can contain its impossible for Postgres to do integrity checks on tables used by a function.
Using a function in a query is pretty straight forward. The only …
=> Add new `aws_resources()` function which returns a dedupped list of AWS Resources tracked by cloudquery

packages/common/prisma/migrations/20240410101502_aws_securityhub_findings/migration.sql, packages/common/prisma/schema.prisma
Adds aws_securityhub_findings to the prisma schema
Creates indexes for the table, for faster searching
Running this query
```sql
SELECT title
, resources
, aws_account_name
, severity
, workflow
FROM aws_securityhub_findings
WHERE aws_account_name = '<MY_ACCOUNT>'
AND workflow ->> 'Status' != 'SUPPRESSED'
ORDER BY severity ->> 'Normalized' DESC
LIMIT 50
```
previously took 22 seconds. When using this table as a source for grafana, this results in intolerable waiting times when graphs are loading. By creating a migration that includes adding indexes, we can see the query time reduced to 220 ms, a 100x improvement
The migration has already been applied to CODE, and the query benchmarked
=> Add aws_securityhub_findings table to prisma schema, and make more performant

package-lock.json, packages/cloudbuster/.gitignore, packages/cloudbuster/README.md, packages/cloudbuster/package.json, packages/cloudbuster/src/config.ts, packages/cloudbuster/src/index.ts, packages/cloudbuster/src/run-locally.ts, packages/cloudbuster/tsconfig.json
Get in loser, we're going [cloudbusting](https://www.youtube.com/watch?v=pllRW9wETzw)!
Since #922 , the `aws_securityhub_findings` table has been availabe to the Prisma client. This PR sets up a skeleton project that will eventually send FSBP alerts to teams.
We currently have an FSPB dashboard, where teams/managers can examine their open vulnerabilities, as well as in SecurityHub itself, but there is currently no standardised way of getting these alerts to teams. In the same vein as repocop, cloudbuster is a lambda that will collect this information, process and prioritise it, and tell teams what the most urgent vulnerabilities are.
Local execution works.
=> Create cloudbuster project

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts
Skips the `aws_wellarchitected` tables.
We don't use wellarchitected so the data from these tables is not very useful. They also contain a lot of AWS managed resources that are untagged which throws off our tagging baseline.
=> Skip `aws_wellarchitected` tables

packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts
Co-authored-by: @tjsilver 
If a CVE-based vulnerability ID is available, pass only that to the `cves` field of the `RepocopVulnerability` interface. Otherwise, fall back to the original list of IDs.
Snyk usually gives a vulnerability an internal Snyk ID, regardless of whether or not there is already a CVE.
This means there are lots of scenarios where a dependabot issue looks like this `[CVE-1234]`, and its corresponding Snyk issue could look like this `[CVE-1234, SNYK-5678]`, meaning that it does not get deduplicated.
Now that we are filtering out the Snyk ID wherever possible, we are able to deduplicate CVEs more accurately
- Unit tests have been added to verify the correct behaviour.
- Repocop has been run on CODE, where we saw the number of vulnerabilities drop by 11%
=> feat: Remove Snyk vulnerability IDs where possible in favour of CVEs.

packages/common/prisma/migrations/20240409101800_function_aws_resource/migration.sql, packages/common/prisma/migrations/20240412103300_aws_resources/migration.sql, packages/common/prisma/schema.prisma
I've gutted a lot of the behaviour from aws_resources() in an effort to make it more readable and less complex.
- `aws_resources()` has been renamed to `aws_resources_raw()` and now returns the raw rows from all tables containing an ARN column. Deduping and grouping is now handled by consumers of `aws_resources_raw()` instead of the function itself. This vastly improves readability as there is no longer a need to build a giant query string.
- A lot of the ARN manipulation code to extract properties of the ARN have been moved to their own functions, again reducing the complexity of the `aws_resources()` function. Adds 5 new functions: `arn_to_partition(arn)`, `arn_to_service(arn)`, `arn_to_region(arn)`, `arn_to_account_id(arn)`, `arn_to_resource_type(arn)`
- Code to check if a table has a …
=> Refactor and cleanup aws_resources() and create a materialized view

jest.config.js
Reverts guardian/service-catalogue#896
The change in the original PR had some unintended consequences. Individual tests are no longer visible in the console when running `npm run test` locally. This makes it almost impossible to debug test failures without pushing to GitHub or raising a PR. As a result, CI has "shifted right", and debugging tests takes much longer than it needs to, as it requires an interaction with GitHub.
I think that having GitHub annotate PRs with test failures is valuable, but this shouldn't come at the expense of elongating the feedback loop.
=> Revert "ci: Add test reporter"

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts, packages/repocop/src/types.ts
- Adds a new action to the vulnerability digest Anghammarad notification which links to the Grafana dashboard filtered to the team slug.
- Moves the action creation into the `createDigest`  function
- Adds an `actions` field to the VulnerabilityDigest type.
Teams will be able to view all their Critical and High vulnerabilities in one place.
All unit tests pass and the shape of the digest produced is as expected.
=> feat: add action to link to team vuln dashboard

.github/workflows/cloudquery-image.yml, .github/workflows/cq-image.yml, containers/cloudquery/Dockerfile, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/cloudquery/task.ts
- Enable readonlyRootFilesystem on our ECS Tasks. This resolves 52 FSBP ECS.5 violations by locking down the container filesystem to prevent unexpected writes.
- Adds ephemeral mounts for Internal Cloudquery data and User config to be written to. Functionally, each of these mounts replaces a directory in the file system that would otherwise be read-only.
- Creates a custom Dockerfile that already contains the required AWS certificates, and a workflow to release the image, similar to `prisma-migrate-image.yml`
Tested in CODE against AWS and GitHub jobs. Both run without issue
=> Enable `readonlyRootFilesystem` in our ECS Task config

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Removes the action that links to the SLA obligations and replaces it with text in the digest itself.
Saves users at least one click and provides the information there and then.
Local tests ran successfully.
=> refactor: remove obligations action and replace with text

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts
Bumps AWS Source plugin to v26.0.0
This version includes a bug fix to various tables where the `tags` column was not in the correct format.
- Change tag column to a map {} rather than an array of objects [{}] for tables aws_directoryservice_directories, aws_ec2_traffic_mirror_filters, aws_ec2_traffic_mirror_sessions, aws_ec2_traffic_mirror_targets, aws_emr_notebook_executions, aws_emr_studios, aws_transfer_agreements, aws_transfer_users, aws_transfer_certificates, aws_transfer_connectors, aws_transfer_profiles, aws_transfer_workflows
In v25.0.0 a number of AWS tables were moved to premium. We should keep an eye on our row usage to make sure it doesn't increase drastically.
=> Bump AWS Source plugin to v26.0.0

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Update the version of the [Galaxies plugin](https://github.com/guardian/cq-source-galaxies/releases). This version includes dependency updates, some of which patch vulnerabilities. For example https://github.com/guardian/cq-source-galaxies/security/dependabot/7.
N/A.
=> chore(deps): Update Galaxies plugin to v1.1.3

.github/workflows/singleton.yml, containers/singleton/Dockerfile, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/images.ts, packages/cdk/lib/cloudquery/task.ts
Create a custom docker image for the singleton container, so we don't need to install awscli and jq.
This is part of the work to resolve AWS FSBP ECS.5 (No write access to root file system by default
Tested on CODE to verify expected behaviour for one job, and multiple concurrent ones.
Create a reusable workflow for creating container images, as we now have 3 of these. This will be done in a follow-up PR
=> Make singleton container readonly

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
This includes a fix to the `snyk_sbom` table. See https://github.com/cloudquery/cloudquery/issues/17767.
Successfully ran CloudQuery locally with this version.
=> chore(deps): Update Snyk plugin to 5.4.0

.github/workflows/cq-image.yml, .github/workflows/prisma-migrate-image.yml, .github/workflows/singleton.yml
Switches from a named release to a branch
I think versioned releases make sense if we are using a workflow from another repo. However, as this action is only used by the service catalogue, I think that doing this would create unnecessary complication, in exchange for very little security benefit. In order to update a versioned workflow, the steps would be
1. Create a branch with the desired change,
2. Test the change referencing `branch-name` instead of `vX.Y.Z`
3. Remember to put it back at the end
4. Create a PR, and merge it to main
5. Create a new version via the CLI or GitHub UI
6. Create a second PR, advancing the version referenced in the action to the new release.
Using the relative workflow path, the steps are
1. Create a branch with the desired change
2. Test it
3. Create a PR, …
=> use the main branch of release-image instead of a tagged version

jest.config.js
Attempt https://github.com/guardian/service-catalogue/pull/896 again, following the reversion in https://github.com/guardian/service-catalogue/pull/933.
In this version, we observe the [`GITHUB_ACTIONS` environment variable](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) which:
> Always set to `true` when GitHub Actions is running the workflow. You can use this variable to differentiate when tests are being run locally or by GitHub Actions.
Locally, test outputs look the same. In CI, test failures are annotated on the PR.
As noted in https://github.com/guardian/service-catalogue/pull/896, the build log is pretty noisy. Seeing where https://github.com/guardian/service-catalogue/pull/941 is failing will be easier with PR annotations.
Ran the …
=> ci: Add test reporter... take 2

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/task.ts
Forbids the OTEL container job from writing to the root filesystem
Security! Hopefully this is the last general-purposed container for CQ jobs that has write access to the filesystem
Ran the OrgWideEc2 job on CODE, verified that traces still show up
Deployed to CODE, and since then, the number of failing controls has dropped by almost half (the remaining half are PROD task definitions, and a couple of specialist containers)
=> make OTEL container readonly

packages/interactive-monitor/src/index.ts
Interactive monitor was logging excessively. I think we only really need the debug logs when we think something has gone wrong, so for now, let's filter them out and just record the final decision
Make logs more readable
=> set some noisy logs to DEBUG

ADR/04-tagging-obligation.md
Add an architecture decision record (ADR), for prosperity, describing the approaches considered to monitor the tagging obligation.
See https://github.com/guardian/recommendations/blob/main/architecture-decision-records.md.
=> docs: Add ADR for monitoring the tagging obligation

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/task.ts
Make postgres container readonly
Security! see #948 #947 #937 #934 for prior art
Ran on CODE, verified container behaviour is normal
=> Make postgres container readonly

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/stale.yml
This PR versions any remaining actions by SHA, where applicable.
This is more secure, as per our [recommendations](https://github.com/guardian/recommendations/blob/main/github-actions.md).
=> refactor: add SHAs to action versions

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts, scripts/setup.sh
> [!CAUTION]
> This PR should not be merged until comms have been sent to the department.
The main changes are:
- Only display extended information about vulnerabilities not in the historic backlog
- Create separate digests based on severity
- Send alerts for critical vulnerabilities every day, and high vulnerabilities once a week.
Teams are now aware of their vulnerability backlogs, and don't need reminding biweekly. Let's switch to a more alert-based model, displaying only alerts raised after a certain cut-off, so teams can prioritise newer alerts over historic vulnerabilities. We also want the messaging to reflect the urgency with which they should be dealt with. Critical alerts are sent daily, meaning developers should drop feature work to triage or resolve them. High severity …
=> Only include recent vulnerabilities in digests

containers/prisma-migrate/run-prisma-migrate.sh, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/prisma-migrate-task.ts
Makes all parts of the prisma container readonly, except for the ./prisma directory, where all files are now loaded
Security!
The change has been deployed to CODE and tested to make sure no errors occur while the script is being run
=> Make prisma container readonly

packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/test-data/example-dependabot-alerts.ts
Prefer snyk or github advisories, if they exist. Vulnerability digests only link out to the first URL in the list, so lets make it one that's the most likely to be helpful
The URLs we prioritise are aimed at developers rather than security researchers, and are generally a bit easier to understand.
Added unit tests
=> QOL: sort vulnerability URLs to show more useful ones first

packages/common/prisma/migrations/20240508195000_refresh_aws_resources/migration.sql, packages/common/prisma/migrations/20240508195000_refresh_aws_resources/migrations.sql
The materialised view aws_resources showed iam policies as tageable even though they are not, this migration corrects this.
This migration changes the view aws_resources but without populating it.
This can not be done after the migration was applied with
select refresh_aws_resources()
Changes to the sql of the previous migration:
function arn_taggable to return false for aws managed iam policies
aws_resources_raw uses arn_taggable (sadly I had to include the whole function not just the change)
I also added refresh_aws_resources() with I had planned to use in a lamda a db trigger, but kept.
I now create the materialised view without data in case I will add further migrations during the quarter since I feel data dumping should not happen in the migrations
The aws_resources view powers our …
=> aws_resources materialised view correct taggable flad for iam policies

containers/db-copy/entrypoint.sh, packages/dev-environment/script/start
Apply Prisma migrations to dev environment when running the `start` script.
We want to be able to use the functions contained in our prisma migrations for developing new things locally!
Ran locally.
=> Apply migrations to Dev environment

containers/prisma-migrate/Dockerfile, containers/prisma-migrate/run-prisma-migrate.sh, packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/prisma-migrate-task.ts
Since https://github.com/guardian/service-catalogue/pull/986 the Prisma migration task has been failing with:
```log
download failed: s3://<REDACTED>/deploy/CODE/service-catalogue-prisma-migrations/prisma.zip to prisma/prisma.zip Could not create directory /usr/src/app/prisma: [Errno 30] Read-only file system: '/usr/src/app/prisma'
```
That is, we're unable to download a file from S3 to a read-only path.
This change:
- Mounts the `/usr/src/app/prisma` volume in the container, as a writable location
- Updates the container's entry point to download the artifact to this location
This results in the above error being resolved, and the migrations completing. Indeed the logs show this:
An additional change was made to better orchestrate the deployment order. See the inline comment for more …
=> fix(prisma): Correct volume permissions

.github/workflows/release-image.yml, containers/prisma-migrate/Dockerfile, packages/dev-environment/README.md, packages/dev-environment/docker-compose-prisma-migrate.yaml, packages/dev-environment/script/start-prisma-migrate-test
Add the possibility to test prima migrations locally
The feedback cycle is otherwise too long
Tested locally
=> Add a possibility to test prisma migrations locally

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Since https://github.com/guardian/service-catalogue/pull/942, the Galaxies tables are failing to sync with the following error:
```log
failed to sync v1 source galaxies: rpc error: code = Unknown desc = failed to sync resources: failed to create execution client for source plugin guardian-galaxies: unable to load AWS config, failed to get shared config profile, deployTools
```
This is fixed in [v1.1.6](https://github.com/guardian/cq-source-galaxies/releases/tag/v1.1.6). See https://github.com/guardian/cq-source-galaxies/pull/20.
See https://github.com/guardian/service-catalogue/pull/1006.
=> chore(deps): Update Galaxies plugin to v1.1.6

packages/dev-environment/script/start
Adds -f as a flag to the line that removes `SQL_DIR`
From `man rm`
```
-f      Attempt to remove the files without prompting for confirmation, regardless of the file's permissions.  If the file does not exist, do not display a diagnostic
message or modify the exit status to reflect an error.
```
This was causing `npm run start -w dev-environment` to fail if `SQL_DIR` didn't exist in the first place
Script now runs correctly
=> dev-environment setup shouldn't fail if SQL_DIR does not exist

.github/workflows/ci.yml, jest.config.js, package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/obligatron.ts, packages/cdk/lib/service-catalogue.ts, packages/obligatron/.gitignore, packages/obligatron/README.md, packages/obligatron/package.json, packages/obligatron/src/config.ts, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/index.ts, packages/obligatron/src/obligations/tagging.test.ts, packages/obligatron/src/obligations/tagging.ts, packages/obligatron/src/run-locally.ts, packages/obligatron/tsconfig.json, scripts/ci.sh
Creates a new "obligatron" lambda which evaluates service-catalogue data and decides if its compliant with obligations.
This lays some of the groundwork for writing the business logic for some of the obligations the Ops team is working on (and maybe Security and Reliability too?).
Eventually this lambda should provide a framework for fetching data from Service Catalogue and saving it to a results table in a generic way so that when writing a new obligation the developer only has to worry about parsing the data, and not establish a DB connection or saving the results to a table.
In the short term this lambda will evaluate the Ops TAGGING obligation by fetching data from the aws_resources view, filtering out AWS managed resources, and validating them against our tagging schema.
Ran locally.
=> Create "obligatron" lambda

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts, packages/dev-environment/config/cloudquery.yaml
Remove the `severity_normalized` filter when collecting AWS Security Hub findings. We're using the Tagging Standard for the tagging obligation. These findings are reported with a severity of 0; removing the filter allows them to be collected in Service Catalogue.
The `severity_normalized` filter is also [deprecated](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_Severity.html).
Ran locally; it does not take significantly longer to collect this data either.
=> feat(cloudquery): Collect more Security Hub findings

.env, packages/dev-environment/docker-compose.yaml
In the DEV environment, CloudQuery fails to connect to the Postgres database, logging:
```log
failed to init destination postgresql: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: failed to get current database: failed to connect to `host=postgres user=postgres database=postgres`: dial error (dial tcp 172.26.0.2:5432: connect: connection refused)
```
This is because Postgres is still initialising when the connection is attempted. This initialisation includes creating the tables, and inserting rows copied from CODE.
In this change, a healthcheck is added to the Postgres container, passing only once the initialisation has completed. CloudQuery (and Grafana) starts afterwards.
Additionally, the configuration is updated, getting the CloudQuery container …
=> fix(dev-environment): Wait for Postgres to initialise before running CloudQuery

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Prefixes each AWS task with `Aws`. This makes it a little easier to identify the purpose of the task, as it creates a pseudo-namespace.
Required by #1048.
See the updated snapshot.
I've also [deployed](https://riffraff.gutools.co.uk/deployment/view/b3de76e4-5e3b-4b65-8de0-4299524cb048) this to CODE. The updates can be seen via the `cli` project:
```bash
➜ npm -w cli start -- list-tasks --stage=CODE                      
> cli@0.0.0 start
> tsx src/index.ts list-tasks --stage=CODE
[
"AwsCostExplorer",
"AwsDelegatedToSecurityAccount",
"AwsListOrgs",
"AwsOrgWideAutoScalingGroups",
"AwsOrgWideBackup",
"AwsOrgWideCertificates",
"AwsOrgWideCloudFormation",
"AwsOrgWideCloudwatchAlarms",
"AwsOrgWideDynamoDB",
"AwsOrgWideEc2",
"AwsOrgWideInspector",
"AwsOrgWideLoadBalancers",
"AwsOrgWideRDS", …
```
=> refactor(cloudquery): Prefix all AWS tasks with `Aws`

.github/workflows/ci.yml, package-lock.json, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/refresh-materialized-view.ts, packages/cdk/lib/service-catalogue.ts, packages/common/prisma/migrations/20240530093317_aws_resources_owner/migration.sql, packages/refresh-materialized-view/README.md, packages/refresh-materialized-view/package.json, packages/refresh-materialized-view/src/config.ts, packages/refresh-materialized-view/src/index.ts, packages/refresh-materialized-view/src/run-locally.ts, packages/refresh-materialized-view/tsconfig.json, scripts/ci.sh
> [!TIP]
> Easiest to review [commit by commit](https://github.com/guardian/service-catalogue/pull/1048/commits).
The `aws_resources` materialized view is currently informing the tagging obligation, and is being used by a few dashboards. Materialized views need to be refreshed. We're currently doing this manually, and sporadically. This means our dashboards often show stale data.
This change adds a new lambda to refresh the materialized view. The lambda is triggered on the successful completion of an AWS based task. This should result in our dashboard reflecting up to date data at all times.
> [!NOTE]
> - The "obligatron" (#989) should replace this view. That is, this lambda is likely to be a short term solution.
> - This change creates a new database user.
I've run the project locally, …
=> feat: Automatically refresh `aws_resources` materialized view

ADR/04-x01-tagging-obligation.md
Extends the ADR from https://github.com/guardian/service-catalogue/pull/955, to document the decision to use AWS Security Hub to identify tagging usage.
=> docs: Update ADR for tagging obligation

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Adds a new scheduled task to ingest IAM credential reports every 4 hours.
This data will be used to populate a Grafana dashboard that will replace Security HQ.
Currently, Security HQ updates IAM credential reports every 4 hours, so we need service catalogue to match the ingestion frequency.
Deployed to CODE and verified the new task appears in the list of tasks. I also ran it.
=> Create ingestion task for IAM credential reports

scripts/setup.sh
Later steps in the script assume that this directory exists and is writable. Having defined the path, let's also make sure it exists. 
At the moment this script fails when setting up the project for the first time.
I've run setup from scratch after this fix, to verify it works.
=> Make sure that local_env_file_dir exists

packages/obligatron/src/config.ts, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/index.ts, packages/obligatron/src/obligations/tagging.test.ts, packages/obligatron/src/obligations/tagging.ts
- Allow Obligatron to start saving results to the DB after processing obligations.
- Change the tagging obligation to return results in a way thats more friendly with our Schema.
- Add logging to Obligatron so that we can see more about what its doing in ELK.
Requires https://github.com/guardian/service-catalogue/pull/1050 to be merged.
Ran locally:
=> Save obligatron results to DB

packages/repocop/src/index.ts
Allows the creation of vulnerability digests to be toggled on and off
Consistency with the rest of the code, easier regeneration of PROD repocop data
=> only send vulnerability reports when ENABLE_MESSAGING=true

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Fixes maths so that teams have 30 days to fix a vulnerability that was raised in the last 24 hours.
Add test to verify the days left to fix is the same at the start and end of a 24 hour period
Consistency, and to better reflect reality. Previously, it was almost impossible to get repocop to say you had two days to fix a vuln unless it had been raised at the exact instant it was executing.
Unit tests have been updated to more precisely define the behaviour of the function
=> Round up number of days teams have to fix vulnerabilites

packages/common/prisma/migrations/20240610104100_replace_views_with_functions/migration.sql, packages/common/prisma/schema.prisma
Replace all database Views with Functions.
Cloudquery updates the schema of tables by dropping them and recreating them. This clashes with Postgres as Postgres will prevent any table referenced by a view to be dropped.
Unfortunately this has the effect of causing the Cloudquery job to continuously fail until a Human comes along and drops the view and table manually, and then recreates the view after the table has been updated.
As far as I know theres no way to turn this behaviour off in Postgres, but there is a workaround and that is to use Functions which don't perform the same kind of referential integetrity checks when a table is dropped.
This does have the downside that the logic of our functions is only checked at runtime, not at deploy time, so it becomes possible to deploy a …
=> Convert all Views to Functions

package-lock.json, packages/repocop/src/evaluation/repository.ts
We got a CodeQL alert for unsafe URL parsing. This change checks the relevant part of the URL for the correct string, making our check a little more accurate. It shouldn't have a significant impact on code security, because URLs are always coming from Snyk or Dependabot, but this is good practice, and makes our check more precise.
Unit tests around URL ordering continue to pass
=> use url parsing instead of string matching

packages/common/prisma/migrations/20240614105000_repocop_user/migration.sql, sql/dbuser.sql
Moves the manually applied SQL script to create the repocop user, and apply permissions, to a Prisma migration, so that it gets automatically applied.
Whilst it looks like a no-op, the exexution of:
```sql
GRANT SELECT ON ALL TABLES IN SCHEMA public TO repocop;
```
Will grant `repocop` access to the `view_repo_ownership` view, which was lost in #1066.
> [!NOTE]
> - The next PR will add a test that's run in CI to catch this regression in future.
> - We have [some more SQL scripts](https://github.com/guardian/service-catalogue/blob/524e0d07211ed1cbef86884878c3bb3d4eb2ab51/sql/dbuser.sql) that have been manually applied. In future PRs we will convert those to Prisma migrations too.
The `repocop` user requires permission on `view_repo_ownership` to run. It no longer has these permissions.
- …
=> fix(repocop): Prisma migration for repocop db user

.github/workflows/ci.yml, sql/ci.sql
The changes in #1066 created a regression, where the `repocop` database user lost access to a view.
In this change, we run some SQL in CI in an attempt to catch such regressions earlier.
Observe CI. The build log (see below) shows we've switched user, and performed a `SELECT *` on the view successfully (the query returns 0 rows as the database is empty).
=> ci: Perform basic SQL tests

packages/obligatron/src/obligations/index.ts, packages/obligatron/src/obligations/tagging.test.ts, packages/obligatron/src/obligations/tagging.ts
Start using our Security Hub data in Obligatron.
This greatly reduces the complexity of our Tagging obligation by reducing our dependency on our custom `aws_resources` view and instead leave it to Amazon to figure out whats tagged and what isn't.
Ran Locally
=> Consume Security Hub tagging data in Obligatron

packages/common/prisma/migrations/20240619190000_obligatron_user/migration.sql
Creates a Prisma migration to create the database user for the [obligatron application](https://github.com/guardian/service-catalogue/blob/4e45a8410c9ad71764c88eb7b4c4beaef01ff795/packages/cdk/lib/obligatron.ts#L38).
=> feat(obligatron): Prisma migration for obligatron db user

packages/common/prisma/migrations/20240620144000_obligatron_user/migration.sql
The `id` column of `obligatron_results` is of type `serial`. The `obligatron` database user needs permission to update the value.
See https://dba.stackexchange.com/questions/71528/explicitly-granting-permissions-to-update-the-sequence-for-a-serial-column-neces.
The lambda runs in CODE up until it tries to write results to the database, at which point the following error is seen:
```log
permission denied for sequence obligatron_results_id_seq
```
[Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/0831c7eb-478f-48c6-ac3e-2c2dfa67c5af), and successfully ran the obligatron lambda with the results seen [here](https://metrics.code.dev-gutools.co.uk/goto/IHc2sC8Ig?orgId=1).
=> fix(obligatron): Allow usage of `obligatron_results_id_seq`

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Change frequency for aws_ssm_parameters and aws_lambda_* to daily from weekly
For grafana dashboard showing resources that will come up for deletion in the playground account. Since we are aiming for 2 week retention period, collecting the data once a week is too little, and only collecting the table queried would lead the potential consistency issues for cross table queries.
=> Add daily runs of aws_ssm_parameters and aws_lambda_*

packages/common/prisma/migrations/20240620104500_obligatron_ec2_images_access/migration.sql, packages/common/prisma/schema.prisma, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/tagging.test.ts, packages/obligatron/src/obligations/tagging.ts
The adoption of [AWS Security Hub Resource Tagging Standard](https://docs.aws.amazon.com/securityhub/latest/userguide/standards-tagging.html) means a subset of all AWS resources are having their tags evaluated.
Amazon Machine Images (AMIs) are one of the resources no covered. We produce a large number of AMIs. This change updates obligatron to query the `aws_ec2_images` table, to evaluate the tagging of our AMIs.
[Deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/74848b28-ae9b-4f5c-bfd3-ef6fcb5c5b7a), and successfully ran the lambda with the results viewable [here](https://metrics.code.dev-gutools.co.uk/goto/cXu5XjUSg?orgId=1).
=> feat(obligatron): Augment tagging results with AMI info

packages/common/src/functions.test.ts, packages/common/src/functions.ts, packages/common/src/types.ts, packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts, packages/repocop/src/types.ts, packages/repocop/src/utils.test.ts, packages/repocop/src/utils.ts
Obligatron will need data from the `repocop_vulnerabilities` table, to evaluate whether or not a repo is meeting its vulnerability SLA obligation. To make that work possible, we need to move some of the logic concerning the `RepocopVulnerability` type from `repocop` to `common`
CI passes
=> Move RepocopVulnerability logic from repocop to common

package-lock.json, package.json, packages/dashboard/.eslintrc, packages/dashboard/package.json, packages/dashboard/src/components/testIds.ts, packages/dashboard/src/constants.ts, packages/dashboard/src/module.ts, packages/dashboard/src/utils/utils.plugin.ts
Use the Guardians eslint config exclusively in the `dashboard` project, instead of the Grafana eslint config
These two config have rules that clash, specifically
- no-duplicate-import
- @typescript-eslint/consistent-type-imports
`@typescript-eslint/consistent-type-imports` by default tries to seperate types and regular imports onto different lines, even if they're from the same package, whereas `no-duplicate-import` wants things from the same package to be imported together.
`npm run lint`
=> Use Guardian eslint settings in Dashboard project

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/obligatron.ts, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/index.ts
Run Obligatron daily at 7AM
So that we can start building a historical view and get an understanding of how much data there is (once we enable Security Hub on all accounts that is!)
Ran snapshot test.
=> Run Obligatron daily at 7AM

packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts, packages/dependency-graph-integrator/src/index.ts
- Implements the existing lambda using the `gu-snyk-integrator` app for now (this will eventually be replaced with its own app).
- Tidies up the paramaters to the PR generator.
- Replaces the action versions in the generated `yaml` with SHA versions.  
Because we want to replace the Snyk integrator lambda.
Tested locally and PR contents looked sensible.
=> Implement the dependency graph integrator lambda

packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts
Rather than asking the use to click a link to check their dependencies look correct, we just echo them during the GHA run.
This improves developer experience, as there's less clicking around. It also fixes an issue where trying to view the contents of a dependency snapshot did not work in the browser for private repositories.
Tested by raising [this PR](https://github.com/guardian/janus/pull/4211) against a private repo, and verified that we are able to see the contents of the snapshot in situ.
=> Dependency submisison action now echoes SBOM snapshot

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/obligatron.ts, packages/common/src/logs.ts, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/tagging.ts
The logs produced by Lambdas are sent to CloudWatch Logs, and then processed by [guardian/cloudwatch-logs-management](https://github.com/guardian/cloudwatch-logs-management ) to get them into Central ELK. We're currently producing JSON formatted logs, which cloudwatch-logs-management [doesn't process correctly](https://github.com/guardian/cloudwatch-logs-management/issues/326).
Revert to the text log format so the message, and markers, are searchable in Central ELK.
Obligatron produces log lines with markers for `total`, `withQueryLogging` and `startTime`. They can be seen using [devx-logs](https://github.com/guardian/devx-logs/tree/main/cli):
```sh
devx-logs --space devx \
--app obligatron \
--stage CODE \
--column message \
--column total \
--column withQueryLogging \
--column startTime …
```
=> fix(obligatron): Ensure logs and markers appear correctly in Central ELK

packages/common/src/functions.test.ts, packages/common/src/functions.ts, packages/common/src/types.ts, packages/repocop/src/query.ts, packages/repocop/src/types.ts, packages/repocop/src/utils.test.ts, packages/repocop/src/utils.ts
Obligatron will be making use of NonEmptyArray, so move it to the `common` package
CI passes
=> move nonEmptyArray, etc to common

packages/common/prisma/migrations/20240530093317_aws_resources_owner/migration.sql
Adds the equivalent of an IF NOT EXISTS to the `refresh-materialized-view` user.
To stop DEV migrations from failing.
Deployed to CODE, which detected no new migrations. If we want to be good citizens, after merging, we can go in and manually adjust the checksum for this migration, but this is not required.
=> only create refresh-materialized-view user if it doesn't already exist

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/common/prisma/migrations/20240703090946_cloudquery_aws_27_5_0/migration.sql, packages/common/prisma/schema.prisma
> [!NOTE]
> Easiest to review [w/out whitespace](https://github.com/guardian/service-catalogue/pull/1153/files?diff=split&w=1).
Update the [CloudQuery AWS source plugin](https://hub.cloudquery.io/plugins/source/cloudquery/aws/latest/docs) to latest (v27.5.0), and update the Prisma files to match.
The Prisma migration looks bigger than the release notes might suggest. This is because we hadn't reflected the changes in v24.0.0 when we previously updated. v24.0.0 made a change to the `_cq_id` column; this is now the primary key for tables. Consequently, we can remove some now redundant indices.
- Deployed to [CODE](https://riffraff.gutools.co.uk/deployment/view/0d71285e-67d8-4c61-916c-13fd079ce9a0)
- Ran the tasks to collect data for the tables `aws_cloudformation_stacks` and …
=> chore(deps): Update CloudQuery AWS source plugin to v27.5.0

packages/common/prisma/migrations/20240703090946_cloudquery_aws_27_5_0/migration.sql
Title explains it!
To prevent strange migration errors from prisma
Deployed to CODE and verified that the migration works
=> Alter a migration to make it safer, by only adding columns if they do not already exist

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/obligatron.ts, packages/cdk/lib/service-catalogue.ts, packages/common/src/functions.test.ts, packages/common/src/functions.ts, packages/common/src/types.ts, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/dependency-vulnerabilities.test.ts, packages/obligatron/src/obligations/dependency-vulnerabilities.ts, packages/obligatron/src/obligations/index.ts, packages/obligatron/src/run-locally.ts, packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/query.ts, packages/repocop/src/remediation/branch-protector/branch-protection.ts, packages/repocop/src/remediation/topics/topic-monitor-production.test.ts, packages/repocop/src/remediation/topics/topic-monitor-production.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts, packages/repocop/src/types.ts, packages/repocop/src/utils.test.ts, packages/repocop/src/utils.ts
Creates a new running mode for the obligation lambda, called `PRODUCTION_DEPENDENCIES`. This summarises whether or not a repository contains vulnerable dependencies that exceed our SLAs.
Eventually, it should just link directly to the security or insights tab on the given repo, but while we still have vulnerabilities being sourced from Snyk, let's link to grafana instead to provide visibility of the vulnerabilities regardless of source.
Runs obligation lambdas on a staggered schedule to avoid overloading the DB (to avoid problems when we have like 10 of these things executing at once)
So we are able to track our SLA progress over time
Added unit tests, local execution works.
Change the way the CDK works to guarantee that repocop (which generates the `repocop_vulnerabilities` table) …
=> Create an obligation lambda for production repositories with out-of-SLA dependency vulnerabilities

.github/actions/npm-run/action.yml, .github/workflows/ci.yml, packages/cdk/package.json, scripts/build.sh, scripts/ci.sh, scripts/local-ci.sh
Creates a composite action for running an arbitrary npm script. Then, uses that action to run `lint`, `typecheck`, etc in parallel, before moving on to the final build step.
So that we can still run these steps locally, I've created a `local-ci.sh` to run those steps.
The CI script runs pretty fast on our machines with a bajillion cores. GH runners only have two, meaning CI times on GHA have crept up over the last 2 years from about 1:30 to over 5 minutes. This change brings that time back down to 2:49-ish.
CI passes. `local-ci.sh` works.
=> parallelise ci

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
When a single library was causing multiple CVEs to show up against a repo, the vulnerability digests can end up looking identical, especially if dependabot is being enabled for the first time. Let's include the CVE in the vulnerability digest to make it clearer that these are unique issues, as they may have slightly different remediations (ie one requires bumping to `x.y.z+1`, and another requires patching to `x.y.z+4`).
Also, removed boilerplate from the tests by setting up a vuln object at the beginning that is reused in subsequent tests.
Added unit tests to verify expected behaviour
=> Vulnerability digest should show CVEs, to make two vulns from the same library look distinct

packages/dev-environment/script/start
When starting up the dev environment, we exit immediately if docker is not running. Instead, let's launch docker and wait for it to start, then continue launching the containers
There are several seconds between the start of the script and the launch of the containers, and users may end up running through the script a few times trying to get all their ducks in a row. Off the top of my head, this includes
- Verifying AWS credentials
- Checking to see if the user is on the VPN
- Checking to see if docker is running
This PR eliminates one of those sources of friction, for a smoother development experience
I have tested 3 scenarios
1. Docker is already running. The script continues, and docker does not restart, it just continues to run
2. Docker is not running. Docker starts up, and the …
=> try to open docker rather than failing the setup script

packages/dev-environment/docker-compose.yaml, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.test.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.ts, scripts/setup.sh
Enables repocop to identify production Scala repos that don't have the SBT dependency submission workflow already, and pick one repo at random to call Dependency Graph Integrator which will raise a PR on the repo to include the workflow, and enable Dependabot alerts/Dependency Graph if not enabled.
This is part of our migration away from Snyk over the next year. 
Tested locally with CODE data. 
- Prioritise this for repos that don't have the Snyk workflow - this could be handled manually as it's only a handful.
- Enable the integrator for Gradle/Kotlin repos, and any other of our languages for which there is a dependency submission workflow available.
- Increase the number of PRs raised per run...?
- Update our recommendations
=> Enable Dependency Graph Integrator to raise PRs to add workflow

packages/common/prisma/migrations/20240709072758_additional_aws_organizations_tables/migration.sql, packages/common/prisma/migrations/20240709073818_aws_organizations_tree/migration.sql, packages/common/prisma/schema.prisma, packages/common/prisma/views/public/aws_organizations_tree.sql, packages/dev-environment/config/cloudquery.yaml, packages/dev-environment/docker-compose.yaml
AWS Organisations allows one to structure accounts into business units, with seemingly limitless levels.
We currently have something like this:
```
root
├── Editorial
│   └── multimedia
├── Product & Engineering
│   ├── Editorial Tools
│   │   ├── cmsFronts
│   │   └── composer
│   └── deployTools
└── glabs
```
The `aws_organizations_tree` view allows one to query accounts via a tree structure, allowing for ancestry queries. This differs from the `aws_organizations_account_parents` table, which only shows the immediate parent. The `aws_organizations_tree` view also includes each node in the tree: the root, the organisational units, and the accounts.
With `aws_organizations_tree` we can identify the `cmsFronts` account sits within `Product & Engineering`.
The format was inspired by …
=> feat(prisma): Create `aws_organizations_tree` view 

packages/common/prisma/migrations/20240709104714_user_permissions/migration.sql
Extends #1154 to all database users.
This'll make the changes in #1175 easier.
#1175 drops and recreates a view. To keep the current access status quo, we would need to re-grant permissions on each table the view queries, which is a bit longer than this option.
Observe CI, the [checks](https://github.com/guardian/service-catalogue/blob/main/sql/ci.sql) should continue to pass.
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/8950dbc0-e1ba-4dd0-8b40-3c2f7f2e1699), and the migration logs show the migration was successfully applied.
=> fix: Grant all database users blanket read access

packages/common/prisma/migrations/20240709110616_update_aws_accounts_view/migration.sql, packages/common/prisma/schema.prisma, packages/common/prisma/views/public/aws_accounts.sql
> [!NOTE]
> Builds on (and requires) #1174 and #1176.
The `organizational_unit` column in the `aws_accounts` view shows the immediate parent. This change replaces this column with an `ancestors` column, detailing the full ancestry path.
A boolean `is_product_and_engineering` column is also added to make it easy to filter for P&E accounts:
```sql
SELECT * FROM aws_accounts WHERE is_product_and_engineering = TRUE;
```
> [!WARNING]
> This is a breaking change to the `aws_accounts` view.
> 
>  Columns removed:
>   - `organizational_unit` (`TEXT`)
>
> Columns added:
>   - `ancestors` (`TEXT[]`)
>   - `is_product_and_engineering` (`BOOLEAN`)
A number of apps within Service Catalogue currently run against Product & Engineering (P&E) owned accounts, for example Obligatron. We're currently …
=> Add ancestry path to `aws_accounts` view

packages/common/prisma/migrations/20240709114326_remove_non_pande_ami_tagging_results/migration.sql, packages/obligatron/src/obligations/tagging.ts
The tagging obligation currently only applies to AWS accounts owned by P&E. Remove past findings for non-P&E accounts (about 190,000 rows in CODE), and produce future findings from P&E accounts only.
This removes an amount of noise on the [Obligatron dashboard](https://metrics.gutools.co.uk/d/cdokcsudhxrswa/obligatron?orgId=1), particularly within the "Departmental Results" section.
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/1dd3da63-abc5-4fd0-ac0b-b597d048fab2), observed the `obligatron_results` table having no results for non-P&E accounts, and [around 60,000 for P&E accounts](https://metrics.code.dev-gutools.co.uk/goto/Bdst2h_Sg?orgId=1).
I've also successfully run Obligatron on CODE, and observed the `obligatron_results` table having results for P&E accounts …
=> fix(obligatron): Only evaluate AMI tagging within P&E accounts

packages/dependency-graph-integrator/src/file-generator.ts, packages/repocop/src/index.ts
Adds a new step to the PR checklist for the dependency graph integrator to let users know that sbt needs to be v1.5+.
We noticed that some repos have lower versions of sbt and the dependency submission action failed.
Ran `dependency-graph-integrator` locally and the extra checklist item rendered correctly in the PR output.
=> Update the dependency graph integrator PR body 

packages/cloudbuster/src/config.ts, packages/cloudbuster/src/findings.ts
Previously, we were evaluating the results of all Security Hub standards. Now, we are filtering specifically for FSBP control failures
So teams aren't getting infrastructure digests about tags, etc
Run locally, verified digests were smaller, and only contained relevant information
=> fix FSBP filtering in cloudbuster

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/common/src/functions.ts, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/aws-vulnerabilities.test.ts, packages/obligatron/src/obligations/aws-vulnerabilities.ts, packages/obligatron/src/obligations/index.ts
Creates a new obligatron mode that collects information about AWS infrastructure vulnerabilities. Currently, it only logs the output and does not write to the table. This is because we are currently not filtering out results that are within SLA. This will need to be done as a separate PR as further work is needed to unify:
1. the various `Severity` types
2. the calculations we perform on those types to calculate whether a resource is inside or outside SLA
So, that work will be done as a follow up PR. At that point, we will start writing to the DB
So we can track departmental progress against our obligation to keep our AWS infrastructure compliant with AWS FSBP
Verified locally. Added unit tests to confirm expected behaviour
=> Create obligatron mode for AWS infrastructure vulnerabilities

jest.config.js, jest.setup.js
Silence the console during the CI build to make the build log easier to read, and see build errors.
Observe CI log on this branch, and compare it to the build log of main. Has it improved?
=> ci: Silence console messages to make build log easier to read

packages/cloudbuster/src/findings.test.ts, packages/cloudbuster/src/findings.ts, packages/common/src/functions.test.ts, packages/common/src/functions.ts, packages/obligatron/src/obligations/aws-vulnerabilities.ts
- Moves `isWithinSlaTime` and associated tests to common
- Filter FSBP obligatron results so that anything within SLA is excluded
So we can start collecting accurate data about which resources have out of SLA FSBP vulnerabilities.
Tests have been moved, CI passes, local execution produces the expected results
=> Filter out FSBP results within SLA time and write to obligatron DB

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
The 1.1.7, and 1.1.8 patch releases include dependency updates.
Full Changelog: [v1.1.6...v1.1.8](https://github.com/guardian/cq-source-galaxies/compare/v1.1.6...v1.1.8)
=> chore(deps): Update CloudQuery source plugin for Galaxies

packages/repocop/src/config.ts, packages/repocop/src/index.ts
This PR adds a flag to config to stop the sending of SNS messages to the Dependency Graph Integrator by Repocop. Currently Repocop sends one message per run and thus raises one PR a day while there are suitable repos.
The security team has identified a potential bug with the sbt dependency submission workflow and needs time to investigate and remediate if necessary. The Gradle workflow can be implemented manually for now, to allow the security team to test it with teams who have Kotlin/Gradle expertise and ensure it's fit for purpose.
=> Switch off automatic PR creation by Dependency Graph Integrator

packages/common/src/types.ts, packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts, packages/dependency-graph-integrator/src/index.ts, packages/dependency-graph-integrator/src/run-locally.ts, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.test.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.ts
- The Dependency Graph Integrator takes a language parameter, and generates the workflow yaml and PR for both Scala and Kotlin.
- We now refer to the language rather than the package manager in the PR, as this makes things simpler. 
We want to support Kotlin repos, and this now gives the flexibility to add further languages/workflows to the integrator.
=> feat: Add Kotlin to Dependency Graph Integrator

packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/types.ts, packages/repocop/src/utils.test.ts, packages/repocop/src/utils.ts
- make `snyk_issues.attributes.status` a union type, that can either be `open` or `resolved`
- filter out `resolved` issues
- test the new filter
Resolved issues have been remediated, so repocop doesn't care about them.
A new unit test has been added to verify this behaviour.
After running on CODE, we see 80% fewer snyk issues loaded into the lambda's memory, and a reduction in runtime from 30s to 22s.
=> Repocop should skip resolved snyk issues

packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Only show vulnerabilities from the last 60 days in vulnerability digests
Previously, we were sending teams notifications, potentially daily, about vulnerabilities that were nearly six months old. I think vulnerabilities that old can reasonably be considered part of a 'historical backlog', and continuing to pester teams about it is unlikely to result in meaningful change. It may be actively detrimental, as it causes alert fatigue, resulting in teams ignoring messages.
The choice of 60 days is slightly arbitrary, and if it doesn't work, we can always change it later. I've made this value configurable, so we could, for example, experiment with different windows for different severities; but doubling the window given to resolve highs seemed like a reasonable starting point.
Unit tests have …
=> Change vulnerability digest cutoff from a fixed date to a 60 day window

packages/repocop/README.md
- More information about RepoCop's downstream dependencies, such as dashboards and other Lambdas
- Updated instructions on how to run RepoCop locally
- A new section about testing the lambda on AWS
- Expanding the section on how RepoCop should be interacting with the CloudQuery DB
RepoCop's README hasn't been meaningfully updated for over 9 months. In that time a lot has changed, so the README is being updated to reflect that. We're also overhauling our approach to communicating DevX's work, and departmental security standards. Clear, up-to-date documentation is an important part of that.
Running instructions work.
=> Update RepoCop README

README.md
- Markdown formatted numbered lists don't show properly in the readme, so slightly tweak them
- \n is not an escape character, so remove it from the chart
Mermaids diagram now renders properly. Check the rich diff
=> Remove unnecessary newlines from mermaids diagram

packages/dependency-graph-integrator/README.md
- Corrects the lambda input
- Gives an example of the lambda output
- Some diagrams showing how the lambda works, and how the dependency submisison workflow works
View the rich diff for a rendered README
Better documentation means less time spent trying to figure out how stuff works
README renders correctly
=> Update and expand the Dependency Graph Integrator docs

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/repocop.ts, packages/cdk/lib/service-catalogue.ts, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/remediation/topics/topic-monitor-production.ts
the `guardian` github org shows up all the time in our codebase, let's make it a constant that we set via config, and pass it in via CDK. This PR does this for repocop and cloudquery. Follow-up PRs will be raised for other packages. 
Magic values are bad! And this will make it easier for people outside the guardian to use and modify the service catalogue if they wish
=> parameterise github org

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudbuster.ts, packages/cloudbuster/src/config.ts, packages/common/prisma/migrations/20240930091139_cloudbuster_user/migration.sql, sql/ci.sql
As cloudbuster will now be writing to a table, it requires different permissions to repocop. In this PR, we create a user that can only read the table containing security hub findings. It will also need to read from `cloudbuster_fsbp_findings`, but that permission will be granted in #1274 , the same PR the creates the table
=> Create a cloudbuster user

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/interactive-monitor.ts, packages/cdk/lib/repocop.ts, packages/cdk/lib/service-catalogue.ts, packages/common/src/pull-requests.test.ts, packages/common/src/pull-requests.ts, packages/dependency-graph-integrator/src/repo-functions.ts, packages/interactive-monitor/src/config.ts, packages/interactive-monitor/src/index.ts, packages/interactive-monitor/src/js-parser.ts, packages/interactive-monitor/src/run-locally.ts, packages/snyk-integrator/src/config.ts, packages/snyk-integrator/src/index.ts
A follow up to #1271 , this finishes the work to paramaterise all relevant instances of the `guardian` github org across the service catalogue.
For the same reasons as the previous PR. Magic values are bad! And this will make it easier for people outside the guardian to use and modify the service catalogue if they wish
=> Finish paramaterisation of org name

packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts
Fixes a typo in the path to the JSON file which logs the snapshot of dependencies when the PR raised by dependency graph integrator first runs the 'submit dependencies' action. 
So that users can correctly see the output before merging the workflow to main, where it will submit the dependencies to the dependency graph.
Tested on `snyk-test-toolargetool` - see 'Log snapshot for user validation' step: [before](https://github.com/guardian/snyk-test-toolargetool/actions/runs/11160575335/job/31021305450) and [after](https://github.com/guardian/snyk-test-toolargetool/actions/runs/11160800827/job/31022017175)
=> fix: Kotlin dependency submission log snapshot output

packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts
Bumps the versions of the sbt and gradle dependency submission workflows that are used in the PRs created by Dependency Graph Integrator.
To keep things up-to-date.
NOTE: depends on #1291 .
=> update dependency submission workflow versions

packages/cloudbuster/src/digests.test.ts, packages/cloudbuster/src/digests.ts, packages/cloudbuster/src/index.ts, packages/cloudbuster/src/run-locally.ts
Now that cloudbuster writes to a DB, to avoid race conditions, we should not be running two instances simultaneously, as this could create race conditions. Instead, we can follow repocop's model of running every day, with high severities being evaluated once a week
- Added unit tests to verify behaviour
- CI passes
=> Eliminate race condition

package-lock.json, packages/common/package.json, packages/common/src/functions.ts
Upgrade octokit packages, stopping just short of the next major version. This is because octokit libraries then become ESM only, which is a much more involved job.
CI passes
=> upgrade octokit as far as we can

packages/common/prisma/migrations/20241009103331_repocop_sla/migration.sql, packages/common/prisma/schema.prisma, packages/obligatron/src/obligations/dependency-vulnerabilities.test.ts, packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/utils.test.ts
Co-authored-by: Natasha <67543397+NovemberTang@users.noreply.github.com>
Adds a column to the `repocop_vulnerabilities` table to track whether vulnerabilities meet their SLAs (2 days for criticals, 30 days for highs).
To simplify the SQL in the Grafana dashboard.
Tested locally and observed the table with the new column and populated with data.
NOTE: We will have to clear the live tables in advance of running the migration.
=> feat: add within_sla column to repocop vulnerabilities table

packages/common/src/functions.test.ts, packages/common/src/functions.ts
Give developers extra time to resolve critical vulnerbilities raised on or close to the weekend
Provide a more realistic timeline for remediation. Currently, vulnerabilities raised on a friday afternoon (ie after repocop has run that day) are already out of date by the time monday rolls around
Unit tests have been added to verify the status of a vuln raised over the weekend on the following Monday
~~As a follow up PR, we should include an `is_within_sla` field in the repocop table, so that the dashboard has the same information as repocop's vulnerability digest~~ resolved in #1296
=> add a weekend offset for vulnerabilities raised on Fri/Sat/Sun

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudbuster.ts, packages/cdk/lib/service-catalogue.ts, packages/cloudbuster/src/config.ts, packages/cloudbuster/src/index.ts
- Start collecting all cloudbuster data, not just the first five rows
- Convert cloudbuster to a scheduled lambda cloudbuster, allow it to start running on AWS
- Switch off all messaging temporarily
- Cloudbuster's schedule and monitoring configuration echoes repocop's
Cloudbuster is ready to be rolled out after the comms announcement. In advance of this, we need to start migrating the grafana tables. To migrate the grafana tables, we need a complete set of data in the Cloudquery DB. So let's allow cloudbuster to collect this
I've switched off messaging as we don't want to start alerting teams before the comms are sent out. We can reconfigure this next week
CI passes, snapshots look normal.
Works on CODE
=> Allow cloudbuster to run, without sending messages

packages/cloudbuster/src/index.ts
Previously, we were logging the entire table out, in a tabular format. In ELK this is very ugly, and the message also cuts off early because it's so large. Now, we just capture the total number of vulnerabilities so we can sense check the count while debugging
=> stop logging the full cloudbuster findings table

packages/cloudbuster/src/findings.test.ts, packages/cloudbuster/src/index.ts, packages/common/src/types.ts, packages/obligatron/src/obligations/aws-vulnerabilities.test.ts
Cloudbuster should not act on suppressed findings
Suppressed vulnerabilities are handled by a different process
Deployed and ran, saw the expected drop in vulnerability counts. Fixed relevant unit tests.
=> filter out suppressed findings

packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts
Adds a step to the dependency graph integrator PR generator to install sbt.
The workflow currently fails because sbt is no longer bundled with latest Ubuntu.
Tested by copying the output of running locally in `janus-app` and observed that the workflow [succeeded](https://github.com/guardian/janus-app/actions/runs/11349830699).
=> fix: update sbt dependency submission workflow to install sbt

packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts
- Explicitly installs java in the sbt dependency submission workflow created by the dependency graph integrator
- Updates `actions/checkout` to latest
- Updates tests
We can't guarantee that future versions of Ubuntu will ship with Java, and it's required by sbt in this workflow.
=> feat: explicitly install java in sbt dep submission workflow

packages/cloudbuster/src/config.ts
Allow cloudbuster to contact teams about new FSBP vulnerabilities
So they can act on them in a timely manner
=> enable cloudbuster messaging on CODE/PROD

packages/obligatron/src/obligations/dependency-vulnerabilities.ts
Repocop now contains a `within_sla` column, which used `daysLeftToFix()` under the hood. Now, instead of performing the calculation twice, we just work out whether or not something is within SLA by using the column repocop provides
Efficiency
=> Obligatron filters on within_sla

packages/common/src/pull-requests.ts, packages/common/src/types.ts, packages/dependency-graph-integrator/src/index.ts, packages/dependency-graph-integrator/src/repo-functions.ts, packages/dependency-graph-integrator/src/run-locally.ts, packages/repocop/src/index.ts, packages/repocop/src/remediation/branch-protector/branch-protection.test.ts, packages/repocop/src/remediation/branch-protector/branch-protection.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.test.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.ts, packages/repocop/src/remediation/shared-utilities.test.ts, packages/repocop/src/remediation/shared-utilities.ts, packages/repocop/src/remediation/topics/topic-monitor-production.ts, packages/snyk-integrator/src/index.ts
- Adds a function that requests repository admins as reviewers on any PR raised using `createPrAndAddToProject`
- Simplifies findContactableOwners, as since #831 , `view_repo_ownership` has included the team slug, meaning we don't need to cross-reference with `github_teams` to retrieve it
- Deletes one instance of the previously duplicated `createPrAndAddToProject`
> [!WARNING]  
> Requires a GitHub permission change. In addition to `pull-request:write`, we need `members:read` to validate the team name
Engineers are sometimes slow to respond to PRs. By requesting reviews, we hope to speed up the process of having DevX-raised PRs merged. If no significant change is observed, we can try another method
=> Request admin reviews on PRs raised by the service catalogue

packages/dependency-graph-integrator/src/repo-functions.ts, packages/dependency-graph-integrator/src/types.ts
In #1305 , we deleted `createPrAndAddToProject`, as it was duplicated in `dependency-graph-integrator`. Its underlying functions, however, were left behind. This PR cleans that code up
Maintainability
The code wasn't actually being used, so as long as CI passes we're good
=> delete code duplicated in dependency-graph-integrator

.github/workflows/ci.yml
Make CI depend on db-migration
We shouldn't be able to deploy to riff-raff unless the migrations are tidy
CI passes
=> make CI depend on db-migration task

packages/dependency-graph-integrator/README.md
Adds `admins` field to running instructions
This is a required input field
=> docs: fix dependency graph integrator running instructions

packages/cloudbuster/src/digests.test.ts, packages/cloudbuster/src/digests.ts
Group FSBP findings by Control ID, and app. Users can click through on the findings link to see a prefiltered FSBP dashboard.
Any given account could have an arbitrary number of FSBP failures. This means that digests could be (and have been) hundreds of lines long, making them unreadable. Let's start tackling this by grouping control failures by control ID and app, to make them a bit more readable at a glance, which is the point of a digest.
I'm still figuring out the balance between granularity and conciseness. If you group by too may variables, you _can_ end up with almost as many entries as if you'd just listed them all individually. Too few, and you hide information that's useful. I've chosen to group by control ID and app for now.
**Why not Stack?** Most of the time there's only one …
=> Group Cloudbuster findings in digest messages

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/repocop/src/index.ts
updates github languages plugin to 0.0.5
take advantage of some security fixes
=> update github languages plugin to 0.0.5

packages/common/src/types.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.test.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.ts
- Fixes the function (originally `createSnsEventsForDependencyGraphIntegration` ) that detected whether a repo has a dependency submission workflow. The function was erroneously reporting that no workflows were found so all repos were candidates for being selected and sent to dependency graph integrator for PRs to be raised.
- Fixes a bug in the filtering of workflows in the dependency tracking functionality (`hasDependencyTracking` which was still reporting correctly) which uses the same function as above (namely `doesRepoHaveDepSubmissionWorkflowForLanguage`).
- Refactors the sns messaging function `createSnsEventsForDependencyGraphIntegration`  to separate out the workflow check. The function was doing a lot of different things in addition to creating the events. I have pulled out the …
=> Fix workflow check in repocop dep graph integration

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Update https://github.com/guardian/cq-source-ns1 to the latest version which includes some dependency updates, including an [update to Node 22 (LTS)](https://github.com/guardian/cq-source-ns1/releases/tag/v0.1.0). See https://github.com/guardian/cq-source-ns1/releases/tag/v0.1.1.
Staying up to date.
After [deploying to CODE](https://riffraff.gutools.co.uk/deployment/view/ce74f712-bae5-4070-a811-832edaf91202) and manually running the NS1 task (`npm -w cli start -- run-task --stage=CODE --name NS1`), I've observed the [logs](https://logs.gutools.co.uk/s/devx/app/r/s/djryD) showing the plugin collecting data and [Grafana CODE](https://metrics.code.dev-gutools.co.uk/goto/gIKJ2DMHg?orgId=1) showing said data (see the `_cq_sync_time` column):
=> chore(deps): Update `guardian/cq-source-ns1` from 0.0.4 to 0.1.1

packages/dependency-graph-integrator/src/file-generator.ts
Added some clarification to the PR body of the dependency and explicity refer to the yaml file and workflow by their names. Moves the 'What do I need to do?' section further up the PR body.
We received some feedback that the instructions on how to test the workflow were unclear.
Ran dependency graph integrator locally, and checked the output was as expected.
=> Refactor: reword dependency graph integrator PR description

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Co-authored-by: @akash1810 
Changes the name of the Github app secret which provides repocop credentials from 'branch protector' to 'repocop'.
This more accurately reflects the use of the secret.
Tested on CODE.
=> refactor: rename repocop github credentials

packages/dev-environment/script/start, packages/dev-environment/script/start-prisma-migrate-test
Updates how we invoke docker; the `docker-compose` command has been replaced with `docker compose`.
I've also corrected some indentation levels, so it might be easier to [review w/out whitespace](https://github.com/guardian/service-catalogue/pull/1336/files?diff=split&w=1).
=> fix: Update docker syntax 

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/common/prisma/migrations/20241128170250_github_repository_custom_properties/migration.sql, packages/common/prisma/schema.prisma, packages/dev-environment/docker-compose.yaml
- upgrades github cloudquery plugin to v11 which provides a custom properties table
- creates a `github_repository_custom_properties` table in prisma schema
- creates the sql  migration
- adds the table to the docker-compose so that it can be queried in DEV
This follows from #1316. Using custom properties will allow us to move away from topics. Custom properties can be
made compulsory, which means we can enforce repos to choose a property.
The `production` custom property also applies branch protection.
=> feat: add Github custom properties table to cloudquery

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Co-authored-by: akash1810 <akash1810@users.noreply.github.com>
Doubles the memory for some of the Github Cloudquery tasks.
These have been failing recently and we suspect it is due to out-of-memory errors.
=> Fix: bump memory on github cloudquery tasks

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/repocop.ts
Allocates more memory to the repocop lambda, from 1024MB to 1536MB.
After [this change](https://github.com/guardian/service-catalogue/commit/e8e39d17e20fe99cba20100a40f962acaba08393#diff-f1ff53a8917a7ca393cb947297fc15e40d2132865ac31f7d1013f6a3e9b3cccd) was merged on 2 December, the memory use has doubled from around ~700MB to ~1400MB. 
Not sure why a change to add a cloudquery table which we are not querying in repocop has led to this increase.
I have created [a visualisation of the memory use since 25 November](https://logs.gutools.co.uk/s/devx/app/dashboards#/view/45c689cb-0068-4d79-90ad-11b08bd21128?_g=(refreshInterval:(pause:!t,value:60000),time:(from:'2024-11-25T00:00:00.000Z',to:'2024-12-03T17:27:55.287Z'))&_a=()) (when the first data point was available).
I increased the memory in …
=> fix: give repocop more memory

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
It gives an explicit schedule for running the task and increases memory from 512 MiB.
We're seeing the task bump along the current memory limit of 512 MiB.
We should see the task run successfully.
=> Configure schedule and memory for AmigoBakePackages task

packages/cloudbuster/src/digests.ts
Adds the account ID of the target account to the console.log for `cloudbuster`.
In `PROD`, the log was still indicating that the messages were being sent to `testing-alerts`, when in fact they were going to the real accounts. 
When this is merged, we should see real account IDs being logged out by `cloudbuster PROD`. I tested the `CODE` variant on CODE and the logging was as expected.
=> fix: log account cloudbuster messages are sent to in PROD

packages/cloudbuster/src/digests.ts, packages/cloudbuster/src/index.ts
- Uses logger in place of console.log
- Refactors the logic a little to make it clearer (is it?)
- logger allows for markers to be added - see comment in #1355
=> refactor: use logger in cloudbuster

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Moves schedule of [RepoCop](https://github.com/guardian/service-catalogue/blob/e38adda7ef2b1808beb613ff6d1d463cf3878f71/packages/cdk/lib/service-catalogue.ts#L252) and [CloudBuster](https://github.com/guardian/service-catalogue/blob/e38adda7ef2b1808beb613ff6d1d463cf3878f71/packages/cdk/lib/service-catalogue.ts#L297) production ECS tasks from 09:30 GMT weekdays to 07:00 GMT weekdays.
There's a scenario we've seen in PRs https://github.com/guardian/contributions-platform/pull/551 and https://github.com/guardian/contributions-platform/pull/552 where the [dependency-graph-integrator job](https://github.com/guardian/service-catalogue/tree/7427a293ddf38ffc46c0416b318a751ec238a327/packages/dependency-graph-integrator) runs working on stale data.
The job makes decisions depending on the service …
=> Reduce Likelihood of Duplicate Dependency Graph Update Workflow PRs

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Explicitly adds the `github_repository_custom_properties` table to the list of those collected by the GithubRepositories Cloudquery source.
All child tables are automatically collected, unless we specify them in the `skipTables` property. However, for clarity it is good to explicitly say what tables we want to collect.
=> refactor: explicitly add custom props table to cloudquery source

packages/common/prisma/schema.prisma, packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.test.ts, packages/repocop/src/remediation/dependency_graph-integrator/send-to-sns.ts, packages/repocop/src/types.ts
- Repocop collects the `github_repositories_custom_properties` table.
- Adds a check for the custom property `gu_dependency_graph_integrator_ignore` and excludes any repos that have this property from dependency graph integration.
- Updates the tests and adds a couple more for the exemptions.
There is at least one repo that we know of that contains a script written in Scala file but that doesn't use sbt. As there are no dependencies for Scala in the repo, it doesn't need to have the sbt dependency submission workflow. Currently, the dependency graph integrator will identify this repo as requiring a workflow, and continue to raise a PR against it if the existing PR is closed or if the workflow is not merged in.
=> Feat: allow for exemption of repos from dependency graph integrator

packages/dependency-graph-integrator/src/file-generator.test.ts, packages/dependency-graph-integrator/src/file-generator.ts
Using Java 21 to run the dependency graph submission workflow rather than Java 17.
Java 21 is the latest LTS version.
Several workflows have successfully run using Java 21, 
eg. https://github.com/guardian/myguardian-support-services/actions/runs/12869554808
=> Use Java 21 in dependency graph submission workflow

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/config.ts
This is the latest in the v6 major. [v6.0.0](https://github.com/cloudquery/cloudquery/blob/main/cli/CHANGELOG.md#600-2024-07-18) defaulted `skip_dependent_tables` to `true`, to avoid accidentally skipping a crucial table we're setting `skip_dependent_tables` to `false`.
We can remove this once we've switched to an "allow list" of tables.
N/A
---
Co-authored by: @kelvin-chappell.
=> feat: Update the CloudQuery CLI to v6.15.0

packages/common/prisma/migrations/20250131123229_drop_github_issue_pullrequest_reviews/migration.sql
Since #1350 we have stopped collecting this table.
The table is redundant.
---
Co-authored by: @kelvin-chappell.
=> feat: Remove the `github_issue_pullrequest_reviews` table from the database

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
This version includes updates to dependencies. See https://github.com/guardian/cq-source-ns1/releases/tag/v0.1.4.
=> chore(deps): Update the version of `guardian/cq-source-ns1` from 0.1.3 to 0.1.4

packages/cdk/lib/service-catalogue.ts
Address a deprecation warning. See https://github.com/aws/aws-cdk/blob/6a77e4f5cd872b4f3b985f1ea6eebd5d54aebd70/packages/aws-cdk-lib/aws-rds/lib/ca-certificate.ts#L18-L23.
This doesn't require a snapshot update as the old and new enum evaluate to the same value. That is, this is a no-op.
=> chore: Address a deprecation warning

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/schedule.test.ts, packages/cdk/lib/cloudquery/schedule.ts, packages/cdk/lib/cloudquery/task.ts, packages/common/prisma/migrations/20250204123000_frequency_milliseconds/migration.sql, packages/common/prisma/schema.prisma
> [!NOTE]
> These database changes have been [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/d96682c5-edcc-438c-8014-5dbedb24175e) and therefore the database schema is only compatible with this branch. Before testing another branch on CODE, we'll need to apply another migration to revert the schema change. Or, rebase the feature branch on this one.
Updates the `cloudquery_table_frequency` table to store frequency as milliseconds. Using milliseconds allows for a higher degree of accuracy. For example, we can identify tables that are updated multiple times a day.
To understand the daily rate, we can do:
```sql
SELECT table_name
, 86400000 / frequency AS daily_rate -- 86400000 = milliseconds in a day
FROM   cloudquery_table_frequency;
```
I've [deployed to …
=> feat: Change `frequency` column in `cloudquery_table_frequency` to milliseconds

package-lock.json, packages/cdk/package.json
Updates `@guardian/private-infrastructure-config` from v2.3.0 to v4.0.0; for some reason Dependabot has been missing this.
Updates GuCDK from v61.1.0 to v61.1.3.
---
Closes https://github.com/guardian/service-catalogue/pull/1395.
Resolves https://github.com/guardian/service-catalogue/security/dependabot/42.
Resolves https://github.com/guardian/service-catalogue/security/dependabot/43.
=> chore(deps): Update some Guardian libraries

.env, containers/cloudquery/Dockerfile
It appears v6.15.0 of the CloudQuery CLI image no longer includes `ca-certificates`, which provides the `update-ca-certificates` command. Add it back!
The changes in https://github.com/guardian/service-catalogue/pull/1405 didn't actually do anything as we have to manually publish a new image. I've added a note about this as an inline comment. We should automate this process in future though.
I've [manually run](https://github.com/guardian/service-catalogue/actions/runs/13175742340/job/36774525816) the [workflow](https://github.com/guardian/service-catalogue/blob/main/.github/workflows/cq-image.yml) to publish an image.
=> fix: Install `ca-certificates` package

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
This version includes some dependency updates.
See https://github.com/guardian/cq-source-galaxies/releases/tag/v1.1.9.
=> chore(deps): Update CloudQuery Galaxies plugin from v1.1.8 to v1.1.9

packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
This change ensures that not all vulnerabilities are reported as high severity.
It's misleading.
It's the same variable value that's used at the page level.
=> fix: Severity of vulnerability correctly reported in digests

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Collecting this data every 30 minutes equates to ~1M rows a day. Since the addition of the AMIgo bakes to Service Catalogue, the need to have this data "fresh" is reduced; daily is fine.
See also https://github.com/guardian/service-catalogue/pull/456.
See the updated snapshot.
---
Co-authored by: @adamnfish.
=> fix: Switch the `aws_ec2_images` table to be collected once a day

packages/common/prisma/migrations/20250212092000_aws_vpc_tables/migration.sql, packages/common/prisma/migrations/20250212092300_view_aws_vpcs/migration.sql, packages/common/prisma/schema.prisma, packages/common/prisma/views/public/view_aws_vpcs.sql, packages/dev-environment/docker-compose.yaml
Querying a VPC and its subnets to understand which subnet is private or public and their IP space is fairly complicated.
Encapsulating this in a view means this complexity is done once.
Rather than detail the complexity in the PR description, I've attempted to explain it with inline comments.
The data in this view enables us to create a dashboard to more easily visualise the shape of a VPC. I'm not yet sure how often we'll `SELECT` from the view. If we find we're exhausting the database, we could consider making it a materialised view that's [automatically refreshed after data collection](https://github.com/guardian/service-catalogue/pull/1048).
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/dd10ec76-fb50-4677-870b-c18078a54cf3) and can now see the view in [Grafana …
=> feat: Create a new SQL view for VPC details

packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.test.ts, packages/cdk/lib/service-catalogue.ts
The Service catalogue databased has started failing on and off since last week, and today it became unusable. This changed gives it more overhead in storage and compute, and enables extra monitoring features. This should enable us to inspect what is exactly has caused service catalogue to start falling over.
=> Add performance overhead and telemetry

packages/cdk/bin/cdk.ts
We've been running xlarge for a while, but we think we can get identical levels of performance by using a large instance instead.
This will help us decide which type of instance to reserve for the year.
=> Downgrade to t4g.large in PROD

packages/cdk/lib/cloudquery/schedule.test.ts
The expected result for this test seems to differ depending on when it is run (i.e. it passed yesterday and failed today). See also: https://github.com/guardian/service-catalogue/commit/a21e159107e7940ac40634a63e7633d8062a65df.
We could probably improve the function to make it more testable (or just update the expected value again), but I think it might be better to just remove this test.
=> Remove unstable test to fix build

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/task.ts
This PR makes the additional CloudQuery container used by the NS1 task read-only.
This should resolve two [high FSBP issues](https://www.google.com/url?q=https://metrics.gutools.co.uk/d/ddi3x35x70jy8d/fsbp-compliance?orgId%3D1%26var-account_name%3DDeploy%2520Tools%26var-control_id%3DAll&sa=D&source=calendar&ust=1745052925244270&usg=AOvVaw1P2gyoPxj79fTSMOoM7XBl) (one for `CODE` and one for `PROD`).
1. [Deployed this branch to `CODE`](https://riffraff.gutools.co.uk/deployment/view/830c4399-82bf-47c5-9c45-a1a162b38feb)
1. Ran the NS1 task using `npm -w cli start run-task -- --stage CODE --name NS1`
1. Checked [the logs](https://logs.gutools.co.uk/s/devx/app/r/s/JzOZB) - there is quite a lot here, but there [don't seem to be any errors](https://logs.gutools.co.uk/s/devx/app/r/s/tghef) and it …
=> fix: Make additional CQ container read-only (NS1 task)

packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.test.ts, packages/cdk/lib/service-catalogue.ts
Provisions an [anomaly detection](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html) alarm for the `EBSByteBalance` metric of the RDS instance. This is in reaction to a recent incident where we saw the database being unusable from Grafana. In triaging this incident, we saw the `EBSByteBalance` metric appearing to correlate with performance issues. With this alarm, we hope to catch issues earlier.
An anomaly detection alarm is chosen over a standard alarm as it wasn't immediately clear what the threshold for a standard alarm should be, as the existing metrics are quite spiky.
This changes instantiates level 1 CDK constructs as there aren't any level 2 constructs available for anomaly detection. The code was largely inspired by …
=> feat: Alarm on `EBSByteBalance` metric anomalies

.github/dependabot.yml, eslint.config.mjs, package-lock.json, package.json, packages/cdk/jest.setup.js, packages/cli/src/aws.ts, packages/cloudbuster/src/digests.test.ts, packages/data-audit/src/audit/aws-lambda.ts, packages/data-audit/src/audit/aws-s3-buckets.ts, packages/dependency-graph-integrator/src/index.ts, packages/interactive-monitor/src/js-parser.test.ts, tsconfig.json
- Replaces deprecated eslint-config-typescript dependency with eslint-config. 
- Bumps eslint to v9.24.0, and Typescript to v5.8.3. 
- Removes ignored lint comments from files which are no longer required.
This should improve our dependabot dependency bump experience in future, as eslint-config only has a dependency on eslint and not typescript (or tslib).
CI passes.
=> chore(deps): replace eslint-config-typescript with eslint-config

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/cluster.ts, packages/cdk/lib/cloudquery/config.test.ts, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/cloudquery/task.ts
Stops collecting data for the [`aws_costexplorer_cost_30d` table](https://hub.cloudquery.io/plugins/source/cloudquery/aws/latest/tables/aws_costexplorer_cost_30d), replacing it with the [`aws_costexplorer_cost_custom` table](https://hub.cloudquery.io/plugins/source/cloudquery/aws/latest/tables/aws_costexplorer_cost_custom). This table supports aggregation. We're aggregating by the `App`, `Stack` and `Stage` tags, which should allow us to understand the cost of an individual service.
Data is collected for every account in the AWS organisation. Previously only data for the Workflow account was collected.
Collection of `aws_costexplorer_cost_custom` runs daily at midnight, with a window for two days ago. That is, at midnight of 25 April 2025, we collect data the period of 23 April 2025 - 24 …
=> feat: Daily collection of `aws_costexplorer_cost_custom`

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Patches the changes in #1510, which fails to run with the follow error:
> operation error Cost Explorer: GetCostAndUsage, https response error StatusCode: 400, RequestID: 8e41a8fb-c06f-42b8-9892-6cc3f285d3bf, api error ValidationException: Only two values for GroupBy are allowed
Confession: I only tested #1510 on CODE with a group by of `App` and `Stage`, which is why I didn't see this error originally!
=> fix: Call `GetCostAndUsage` correctly

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts, packages/cli/README.md, packages/cli/src/aws.ts, packages/cli/src/index.ts
Following from https://github.com/guardian/service-catalogue/pull/1510 this change updates the Service Catalogue CLI to allow setting of environment variables within the CloudQuery container. This allows us to backfill data for the `AwsCostExplorer` task by running:
```bash
npm -w cli start -- run-task \
--stage PROD \
--name AwsCostExplorer \
--env START_DATE=2025-01-01 \
--env END_DATE=2025-02-01
```
This utilises the [container overrides](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerOverride.html).
To backfill data on demand.
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/c873a3b6-807a-43db-b492-6a54d4b94610). After running the following:
```bash
npm -w cli start -- run-task \
--stage CODE \
--name AwsCostExplorer \
--env …
```
=> feat: Enable on demand backfill of `aws_costexplorer_cost_custom`

.github/dependabot.yml
I was surprised to see #1519 and #1520 as separate PRs. This change updates the Dependabot configuration to bump all eslint plugins [together](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#patterns-and-exclude-patterns-groups), ensuring they're compatible with each other.
=> chore(dependabot): Group eslint plugin updates

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/index.ts, packages/cdk/lib/cloudquery/versions.ts
We currently have a [spreadsheet](https://docs.google.com/spreadsheets/d/1vG1BKgBIf_mTv4s5PaRL9sePjayumDI5ftZVzsr-h_U/edit?gid=0#gid=0) to track when software becomes EOL. This spreadsheet is manually updated using https://endoflife.date.
This change brings the information from endoflife.date into Service Catalogue, with a future vision of automating the spreadsheet. The data is collected once a month, on the hypothesis that the data doesn't change that often.
In CODE, this has created ~6000 rows in the database. This does not exceed our usage quota.
See also:
- https://www.cloudquery.io/blog/what-we-learned-querying-cloud-infra-for-expired-dependencies
- https://hub.cloudquery.io/plugins/source/cloudquery/endoflife/latest/docs
I've [deployed to …
=> feat(cloudquery): Collect data from `endoflife.date` once a month

packages/common/prisma/migrations/20250519144107_view_domain_tag_fix_slow_join/migration.sql, packages/common/prisma/views/public/view_domain_tags.sql
Improves performance by adjusting the join between `aws_acm_certificates` and `arn_tag_sets`. 
```SQL
= ANY(cert.in_use_by)
```
Total request time: 10.7 s
```SQL
= cert.in_use_by [1]
```
Total request time: 468 ms
To improve performance of the [Tools Audit dashboard ](https://metrics.gutools.co.uk/d/aegzv59r9eghsd/tool-audit).
This change has been run into PROD for testing and to unblock a demo.
=> Improves the view_domain_tag performance

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Reduces the amount if inspector findings we ingest
It would be nice to get the severity filter in the first commit working, but CloudQuery is extremely grumpy about how to get a number into its table spec, and I haven't worked that out yet.
Currently our daily findings our 500k. Collecting only active findings cuts that number in half, which is particularly useful when you're about to scale up your use of inspector massively.
Deployed to CODE, verified execution and reduction in size of dataset
=> Filter inspector findings

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
Rolling out inspector and guard duty more widely means that we are collecting much more data in security hub. This PR brings the row count down to a sustainable (but still elevated) level
We have a limit on the number of CQ rows we can sync every month
Tested on CODE. In terms of row count, we have gone from x -> 5x -> 2x
In the future, if we turn off the tagging data, we could eliminate the `LOW` and `INFORMATIONAL` severity levels, and significantly reduce the amount of data we collect again, potentially to below our original level.
=> modify the securityhub_findings filter to reduce data collected

package-lock.json, packages/common/package.json
Dependabot's octokit upgrades have been failing for months. Let's update the ones we can now, and figure the rest out later.
=> update some deps dependabot can't manage

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/index.ts
- Uses a Github App to authenticate the collection of the github_languages table by the custom Cloudquery plugin.
- Removes the creation of a PAT token which we should no longer need.
Replaces the use of a single GitHub access token with app-based authentication. It also updates related configurations, secrets management, and infrastructure definitions to align with this new authentication method.
* Replaced the use of the `GITHUB_ACCESS_TOKEN` secret with three new secrets: `GITHUB_PRIVATE_KEY`, `GITHUB_APP_ID`, and `GITHUB_INSTALLATION_ID`, for GitHub app-based authentication. (`packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap`: [packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snapL16237-R16281](diffhunk://#diff-f1ff53a8917a7ca393cb947297fc15e40d2132865ac31f7d1013f6 …
=> feat: use a Github App to authenticate the github languages cloudquery task

.github/actions/npm-run/action.yml, .github/workflows/ci.yml, .github/workflows/cq-image.yml, .github/workflows/prisma-migrate-image.yml, .github/workflows/release-image.yml, .github/workflows/singleton.yml, .github/workflows/stale.yml, .github/workflows/zizmor.yml
Integrate the service catalogue with [Zizmor](https://docs.zizmor.sh/). Zizmor is a tool that performs static analysis on GitHub actions. It seems to be named after a still-living [New York dermatologist](https://www.bbc.co.uk/news/blogs-trending-35226720), who was famous for his subway adverts?
When integrated with a repo for the first time, This action will not fail when issues are detected - it will instead generate issues in the Security tab of the repo, so teams can deal with them as and when they have time. This mimics the behaviour of dependabot, and you can see an example of existing issues [here](https://github.com/guardian/service-catalogue/security/code-scanning?query=is%3Aopen+branch%3Ant%2Fzizmor-high+).
However, if a _new_ issue is added to the repo, CI will fail. You can …
=> Integrate zizmor with service catalogue

packages/common/prisma/migrations/20250723075100_view_aws_vpcs/migration.sql
Updates the view created in https://github.com/guardian/service-catalogue/pull/1437 to show all CIDR blocks of a VPC. This view primarily drives the [aws-account-vpcs dashboard](https://metrics.gutools.co.uk/d/aecrxbaf4e800e/aws-account-vpcs); the column name and type remain the same (string) so the dashboard shouldn't need updating.
Accuracy! Previously, there was an assumption that every VPC had one CIDR block.
I've [ran the query in Grafana](https://metrics.gutools.co.uk/goto/Q7E2QjUHg?orgId=1), filtering for a VPC known to have multiple CIDR blocks. The results are correct.
=> feat: Display all CIDR blocks in `view_aws_vpcs`

packages/cloudbuster/src/run-locally.ts, packages/data-audit/package.json, packages/data-audit/src/index.ts, packages/data-audit/src/run-locally.ts, packages/dependency-graph-integrator/src/run-locally.ts, packages/interactive-monitor/package.json, packages/interactive-monitor/src/index.ts, packages/interactive-monitor/src/js-parser.test.ts, packages/repocop/src/run-locally.ts
- Updates the run-locally scripts in various packages to use ESM syntax rather than CommonJS. ESM modules don’t expose a concept of 'main module' like CommonJS does, so Node.js can’t natively tell if a module is the entry point. Instead, we use a comparison of the URL of the current module file with the path of the script. See comments in the `run-locally.ts` files for more information.
- Adds `"type":"module"` to `package.json`s that were missing it.
Running locally for several packages was broken after the recent bump to ESM.
Running locally works now for all packages that were broken.
=> fix: local running of packages

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/interactive-monitor.ts
Allows interactive-monitor to publish to anghammarad
interactive-monitor is identifying australian interactives, but is failing to apply the topics to them. This is because anghammarad sends out a notification just before the topic is applied, and this lambda does not currently have permission to publish to anghammarad.
Allowing us to notify users means we can move on to the next stage of the process, which is applying the new tags
=> allow interactive monitor to publish to anghammarad

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Updates the [End Of Life CloudQuery plugin](https://hub.cloudquery.io/plugins/source/cloudquery/endoflife/latest/versions) to the current latest.
=> chore(deps): Update End Of Life CloudQuery plugin to 1.4.0

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/common/src/database-queries.ts, packages/obligatron/src/index.ts, packages/obligatron/src/obligations/github-topics.test.ts, packages/obligatron/src/obligations/github-topics.ts, packages/obligatron/src/obligations/index.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts
- Moves `getRepositories` to common
- Creates a new `REPOSITORY_STATUS` obligation that checks for the existence of particular topics
At the moment, this code does not attempt to find the repo owner. It only performs the evaluation. This is because it is an MVP, and adding the logic to find the owner would increase the complexity of this PR. This is addressed in #1594 
It also does not find interactives, as `guardian_production_status` doesn't currently include  `interactive` as a value. This will be fixed in #1593 
All unarchived repositories should have a valid production status, so that its security obligations can be evaluated accurately. Tracking the number of repos that do not have one of these statuses means we have a ceiling of how many repos are not being tracked by repocop, that …
=> Track the number of repos that do not have a valid production status

packages/interactive-monitor/src/index.ts
When the interactive-monitor notification goes out, allow the user to click a link, taking them to the repo on GitHub
Better user experience
Verified behaviour on CODE
=> Link to newly tagged interactives

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
This PR adds a dedicated task for SNS topic data, so that we can refresh the data every night. Prior to this PR the `aws_sns_topics` table was updated as part of the [catch-all AWS task](https://github.com/guardian/service-catalogue/blob/22e9930660da89e2be4686462a31562e6060d56d/packages/cdk/lib/cloudquery/index.ts#L339-L371), which [runs weekly](https://github.com/guardian/service-catalogue/blob/22e9930660da89e2be4686462a31562e6060d56d/packages/cdk/lib/cloudquery/index.ts#L349).
We want to [monitor/alert on SNS topic misconfiguration](https://trello.com/c/SJE8dmow/368-check-if-sns-topic-subscriptions-for-slo-alerts-have-all-been-confirmed), as this can lead to failures delivering alarm notifications.
These alerts will be more accurate and useful if we are refreshing the data regularly. …
=> Collect SNS topic data every night

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/config.ts, packages/cdk/lib/cloudquery/index.ts
We'd like to understand more about how https://github.com/guardian/cdk is being used. We already know which version of GuCDK a service is using. Collecting `github_releases` for this repository will allow us to determine the latest version of GuCDK available, and thus how up-to-date the estate is.
This change collects `github_releases` for individual repositories rather than the entire organisation as it's yet not known how expensive this would be on the GitHub API rate limits and CloudQuery row limits - [we're already explicitly skipping this table](https://github.com/guardian/service-catalogue/blob/1cd2bd04f3ca45766b54b17229738f06b4c41cfd/packages/cdk/lib/cloudquery/index.ts#L428-L431).
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/003820dd-6619-4ca2-b1dd-3948472 …
=> feat(cloudquery): Collect `github_releases` for `guardian/cdk`

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudbuster.ts, packages/cdk/lib/repocop.ts, packages/cdk/lib/service-catalogue.ts, packages/cloudbuster/package.json, packages/cloudbuster/src/config.ts, packages/cloudbuster/src/digests.test.ts, packages/cloudbuster/src/digests.ts, packages/cloudbuster/src/index.ts, packages/repocop/package.json, packages/repocop/src/config.ts, packages/repocop/src/index.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.ts
Allows the cutoff date for vulnerability digest notification to be common between repocop and cloudbuster
They use the same vulnerability reporting schedule. Typically when we want to change one, we also want to change the other.
Unit tests have been updated
Tested on CODE
=> Make maximum vulnerability age for digest common

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/service-catalogue.ts
Reduces the window for teams to be alerted about new issues from 60 to 45 days.
Reducing the number of times we notify teams about an issue will help teams deal with alert fatigue. 60 days was chosen as an arbitrary number longer than the SLA period - 45 also meets that brief.
CI passes
=> reduce maximum age for digest inclusion

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
This PR updates the write mode for the new GitHub releases task, which was introduced in https://github.com/guardian/service-catalogue/pull/1600. By using `overwrite` instead of `overwrite-delete-stale`, we can collect release information for the `cdk` repository without accidentally clearing rows for all other repos from the `github_repositories` table.
Prior to this PR, the new releases task was overwriting all data in the `github_repositories` table (which is a [dependency for the `github_releases` table](https://hub.cloudquery.io/plugins/source/cloudquery/github/v14.1.1/tables/github_releases)). Because we are [limiting the releases task to a single repository (`cdk`)](https://github.com/guardian/service-catalogue/blob/e7c21a85c3788bbd143b00303180110b17e20e46/packages/cdk/lib/cloudquer …
=> Attempt to fix GitHub releases task

packages/obligatron/src/obligations/github-topics.test.ts, packages/obligatron/src/obligations/github-topics.ts
We have a table, called `guardian_non_p_and_e_github_teams`, that enumerates teams outside of the department. Repos owned by these teams are not required to use production statuses listed in `guardian_production_status`. This PR excludes repositories owned exclusively by external teams from this obligation
Only teams inside P&E are required to use topics as a production status
The new code has been unit tested. It has also been deployed to CODE, where we see a 30% reduction in repos breaking the rule
=> Exclude repos from REPOSITORY_STATUS obligation if they do not belong to P&E

.env, packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap
Updates Galaxies plugin for CloudQuery to 1.1.10, which includes various dependency updates. See https://github.com/guardian/cq-source-galaxies/releases/tag/v1.1.10.
After [deploying to CODE](https://riffraff.gutools.co.uk/deployment/view/5f3fe90b-fefc-488e-8225-eb467375a280), we can run the Galaxies task via:
```bash
npm -w cli start -- run-task --stage CODE --name Galaxies
```
We can then query the data in Grafana, observing [the `_cq_sync_time` column](https://metrics.code.dev-gutools.co.uk/goto/U1CznTrNg?orgId=1):
=> chore(deps): Update Galaxies CloudQuery plugin from 1.1.9 to 1.1.10

packages/common/prisma/migrations/20250922134600_repocop_vulns_update/migration.sql, packages/common/prisma/schema.prisma, packages/common/src/types.test.ts, packages/common/src/types.ts, packages/obligatron/src/obligations/dependency-vulnerabilities.test.ts, packages/obligatron/src/obligations/dependency-vulnerabilities.ts, packages/repocop/src/evaluation/repository.test.ts, packages/repocop/src/evaluation/repository.ts, packages/repocop/src/index.ts, packages/repocop/src/query.ts, packages/repocop/src/remediation/vuln-digest/vuln-digest.test.ts, packages/repocop/src/utils.test.ts
The first in a sequence of PRs to provide runtime dependencies to the repocop dashboard.
This PR:
- Adds a `scope` column to the repocop vulnerabilities table
- Partitions the vulnerabilities based on scope, rather than filtering them, so we can use the development vulnerabilities later
Technically, the `scope` value is optional, according to the Octokit API. In the (unusual) case the GitHub can't tell whether a dependency is runtime or development, the safest option is to assume that it _is_ being used at runtime, and include it in the SLA requirement as a precaution. This also keeps the data model a bit simpler for grafana purposes. If a new type of scope is created, repocop will start logging this.
So the service catalogue can store and display information about dev vulnerabilities, …
=> Indicate vulnerability scope

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/index.ts
This makes the scheduling of `aws_cloudwatch_alarms` match `aws_elbv1_load_balancers` and `aws_elbv2_load_balancers`.
We get alerts for when a cloudwatch alarm references a non-existing LB. The frequency of the load balancer tables means we can detect when a LB disappears quite quickly, but detecting the fixed cloudwatch alarm only happens over night.
I think this change is low risk from a code perspective, so I haven't validated it.
The question that worries me is if the increased row consumption is going to be a problem? The table currently has `3520` rows, so with this change I think it means 168,960 rows a day or ~5M/month?
=> Increase frequency for cloudwatch table

packages/cdk/lib/__snapshots__/service-catalogue.test.ts.snap, packages/cdk/lib/cloudquery/allow-list-tables/riffraff-table-list.ts, packages/common/prisma/migrations/20250930121946_drop_riffraff_authorized_users_table/migration.sql
This PR removes the unused `riffraff_authorized_users` table and prevents further attempts to sync this table. As a follow-up to this, we'll also deploy https://github.com/guardian/riff-raff/pull/1475, which will remove the resources on the Riff-Raff side.
This table was originally added in https://github.com/guardian/riff-raff/pull/1273 and https://github.com/guardian/service-catalogue/pull/424.
This list of users has been irrelevant since https://github.com/guardian/riff-raff/pull/1464 was merged, so there is no value in keeping this table in Service Catalogue.
We don't believe that this table was ever really used so there are no current plans to sync the up-to-date list of users to Service Catalogue as a replacement.
Prior to deploying this branch to `CODE`, I confirmed that it was …
=> Remove unused riffraff_authorized_users table

packages/repocop/src/languages.ts
Fixes a typo in RenderScript which is case-sensitive.
Adds ObjectScript to the ignore list.
Repos were still being reported as not having vulnerability tracking based on these languages which should be ignored.
=> Fix: update ignored languages
